/* exoFComplete.c generated by valac 0.12.1, the Vala compiler
 * generated from exoFComplete.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define EXOGENESIS_TYPE_FCOMPLETE (exogenesis_fcomplete_get_type ())
#define EXOGENESIS_FCOMPLETE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_FCOMPLETE, ExogenesisFComplete))
#define EXOGENESIS_FCOMPLETE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_FCOMPLETE, ExogenesisFCompleteClass))
#define EXOGENESIS_IS_FCOMPLETE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_FCOMPLETE))
#define EXOGENESIS_IS_FCOMPLETE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_FCOMPLETE))
#define EXOGENESIS_FCOMPLETE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_FCOMPLETE, ExogenesisFCompleteClass))

typedef struct _ExogenesisFComplete ExogenesisFComplete;
typedef struct _ExogenesisFCompleteClass ExogenesisFCompleteClass;
typedef struct _ExogenesisFCompletePrivate ExogenesisFCompletePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _ExogenesisFComplete {
	GtkLayout parent_instance;
	ExogenesisFCompletePrivate * priv;
};

struct _ExogenesisFCompleteClass {
	GtkLayoutClass parent_class;
};

struct _ExogenesisFCompletePrivate {
	GtkFixed* fxdLayout;
	GtkButton* btnReboot;
	GtkButton* btnContinue;
	GtkLabel* lblPostInstall;
	GtkImage* imgFinished;
};


static gpointer exogenesis_fcomplete_parent_class = NULL;
extern gchar* exogenesis_AppPath;

GType exogenesis_fcomplete_get_type (void) G_GNUC_CONST;
#define EXOGENESIS_FCOMPLETE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXOGENESIS_TYPE_FCOMPLETE, ExogenesisFCompletePrivate))
enum  {
	EXOGENESIS_FCOMPLETE_DUMMY_PROPERTY
};
ExogenesisFComplete* exogenesis_fcomplete_new (void);
ExogenesisFComplete* exogenesis_fcomplete_construct (GType object_type);
static void exogenesis_fcomplete_Build (ExogenesisFComplete* self);
static void exogenesis_fcomplete_LoadImage (ExogenesisFComplete* self);
#define EXOGENESIS_UIPath "/home/steve/1-work/anjuta/exogenesis/src/exogenesis.ui"
void exogenesis_fcomplete_OnBtnReboot_Click (ExogenesisFComplete* self);
static void _exogenesis_fcomplete_OnBtnReboot_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_fcomplete_OnBtnContinue_Click (ExogenesisFComplete* self);
static void _exogenesis_fcomplete_OnBtnContinue_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_general_functions_LogIt (const gchar* Message);
static void exogenesis_fcomplete_finalize (GObject* obj);


ExogenesisFComplete* exogenesis_fcomplete_construct (GType object_type) {
	ExogenesisFComplete * self = NULL;
	self = (ExogenesisFComplete*) g_object_new (object_type, NULL);
	exogenesis_fcomplete_Build (self);
	exogenesis_fcomplete_LoadImage (self);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) self->priv->fxdLayout);
	return self;
}


ExogenesisFComplete* exogenesis_fcomplete_new (void) {
	return exogenesis_fcomplete_construct (EXOGENESIS_TYPE_FCOMPLETE);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _exogenesis_fcomplete_OnBtnReboot_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fcomplete_OnBtnReboot_Click (self);
}


static void _exogenesis_fcomplete_OnBtnContinue_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fcomplete_OnBtnContinue_Click (self);
}


static void exogenesis_fcomplete_Build (ExogenesisFComplete* self) {
	GtkBuilder* _tmp0_ = NULL;
	GtkBuilder* builder;
	GObject* _tmp1_ = NULL;
	GtkFixed* _tmp2_;
	GObject* _tmp3_ = NULL;
	GtkButton* _tmp4_;
	GObject* _tmp5_ = NULL;
	GtkButton* _tmp6_;
	GObject* _tmp7_ = NULL;
	GtkLabel* _tmp8_;
	GObject* _tmp9_ = NULL;
	GtkImage* _tmp10_;
	gint _tmp11_;
	gint _tmp12_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_builder_new ();
	builder = _tmp0_;
	gtk_builder_add_from_file (builder, EXOGENESIS_UIPath, &_inner_error_);
	if (_inner_error_ != NULL) {
		_g_object_unref0 (builder);
		goto __catch0_g_error;
	}
	_tmp1_ = gtk_builder_get_object (builder, "fxdComplete");
	_tmp2_ = _g_object_ref0 (GTK_FIXED (_tmp1_));
	_g_object_unref0 (self->priv->fxdLayout);
	self->priv->fxdLayout = _tmp2_;
	_tmp3_ = gtk_builder_get_object (builder, "btnReboot");
	_tmp4_ = _g_object_ref0 (GTK_BUTTON (_tmp3_));
	_g_object_unref0 (self->priv->btnReboot);
	self->priv->btnReboot = _tmp4_;
	_tmp5_ = gtk_builder_get_object (builder, "btnContinue");
	_tmp6_ = _g_object_ref0 (GTK_BUTTON (_tmp5_));
	_g_object_unref0 (self->priv->btnContinue);
	self->priv->btnContinue = _tmp6_;
	_tmp7_ = gtk_builder_get_object (builder, "lblInstalled");
	_tmp8_ = _g_object_ref0 (GTK_LABEL (_tmp7_));
	_g_object_unref0 (self->priv->lblPostInstall);
	self->priv->lblPostInstall = _tmp8_;
	_tmp9_ = gtk_builder_get_object (builder, "imgFinished");
	_tmp10_ = _g_object_ref0 (GTK_IMAGE (_tmp9_));
	_g_object_unref0 (self->priv->imgFinished);
	self->priv->imgFinished = _tmp10_;
	g_signal_connect_object (self->priv->btnReboot, "clicked", (GCallback) _exogenesis_fcomplete_OnBtnReboot_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btnContinue, "clicked", (GCallback) _exogenesis_fcomplete_OnBtnContinue_Click_gtk_button_clicked, self, 0);
	g_object_get ((GtkWidget*) self->priv->fxdLayout, "width-request", &_tmp11_, NULL);
	g_object_set ((GtkWidget*) self, "width-request", _tmp11_, NULL);
	g_object_get ((GtkWidget*) self->priv->fxdLayout, "height-request", &_tmp12_, NULL);
	g_object_set ((GtkWidget*) self, "height-request", _tmp12_, NULL);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (builder);
	goto __finally0;
	__catch0_g_error:
	{
		GError * err;
		gchar* _tmp13_;
		gchar* _tmp14_;
		GtkMessageDialog* _tmp15_ = NULL;
		GtkMessageDialog* _tmp16_;
		GtkMessageDialog* msg;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp13_ = g_strconcat ("Failed to load UI\n", err->message, NULL);
		_tmp14_ = _tmp13_;
		_tmp15_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_ERROR, GTK_BUTTONS_CANCEL, _tmp14_);
		_tmp16_ = g_object_ref_sink (_tmp15_);
		_g_free0 (_tmp14_);
		msg = _tmp16_;
		gtk_dialog_run ((GtkDialog*) msg);
		gtk_main_quit ();
		_g_object_unref0 (msg);
		_g_error_free0 (err);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void exogenesis_fcomplete_LoadImage (ExogenesisFComplete* self) {
	gchar* _tmp0_ = NULL;
	gchar* file;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup_printf ("%s/images/reboot_or_continue.png", exogenesis_AppPath);
	file = _tmp0_;
	gtk_image_set_from_file (self->priv->imgFinished, file);
	_g_free0 (file);
	goto __finally1;
	__catch1_g_error:
	{
		GError * err;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp1_ = g_strdup_printf ("ERROR - %s\n", err->message);
		_tmp2_ = _tmp1_;
		exogenesis_general_functions_LogIt (_tmp2_);
		_g_free0 (_tmp2_);
		_g_error_free0 (err);
	}
	__finally1:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


void exogenesis_fcomplete_OnBtnReboot_Click (ExogenesisFComplete* self) {
	g_return_if_fail (self != NULL);
}


void exogenesis_fcomplete_OnBtnContinue_Click (ExogenesisFComplete* self) {
	g_return_if_fail (self != NULL);
}


static void exogenesis_fcomplete_class_init (ExogenesisFCompleteClass * klass) {
	exogenesis_fcomplete_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ExogenesisFCompletePrivate));
	G_OBJECT_CLASS (klass)->finalize = exogenesis_fcomplete_finalize;
}


static void exogenesis_fcomplete_instance_init (ExogenesisFComplete * self) {
	self->priv = EXOGENESIS_FCOMPLETE_GET_PRIVATE (self);
}


static void exogenesis_fcomplete_finalize (GObject* obj) {
	ExogenesisFComplete * self;
	self = EXOGENESIS_FCOMPLETE (obj);
	_g_object_unref0 (self->priv->fxdLayout);
	_g_object_unref0 (self->priv->btnReboot);
	_g_object_unref0 (self->priv->btnContinue);
	_g_object_unref0 (self->priv->lblPostInstall);
	_g_object_unref0 (self->priv->imgFinished);
	G_OBJECT_CLASS (exogenesis_fcomplete_parent_class)->finalize (obj);
}


GType exogenesis_fcomplete_get_type (void) {
	static volatile gsize exogenesis_fcomplete_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_fcomplete_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisFCompleteClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_fcomplete_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisFComplete), 0, (GInstanceInitFunc) exogenesis_fcomplete_instance_init, NULL };
		GType exogenesis_fcomplete_type_id;
		exogenesis_fcomplete_type_id = g_type_register_static (GTK_TYPE_LAYOUT, "ExogenesisFComplete", &g_define_type_info, 0);
		g_once_init_leave (&exogenesis_fcomplete_type_id__volatile, exogenesis_fcomplete_type_id);
	}
	return exogenesis_fcomplete_type_id__volatile;
}



