/* exoFTimeZone.c generated by valac 0.12.1, the Vala compiler
 * generated from exoFTimeZone.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <stdio.h>


#define EXOGENESIS_TYPE_FTIME_ZONE (exogenesis_ftime_zone_get_type ())
#define EXOGENESIS_FTIME_ZONE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_FTIME_ZONE, ExogenesisFTimeZone))
#define EXOGENESIS_FTIME_ZONE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_FTIME_ZONE, ExogenesisFTimeZoneClass))
#define EXOGENESIS_IS_FTIME_ZONE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_FTIME_ZONE))
#define EXOGENESIS_IS_FTIME_ZONE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_FTIME_ZONE))
#define EXOGENESIS_FTIME_ZONE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_FTIME_ZONE, ExogenesisFTimeZoneClass))

typedef struct _ExogenesisFTimeZone ExogenesisFTimeZone;
typedef struct _ExogenesisFTimeZoneClass ExogenesisFTimeZoneClass;
typedef struct _ExogenesisFTimeZonePrivate ExogenesisFTimeZonePrivate;

#define EXOGENESIS_TYPE_TZ_WIDGET (exogenesis_tz_widget_get_type ())
#define EXOGENESIS_TZ_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_TZ_WIDGET, ExogenesisTZWidget))
#define EXOGENESIS_TZ_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_TZ_WIDGET, ExogenesisTZWidgetClass))
#define EXOGENESIS_IS_TZ_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_TZ_WIDGET))
#define EXOGENESIS_IS_TZ_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_TZ_WIDGET))
#define EXOGENESIS_TZ_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_TZ_WIDGET, ExogenesisTZWidgetClass))

typedef struct _ExogenesisTZWidget ExogenesisTZWidget;
typedef struct _ExogenesisTZWidgetClass ExogenesisTZWidgetClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define EXOGENESIS_TYPE_FTIME_ADJUST_MAN (exogenesis_ftime_adjust_man_get_type ())
#define EXOGENESIS_FTIME_ADJUST_MAN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_FTIME_ADJUST_MAN, ExogenesisFTimeAdjustMan))
#define EXOGENESIS_FTIME_ADJUST_MAN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_FTIME_ADJUST_MAN, ExogenesisFTimeAdjustManClass))
#define EXOGENESIS_IS_FTIME_ADJUST_MAN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_FTIME_ADJUST_MAN))
#define EXOGENESIS_IS_FTIME_ADJUST_MAN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_FTIME_ADJUST_MAN))
#define EXOGENESIS_FTIME_ADJUST_MAN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_FTIME_ADJUST_MAN, ExogenesisFTimeAdjustManClass))

typedef struct _ExogenesisFTimeAdjustMan ExogenesisFTimeAdjustMan;
typedef struct _ExogenesisFTimeAdjustManClass ExogenesisFTimeAdjustManClass;

#define EXOGENESIS_TYPE_INSTALL_DATA (exogenesis_install_data_get_type ())
#define EXOGENESIS_INSTALL_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallData))
#define EXOGENESIS_INSTALL_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallDataClass))
#define EXOGENESIS_IS_INSTALL_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_INSTALL_DATA))
#define EXOGENESIS_IS_INSTALL_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_INSTALL_DATA))
#define EXOGENESIS_INSTALL_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallDataClass))

typedef struct _ExogenesisInstallData ExogenesisInstallData;
typedef struct _ExogenesisInstallDataClass ExogenesisInstallDataClass;

#define EXOGENESIS_TYPE_MAIN_WIN (exogenesis_main_win_get_type ())
#define EXOGENESIS_MAIN_WIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWin))
#define EXOGENESIS_MAIN_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWinClass))
#define EXOGENESIS_IS_MAIN_WIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_MAIN_WIN))
#define EXOGENESIS_IS_MAIN_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_MAIN_WIN))
#define EXOGENESIS_MAIN_WIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWinClass))

typedef struct _ExogenesisMainWin ExogenesisMainWin;
typedef struct _ExogenesisMainWinClass ExogenesisMainWinClass;

struct _ExogenesisFTimeZone {
	GtkBox parent_instance;
	ExogenesisFTimeZonePrivate * priv;
};

struct _ExogenesisFTimeZoneClass {
	GtkBoxClass parent_class;
	void (*Build) (ExogenesisFTimeZone* self);
};

struct _ExogenesisFTimeZonePrivate {
	GtkBox* boxTimeZone;
	GtkButton* btnPrevious;
	GtkLabel* lblTimeZoneTitle;
	GtkImage* imgTimezone;
	GtkBox* boxTZWidget;
	GtkLabel* lblCurrentTime;
	GtkButton* btnManual;
	GtkButton* btnNext;
	GtkBox* boxMain;
	ExogenesisTZWidget* _tzmap;
	gchar* _SelectedTimeZone;
	struct tm _SelectedTime;
	guint timerID;
	gboolean _ManualTime;
};


static gpointer exogenesis_ftime_zone_parent_class = NULL;
extern ExogenesisInstallData* exogenesis_gInstallData;

GType exogenesis_ftime_zone_get_type (void) G_GNUC_CONST;
GType exogenesis_tz_widget_get_type (void) G_GNUC_CONST;
#define EXOGENESIS_FTIME_ZONE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXOGENESIS_TYPE_FTIME_ZONE, ExogenesisFTimeZonePrivate))
enum  {
	EXOGENESIS_FTIME_ZONE_DUMMY_PROPERTY
};
void exogenesis_ftime_zone_Build (ExogenesisFTimeZone* self);
static void exogenesis_ftime_zone_real_Build (ExogenesisFTimeZone* self);
#define EXOGENESIS_UIPath "/home/steve/1-work/anjuta/exogenesis/src/exogenesis.ui"
void exogenesis_ftime_zone_OnBtnChangeTime_Click (ExogenesisFTimeZone* self);
static void _exogenesis_ftime_zone_OnBtnChangeTime_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_ftime_zone_OnBtnTZNext_Click (ExogenesisFTimeZone* self);
static void _exogenesis_ftime_zone_OnBtnTZNext_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_ftime_zone_OnBtnTZPrevious_Click (ExogenesisFTimeZone* self);
static void _exogenesis_ftime_zone_OnBtnTZPrevious_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_ftime_zone_OnRealised (ExogenesisFTimeZone* self);
static void _exogenesis_ftime_zone_OnRealised_gtk_widget_realize (GtkWidget* _sender, gpointer self);
ExogenesisTZWidget* exogenesis_tz_widget_new (void);
ExogenesisTZWidget* exogenesis_tz_widget_construct (GType object_type);
void exogenesis_ftime_zone_OnTimeZoneSelected (ExogenesisFTimeZone* self, const gchar* Zone, struct tm* localtime);
static void _exogenesis_ftime_zone_OnTimeZoneSelected_exogenesis_tz_widget_time_zone_selected (ExogenesisTZWidget* _sender, const gchar* Zone, struct tm* localtime, gpointer self);
ExogenesisFTimeZone* exogenesis_ftime_zone_new (void);
ExogenesisFTimeZone* exogenesis_ftime_zone_construct (GType object_type);
gboolean exogenesis_ftime_zone_OnTimer (ExogenesisFTimeZone* self);
static gboolean _exogenesis_ftime_zone_OnTimer_gsource_func (gpointer self);
static void exogenesis_ftime_zone_DisplayTime (ExogenesisFTimeZone* self);
ExogenesisFTimeAdjustMan* exogenesis_ftime_adjust_man_new (void);
ExogenesisFTimeAdjustMan* exogenesis_ftime_adjust_man_construct (GType object_type);
GType exogenesis_ftime_adjust_man_get_type (void) G_GNUC_CONST;
GType exogenesis_install_data_get_type (void) G_GNUC_CONST;
void exogenesis_install_data_set_TimeZone (ExogenesisInstallData* self, const gchar* value);
GType exogenesis_main_win_get_type (void) G_GNUC_CONST;
void exogenesis_main_win_ShowNextWindow (ExogenesisMainWin* self);
void exogenesis_main_win_ShowPreviousWindow (ExogenesisMainWin* self);
static void exogenesis_ftime_zone_ShowAllocs (ExogenesisFTimeZone* self, GtkContainer* x);
static void exogenesis_ftime_zone_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _exogenesis_ftime_zone_OnBtnChangeTime_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_ftime_zone_OnBtnChangeTime_Click (self);
}


static void _exogenesis_ftime_zone_OnBtnTZNext_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_ftime_zone_OnBtnTZNext_Click (self);
}


static void _exogenesis_ftime_zone_OnBtnTZPrevious_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_ftime_zone_OnBtnTZPrevious_Click (self);
}


static void _exogenesis_ftime_zone_OnRealised_gtk_widget_realize (GtkWidget* _sender, gpointer self) {
	exogenesis_ftime_zone_OnRealised (self);
}


static void _exogenesis_ftime_zone_OnTimeZoneSelected_exogenesis_tz_widget_time_zone_selected (ExogenesisTZWidget* _sender, const gchar* Zone, struct tm* localtime, gpointer self) {
	exogenesis_ftime_zone_OnTimeZoneSelected (self, Zone, localtime);
}


static void g_time_local (time_t time, struct tm* result) {
	struct tm _result_ = {0};
	struct tm _tmp0_ = {0};
	localtime_r (&time, &_tmp0_);
	_result_ = _tmp0_;
	*result = _result_;
	return;
}


static gchar* g_time_format (struct tm *self, const gchar* format) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* buffer;
	gint buffer_length1;
	gint _buffer_size_;
	gchar* _tmp1_;
	g_return_val_if_fail (format != NULL, NULL);
	_tmp0_ = g_new0 (gchar, 64);
	buffer = _tmp0_;
	buffer_length1 = 64;
	_buffer_size_ = 64;
	strftime (buffer, buffer_length1, format, &(*self));
	_tmp1_ = g_strdup ((const gchar*) buffer);
	result = _tmp1_;
	buffer = (g_free (buffer), NULL);
	return result;
}


static void exogenesis_ftime_zone_real_Build (ExogenesisFTimeZone* self) {
	GtkBuilder* _tmp0_ = NULL;
	GtkBuilder* builder;
	GObject* _tmp1_ = NULL;
	GtkBox* _tmp2_;
	GObject* _tmp3_ = NULL;
	GtkButton* _tmp4_;
	GObject* _tmp5_ = NULL;
	GtkLabel* _tmp6_;
	GObject* _tmp7_ = NULL;
	GtkImage* _tmp8_;
	GObject* _tmp9_ = NULL;
	GtkBox* _tmp10_;
	GObject* _tmp11_ = NULL;
	GtkLabel* _tmp12_;
	GObject* _tmp13_ = NULL;
	GtkButton* _tmp14_;
	GObject* _tmp15_ = NULL;
	GtkButton* _tmp16_;
	GObject* _tmp17_ = NULL;
	GtkBox* _tmp18_;
	ExogenesisTZWidget* _tmp19_ = NULL;
	GTimeVal _tmp20_ = {0};
	GTimeVal _tmp21_ = {0};
	struct tm _tmp22_ = {0};
	struct tm _tmp23_ = {0};
	struct tm t;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_builder_new ();
	builder = _tmp0_;
	gtk_builder_add_from_file (builder, EXOGENESIS_UIPath, &_inner_error_);
	if (_inner_error_ != NULL) {
		_g_object_unref0 (builder);
		goto __catch10_g_error;
	}
	_tmp1_ = gtk_builder_get_object (builder, "boxTimeZone");
	_tmp2_ = _g_object_ref0 (GTK_BOX (_tmp1_));
	_g_object_unref0 (self->priv->boxTimeZone);
	self->priv->boxTimeZone = _tmp2_;
	_tmp3_ = gtk_builder_get_object (builder, "btnPrevious");
	_tmp4_ = _g_object_ref0 (GTK_BUTTON (_tmp3_));
	_g_object_unref0 (self->priv->btnPrevious);
	self->priv->btnPrevious = _tmp4_;
	_tmp5_ = gtk_builder_get_object (builder, "lblTimeZoneTitle");
	_tmp6_ = _g_object_ref0 (GTK_LABEL (_tmp5_));
	_g_object_unref0 (self->priv->lblTimeZoneTitle);
	self->priv->lblTimeZoneTitle = _tmp6_;
	_tmp7_ = gtk_builder_get_object (builder, "imgTimezone");
	_tmp8_ = _g_object_ref0 (GTK_IMAGE (_tmp7_));
	_g_object_unref0 (self->priv->imgTimezone);
	self->priv->imgTimezone = _tmp8_;
	_tmp9_ = gtk_builder_get_object (builder, "boxTZWidget");
	_tmp10_ = _g_object_ref0 (GTK_BOX (_tmp9_));
	_g_object_unref0 (self->priv->boxTZWidget);
	self->priv->boxTZWidget = _tmp10_;
	_tmp11_ = gtk_builder_get_object (builder, "lblCurrentTime");
	_tmp12_ = _g_object_ref0 (GTK_LABEL (_tmp11_));
	_g_object_unref0 (self->priv->lblCurrentTime);
	self->priv->lblCurrentTime = _tmp12_;
	_tmp13_ = gtk_builder_get_object (builder, "btnManual");
	_tmp14_ = _g_object_ref0 (GTK_BUTTON (_tmp13_));
	_g_object_unref0 (self->priv->btnManual);
	self->priv->btnManual = _tmp14_;
	_tmp15_ = gtk_builder_get_object (builder, "btnNext");
	_tmp16_ = _g_object_ref0 (GTK_BUTTON (_tmp15_));
	_g_object_unref0 (self->priv->btnNext);
	self->priv->btnNext = _tmp16_;
	_tmp17_ = gtk_builder_get_object (builder, "boxMain");
	_tmp18_ = _g_object_ref0 (GTK_BOX (_tmp17_));
	_g_object_unref0 (self->priv->boxMain);
	self->priv->boxMain = _tmp18_;
	g_signal_connect_object (self->priv->btnManual, "clicked", (GCallback) _exogenesis_ftime_zone_OnBtnChangeTime_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btnNext, "clicked", (GCallback) _exogenesis_ftime_zone_OnBtnTZNext_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btnPrevious, "clicked", (GCallback) _exogenesis_ftime_zone_OnBtnTZPrevious_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "realize", (GCallback) _exogenesis_ftime_zone_OnRealised_gtk_widget_realize, self, 0);
	_tmp19_ = exogenesis_tz_widget_new ();
	_g_object_unref0 (self->priv->_tzmap);
	self->priv->_tzmap = g_object_ref_sink (_tmp19_);
	g_signal_connect_object (self->priv->_tzmap, "time-zone-selected", (GCallback) _exogenesis_ftime_zone_OnTimeZoneSelected_exogenesis_tz_widget_time_zone_selected, self, 0);
	gtk_box_pack_start (self->priv->boxTZWidget, (GtkWidget*) self->priv->_tzmap, FALSE, FALSE, (guint) 0);
	g_get_current_time (&_tmp20_);
	_tmp21_ = _tmp20_;
	g_time_local ((time_t) _tmp21_.tv_sec, &_tmp22_);
	_tmp23_ = _tmp22_;
	t = _tmp23_;
	_tmp24_ = g_time_format (&t, "%Ec");
	_tmp25_ = _tmp24_;
	gtk_label_set_label (self->priv->lblCurrentTime, _tmp25_);
	_g_free0 (_tmp25_);
	_g_object_unref0 (builder);
	goto __finally10;
	__catch10_g_error:
	{
		GError * err;
		gchar* _tmp26_;
		gchar* _tmp27_;
		GtkMessageDialog* _tmp28_ = NULL;
		GtkMessageDialog* _tmp29_;
		GtkMessageDialog* msg;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp26_ = g_strconcat ("Failed to load UI\n", err->message, NULL);
		_tmp27_ = _tmp26_;
		_tmp28_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_ERROR, GTK_BUTTONS_CANCEL, _tmp27_);
		_tmp29_ = g_object_ref_sink (_tmp28_);
		_g_free0 (_tmp27_);
		msg = _tmp29_;
		gtk_dialog_run ((GtkDialog*) msg);
		gtk_main_quit ();
		_g_object_unref0 (msg);
		_g_error_free0 (err);
	}
	__finally10:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


void exogenesis_ftime_zone_Build (ExogenesisFTimeZone* self) {
	EXOGENESIS_FTIME_ZONE_GET_CLASS (self)->Build (self);
}


static gboolean _exogenesis_ftime_zone_OnTimer_gsource_func (gpointer self) {
	gboolean result;
	result = exogenesis_ftime_zone_OnTimer (self);
	return result;
}


ExogenesisFTimeZone* exogenesis_ftime_zone_construct (GType object_type) {
	ExogenesisFTimeZone * self = NULL;
	guint _tmp0_;
	self = (ExogenesisFTimeZone*) g_object_new (object_type, NULL);
	exogenesis_ftime_zone_Build (self);
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) self->priv->boxTimeZone, FALSE, FALSE, (guint) 0);
	g_object_set ((GtkWidget*) self, "width-request", 700, NULL);
	g_object_set ((GtkWidget*) self, "height-request", 450, NULL);
	_tmp0_ = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 1000, _exogenesis_ftime_zone_OnTimer_gsource_func, g_object_ref (self), g_object_unref);
	self->priv->timerID = _tmp0_;
	gtk_widget_show_all ((GtkWidget*) self);
	return self;
}


ExogenesisFTimeZone* exogenesis_ftime_zone_new (void) {
	return exogenesis_ftime_zone_construct (EXOGENESIS_TYPE_FTIME_ZONE);
}


gboolean exogenesis_ftime_zone_OnTimer (ExogenesisFTimeZone* self) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	exogenesis_ftime_zone_DisplayTime (self);
	result = TRUE;
	return result;
}


static void exogenesis_ftime_zone_DisplayTime (ExogenesisFTimeZone* self) {
	GTimeVal _tmp0_ = {0};
	GTimeVal _tmp1_ = {0};
	struct tm _tmp2_ = {0};
	struct tm _tmp3_ = {0};
	struct tm t;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_;
	g_return_if_fail (self != NULL);
	g_get_current_time (&_tmp0_);
	_tmp1_ = _tmp0_;
	g_time_local ((time_t) _tmp1_.tv_sec, &_tmp2_);
	_tmp3_ = _tmp2_;
	t = _tmp3_;
	_tmp4_ = g_time_format (&t, "%Ec");
	_tmp5_ = _tmp4_;
	gtk_label_set_label (self->priv->lblCurrentTime, _tmp5_);
	_g_free0 (_tmp5_);
}


void exogenesis_ftime_zone_OnTimeZoneSelected (ExogenesisFTimeZone* self, const gchar* Zone, struct tm* localtime) {
	gchar* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (Zone != NULL);
	_tmp0_ = g_strdup (Zone);
	_g_free0 (self->priv->_SelectedTimeZone);
	self->priv->_SelectedTimeZone = _tmp0_;
	self->priv->_SelectedTime = *localtime;
	_tmp1_ = g_time_format (localtime, "%Ec");
	_tmp2_ = _tmp1_;
	gtk_label_set_label (self->priv->lblCurrentTime, _tmp2_);
	_g_free0 (_tmp2_);
}


void exogenesis_ftime_zone_OnBtnChangeTime_Click (ExogenesisFTimeZone* self) {
	ExogenesisFTimeAdjustMan* _tmp0_ = NULL;
	ExogenesisFTimeAdjustMan* fta;
	g_return_if_fail (self != NULL);
	_tmp0_ = exogenesis_ftime_adjust_man_new ();
	fta = g_object_ref_sink (_tmp0_);
	_g_object_unref0 (fta);
}


void exogenesis_ftime_zone_OnBtnTZNext_Click (ExogenesisFTimeZone* self) {
	GtkWidget* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	exogenesis_install_data_set_TimeZone (exogenesis_gInstallData, self->priv->_SelectedTimeZone);
	_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) self);
	exogenesis_main_win_ShowNextWindow (EXOGENESIS_MAIN_WIN (_tmp0_));
}


void exogenesis_ftime_zone_OnBtnTZPrevious_Click (ExogenesisFTimeZone* self) {
	GtkWidget* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) self);
	exogenesis_main_win_ShowPreviousWindow (EXOGENESIS_MAIN_WIN (_tmp0_));
}


static void exogenesis_ftime_zone_ShowAllocs (ExogenesisFTimeZone* self, GtkContainer* x) {
	GtkAllocation alloc = {0};
	GtkAllocation _tmp0_ = {0};
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_;
	const gchar* _tmp10_ = NULL;
	gint _tmp11_;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_;
	gint _tmp14_;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (x != NULL);
	gtk_widget_get_allocation ((GtkWidget*) x, &_tmp0_);
	alloc = _tmp0_;
	_tmp1_ = gtk_buildable_get_name ((GtkBuildable*) x);
	_tmp2_ = g_strdup_printf ("%i", alloc.x);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strdup_printf ("%i", alloc.y);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strdup_printf ("%i", alloc.width);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strdup_printf ("%i", alloc.height);
	_tmp9_ = _tmp8_;
	fprintf (stdout, "%s ALLOC x=%s y=%s w=%s h=%s\n", _tmp1_, _tmp3_, _tmp5_, _tmp7_, _tmp9_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	_tmp10_ = gtk_buildable_get_name ((GtkBuildable*) x);
	g_object_get ((GtkWidget*) x, "height-request", &_tmp11_, NULL);
	_tmp12_ = g_strdup_printf ("%i", _tmp11_);
	_tmp13_ = _tmp12_;
	g_object_get ((GtkWidget*) x, "width-request", &_tmp14_, NULL);
	_tmp15_ = g_strdup_printf ("%i", _tmp14_);
	_tmp16_ = _tmp15_;
	fprintf (stdout, "%s SIZE h=%s w=%s\n", _tmp10_, _tmp13_, _tmp16_);
	_g_free0 (_tmp16_);
	_g_free0 (_tmp13_);
}


void exogenesis_ftime_zone_OnRealised (ExogenesisFTimeZone* self) {
	GtkAllocation alloc = {0};
	GtkWidget* _tmp0_ = NULL;
	GtkAllocation _tmp1_ = {0};
	GtkWidget* _tmp2_ = NULL;
	GtkAllocation _tmp3_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) self);
	gtk_widget_get_allocation (_tmp0_, &_tmp1_);
	alloc = _tmp1_;
	gtk_widget_set_allocation ((GtkWidget*) self->priv->boxTimeZone, &alloc);
	_tmp2_ = gtk_widget_get_toplevel ((GtkWidget*) self);
	gtk_container_resize_children ((GtkContainer*) GTK_WINDOW (_tmp2_));
	gtk_widget_get_allocation ((GtkWidget*) self->priv->boxTZWidget, &_tmp3_);
	alloc = _tmp3_;
	gtk_widget_set_allocation ((GtkWidget*) self->priv->_tzmap, &alloc);
	g_object_set ((GtkWidget*) self->priv->_tzmap, "width-request", alloc.width, NULL);
	g_object_set ((GtkWidget*) self->priv->_tzmap, "height-request", alloc.height, NULL);
	gtk_widget_show_all ((GtkWidget*) self->priv->boxTimeZone);
	gtk_widget_show_all ((GtkWidget*) self->priv->boxTZWidget);
}


static void exogenesis_ftime_zone_class_init (ExogenesisFTimeZoneClass * klass) {
	exogenesis_ftime_zone_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ExogenesisFTimeZonePrivate));
	EXOGENESIS_FTIME_ZONE_CLASS (klass)->Build = exogenesis_ftime_zone_real_Build;
	G_OBJECT_CLASS (klass)->finalize = exogenesis_ftime_zone_finalize;
}


static void exogenesis_ftime_zone_instance_init (ExogenesisFTimeZone * self) {
	self->priv = EXOGENESIS_FTIME_ZONE_GET_PRIVATE (self);
}


static void exogenesis_ftime_zone_finalize (GObject* obj) {
	ExogenesisFTimeZone * self;
	self = EXOGENESIS_FTIME_ZONE (obj);
	_g_object_unref0 (self->priv->boxTimeZone);
	_g_object_unref0 (self->priv->btnPrevious);
	_g_object_unref0 (self->priv->lblTimeZoneTitle);
	_g_object_unref0 (self->priv->imgTimezone);
	_g_object_unref0 (self->priv->boxTZWidget);
	_g_object_unref0 (self->priv->lblCurrentTime);
	_g_object_unref0 (self->priv->btnManual);
	_g_object_unref0 (self->priv->btnNext);
	_g_object_unref0 (self->priv->boxMain);
	_g_object_unref0 (self->priv->_tzmap);
	_g_free0 (self->priv->_SelectedTimeZone);
	G_OBJECT_CLASS (exogenesis_ftime_zone_parent_class)->finalize (obj);
}


GType exogenesis_ftime_zone_get_type (void) {
	static volatile gsize exogenesis_ftime_zone_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_ftime_zone_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisFTimeZoneClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_ftime_zone_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisFTimeZone), 0, (GInstanceInitFunc) exogenesis_ftime_zone_instance_init, NULL };
		GType exogenesis_ftime_zone_type_id;
		exogenesis_ftime_zone_type_id = g_type_register_static (GTK_TYPE_BOX, "ExogenesisFTimeZone", &g_define_type_info, 0);
		g_once_init_leave (&exogenesis_ftime_zone_type_id__volatile, exogenesis_ftime_zone_type_id);
	}
	return exogenesis_ftime_zone_type_id__volatile;
}



