/* exoFWelcome.c generated by valac 0.12.1, the Vala compiler
 * generated from exoFWelcome.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>


#define EXOGENESIS_TYPE_FWELCOME (exogenesis_fwelcome_get_type ())
#define EXOGENESIS_FWELCOME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_FWELCOME, ExogenesisFWelcome))
#define EXOGENESIS_FWELCOME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_FWELCOME, ExogenesisFWelcomeClass))
#define EXOGENESIS_IS_FWELCOME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_FWELCOME))
#define EXOGENESIS_IS_FWELCOME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_FWELCOME))
#define EXOGENESIS_FWELCOME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_FWELCOME, ExogenesisFWelcomeClass))

typedef struct _ExogenesisFWelcome ExogenesisFWelcome;
typedef struct _ExogenesisFWelcomeClass ExogenesisFWelcomeClass;
typedef struct _ExogenesisFWelcomePrivate ExogenesisFWelcomePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define EXOGENESIS_TYPE_GENERAL_FUNCTIONS (exogenesis_general_functions_get_type ())
#define EXOGENESIS_GENERAL_FUNCTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_GENERAL_FUNCTIONS, ExogenesisGeneralFunctions))
#define EXOGENESIS_GENERAL_FUNCTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_GENERAL_FUNCTIONS, ExogenesisGeneralFunctionsClass))
#define EXOGENESIS_IS_GENERAL_FUNCTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_GENERAL_FUNCTIONS))
#define EXOGENESIS_IS_GENERAL_FUNCTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_GENERAL_FUNCTIONS))
#define EXOGENESIS_GENERAL_FUNCTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_GENERAL_FUNCTIONS, ExogenesisGeneralFunctionsClass))

typedef struct _ExogenesisGeneralFunctions ExogenesisGeneralFunctions;
typedef struct _ExogenesisGeneralFunctionsClass ExogenesisGeneralFunctionsClass;

#define EXOGENESIS_TYPE_LANGUAGE_MANAGER (exogenesis_language_manager_get_type ())
#define EXOGENESIS_LANGUAGE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_LANGUAGE_MANAGER, ExogenesisLanguageManager))
#define EXOGENESIS_LANGUAGE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_LANGUAGE_MANAGER, ExogenesisLanguageManagerClass))
#define EXOGENESIS_IS_LANGUAGE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_LANGUAGE_MANAGER))
#define EXOGENESIS_IS_LANGUAGE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_LANGUAGE_MANAGER))
#define EXOGENESIS_LANGUAGE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_LANGUAGE_MANAGER, ExogenesisLanguageManagerClass))

typedef struct _ExogenesisLanguageManager ExogenesisLanguageManager;
typedef struct _ExogenesisLanguageManagerClass ExogenesisLanguageManagerClass;

#define EXOGENESIS_TYPE_LANGUAGE (exogenesis_language_get_type ())
#define EXOGENESIS_LANGUAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_LANGUAGE, ExogenesisLanguage))
#define EXOGENESIS_LANGUAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_LANGUAGE, ExogenesisLanguageClass))
#define EXOGENESIS_IS_LANGUAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_LANGUAGE))
#define EXOGENESIS_IS_LANGUAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_LANGUAGE))
#define EXOGENESIS_LANGUAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_LANGUAGE, ExogenesisLanguageClass))

typedef struct _ExogenesisLanguage ExogenesisLanguage;
typedef struct _ExogenesisLanguageClass ExogenesisLanguageClass;
#define _exogenesis_language_unref0(var) ((var == NULL) ? NULL : (var = (exogenesis_language_unref (var), NULL)))
#define __g_list_free__exogenesis_language_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__exogenesis_language_unref0_ (var), NULL)))

#define EXOGENESIS_TYPE_MAIN_WIN (exogenesis_main_win_get_type ())
#define EXOGENESIS_MAIN_WIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWin))
#define EXOGENESIS_MAIN_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWinClass))
#define EXOGENESIS_IS_MAIN_WIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_MAIN_WIN))
#define EXOGENESIS_IS_MAIN_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_MAIN_WIN))
#define EXOGENESIS_MAIN_WIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWinClass))

typedef struct _ExogenesisMainWin ExogenesisMainWin;
typedef struct _ExogenesisMainWinClass ExogenesisMainWinClass;

struct _ExogenesisFWelcome {
	GtkBox parent_instance;
	ExogenesisFWelcomePrivate * priv;
};

struct _ExogenesisFWelcomeClass {
	GtkBoxClass parent_class;
};

struct _ExogenesisFWelcomePrivate {
	GtkBox* boxWelcome;
	GtkTreeView* tvwLanguages;
	GtkLayout* lytImage;
	GtkImage* imgNext;
	GtkBox* boxInfo;
	GtkImage* imgWelcome;
	GtkLabel* lblWelcomeInfo;
	GtkButton* btnInstall;
	GtkButton* btnLive;
	GtkListStore* _lstLanguages;
	gchar* _fName;
	GtkCssProvider* _provider;
	GdkDisplay* _display;
	GdkScreen* _screen;
};


static gpointer exogenesis_fwelcome_parent_class = NULL;
extern gchar* exogenesis_AppPath;
extern ExogenesisGeneralFunctions* exogenesis_gGenFunc;
extern ExogenesisLanguageManager* exogenesis_gLanguageManager;

GType exogenesis_fwelcome_get_type (void) G_GNUC_CONST;
#define EXOGENESIS_FWELCOME_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXOGENESIS_TYPE_FWELCOME, ExogenesisFWelcomePrivate))
enum  {
	EXOGENESIS_FWELCOME_DUMMY_PROPERTY
};
static void exogenesis_fwelcome_Build (ExogenesisFWelcome* self);
void exogenesis_fwelcome_OnBtnInstall_Click (ExogenesisFWelcome* self, GtkButton* source);
static void _exogenesis_fwelcome_OnBtnInstall_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
static void exogenesis_fwelcome_SetLabels (ExogenesisFWelcome* self);
gpointer exogenesis_general_functions_ref (gpointer instance);
void exogenesis_general_functions_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_general_functions (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_general_functions (GValue* value, gpointer v_object);
void exogenesis_value_take_general_functions (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_general_functions (const GValue* value);
GType exogenesis_general_functions_get_type (void) G_GNUC_CONST;
gchar* exogenesis_general_functions_GetLabelText (ExogenesisGeneralFunctions* self, const gchar* formname, const gchar* controlname);
ExogenesisFWelcome* exogenesis_fwelcome_new (void);
ExogenesisFWelcome* exogenesis_fwelcome_construct (GType object_type);
static void exogenesis_fwelcome_GetLanguages (ExogenesisFWelcome* self);
gchar* exogenesis_fwelcome_GetSelectedLanguage (ExogenesisFWelcome* self);
gpointer exogenesis_language_manager_ref (gpointer instance);
void exogenesis_language_manager_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_language_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_language_manager (GValue* value, gpointer v_object);
void exogenesis_value_take_language_manager (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_language_manager (const GValue* value);
GType exogenesis_language_manager_get_type (void) G_GNUC_CONST;
gpointer exogenesis_language_ref (gpointer instance);
void exogenesis_language_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_language (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_language (GValue* value, gpointer v_object);
void exogenesis_value_take_language (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_language (const GValue* value);
GType exogenesis_language_get_type (void) G_GNUC_CONST;
GList* exogenesis_language_manager_AvailableLanguages (ExogenesisLanguageManager* self);
const gchar* exogenesis_language_get_Country (ExogenesisLanguage* self);
const gchar* exogenesis_language_get_CountryNative (ExogenesisLanguage* self);
const gchar* exogenesis_language_get_Code (ExogenesisLanguage* self);
static void _exogenesis_language_unref0_ (gpointer var);
static void _g_list_free__exogenesis_language_unref0_ (GList* self);
GType exogenesis_main_win_get_type (void) G_GNUC_CONST;
void exogenesis_main_win_ShowNextWindow (ExogenesisMainWin* self);
static void exogenesis_fwelcome_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _exogenesis_fwelcome_OnBtnInstall_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fwelcome_OnBtnInstall_Click (self, _sender);
}


static void exogenesis_fwelcome_Build (ExogenesisFWelcome* self) {
	GtkBuilder* _tmp0_ = NULL;
	GtkBuilder* builder;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	GObject* _tmp3_ = NULL;
	GtkBox* _tmp4_;
	GObject* _tmp5_ = NULL;
	GtkTreeView* _tmp6_;
	GObject* _tmp7_ = NULL;
	GtkLayout* _tmp8_;
	GObject* _tmp9_ = NULL;
	GtkImage* _tmp10_;
	GObject* _tmp11_ = NULL;
	GtkBox* _tmp12_;
	GObject* _tmp13_ = NULL;
	GtkImage* _tmp14_;
	GObject* _tmp15_ = NULL;
	GtkLabel* _tmp16_;
	GObject* _tmp17_ = NULL;
	GtkButton* _tmp18_;
	GObject* _tmp19_ = NULL;
	GtkButton* _tmp20_;
	GtkCellRendererText* _tmp21_ = NULL;
	GtkCellRendererText* _tmp22_;
	GdkScreen* _tmp23_ = NULL;
	GdkScreen* _tmp24_;
	GtkStyleContext* _tmp25_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_builder_new ();
	builder = _tmp0_;
	_tmp1_ = g_strdup_printf ("%s/src/exogenesis.ui", exogenesis_AppPath);
	_tmp2_ = _tmp1_;
	gtk_builder_add_from_file (builder, _tmp2_, &_inner_error_);
	_g_free0 (_tmp2_);
	if (_inner_error_ != NULL) {
		_g_object_unref0 (builder);
		goto __catch12_g_error;
	}
	_tmp3_ = gtk_builder_get_object (builder, "boxWelcome");
	_tmp4_ = _g_object_ref0 (GTK_BOX (_tmp3_));
	_g_object_unref0 (self->priv->boxWelcome);
	self->priv->boxWelcome = _tmp4_;
	_tmp5_ = gtk_builder_get_object (builder, "tvwLanguages");
	_tmp6_ = _g_object_ref0 (GTK_TREE_VIEW (_tmp5_));
	_g_object_unref0 (self->priv->tvwLanguages);
	self->priv->tvwLanguages = _tmp6_;
	_tmp7_ = gtk_builder_get_object (builder, "lytImage");
	_tmp8_ = _g_object_ref0 (GTK_LAYOUT (_tmp7_));
	_g_object_unref0 (self->priv->lytImage);
	self->priv->lytImage = _tmp8_;
	_tmp9_ = gtk_builder_get_object (builder, "imgNext");
	_tmp10_ = _g_object_ref0 (GTK_IMAGE (_tmp9_));
	_g_object_unref0 (self->priv->imgNext);
	self->priv->imgNext = _tmp10_;
	_tmp11_ = gtk_builder_get_object (builder, "boxInfo");
	_tmp12_ = _g_object_ref0 (GTK_BOX (_tmp11_));
	_g_object_unref0 (self->priv->boxInfo);
	self->priv->boxInfo = _tmp12_;
	_tmp13_ = gtk_builder_get_object (builder, "imgWelcome");
	_tmp14_ = _g_object_ref0 (GTK_IMAGE (_tmp13_));
	_g_object_unref0 (self->priv->imgWelcome);
	self->priv->imgWelcome = _tmp14_;
	_tmp15_ = gtk_builder_get_object (builder, "lblWelcomeInfo");
	_tmp16_ = _g_object_ref0 (GTK_LABEL (_tmp15_));
	_g_object_unref0 (self->priv->lblWelcomeInfo);
	self->priv->lblWelcomeInfo = _tmp16_;
	_tmp17_ = gtk_builder_get_object (builder, "btnInstall");
	_tmp18_ = _g_object_ref0 (GTK_BUTTON (_tmp17_));
	_g_object_unref0 (self->priv->btnInstall);
	self->priv->btnInstall = _tmp18_;
	_tmp19_ = gtk_builder_get_object (builder, "btnLive");
	_tmp20_ = _g_object_ref0 (GTK_BUTTON (_tmp19_));
	_g_object_unref0 (self->priv->btnLive);
	self->priv->btnLive = _tmp20_;
	g_signal_connect_object (self->priv->btnInstall, "clicked", (GCallback) _exogenesis_fwelcome_OnBtnInstall_Click_gtk_button_clicked, self, 0);
	gtk_tree_view_set_model (self->priv->tvwLanguages, (GtkTreeModel*) self->priv->_lstLanguages);
	_tmp21_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	_tmp22_ = g_object_ref_sink (_tmp21_);
	gtk_tree_view_insert_column_with_attributes (self->priv->tvwLanguages, -1, "Language", (GtkCellRenderer*) _tmp22_, "text", NULL, NULL);
	_g_object_unref0 (_tmp22_);
	_tmp23_ = gdk_display_get_default_screen (self->priv->_display);
	_tmp24_ = _g_object_ref0 (_tmp23_);
	_g_object_unref0 (self->priv->_screen);
	self->priv->_screen = _tmp24_;
	_tmp25_ = gtk_widget_get_style_context ((GtkWidget*) self);
	gtk_style_context_add_provider_for_screen (self->priv->_screen, (GtkStyleProvider*) self->priv->_provider, (guint) 1);
	gtk_css_provider_load_from_data (self->priv->_provider, " GtkWindow {\n" \
" background-image: url('images/default_bkground.png');\n" \
" }\n", (gssize) (-1), &_inner_error_);
	if (_inner_error_ != NULL) {
		_g_object_unref0 (builder);
		goto __catch12_g_error;
	}
	_g_object_unref0 (builder);
	goto __finally12;
	__catch12_g_error:
	{
		GError * err;
		gchar* _tmp26_;
		gchar* _tmp27_;
		GtkMessageDialog* _tmp28_ = NULL;
		GtkMessageDialog* _tmp29_;
		GtkMessageDialog* msg;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp26_ = g_strconcat ("Failed to load UI\n", err->message, NULL);
		_tmp27_ = _tmp26_;
		_tmp28_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_ERROR, GTK_BUTTONS_CANCEL, _tmp27_);
		_tmp29_ = g_object_ref_sink (_tmp28_);
		_g_free0 (_tmp27_);
		msg = _tmp29_;
		gtk_dialog_run ((GtkDialog*) msg);
		gtk_main_quit ();
		_g_object_unref0 (msg);
		_g_error_free0 (err);
	}
	__finally12:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void exogenesis_fwelcome_SetLabels (ExogenesisFWelcome* self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = exogenesis_general_functions_GetLabelText (exogenesis_gGenFunc, self->priv->_fName, "lblWelcomeInfo");
	_tmp1_ = _tmp0_;
	gtk_label_set_label (self->priv->lblWelcomeInfo, _tmp1_);
	_g_free0 (_tmp1_);
}


ExogenesisFWelcome* exogenesis_fwelcome_construct (GType object_type) {
	ExogenesisFWelcome * self = NULL;
	GtkAllocation alloc = {0};
	GtkAllocation _tmp0_ = {0};
	self = (ExogenesisFWelcome*) g_object_new (object_type, NULL);
	exogenesis_fwelcome_Build (self);
	exogenesis_fwelcome_GetLanguages (self);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) self->priv->boxWelcome);
	g_object_set ((GtkWidget*) self, "width-request", 700, NULL);
	g_object_set ((GtkWidget*) self, "height-request", 450, NULL);
	gtk_widget_get_allocation ((GtkWidget*) self, &_tmp0_);
	alloc = _tmp0_;
	gtk_widget_set_allocation ((GtkWidget*) self->priv->boxWelcome, &alloc);
	gtk_widget_show_all ((GtkWidget*) self);
	return self;
}


ExogenesisFWelcome* exogenesis_fwelcome_new (void) {
	return exogenesis_fwelcome_construct (EXOGENESIS_TYPE_FWELCOME);
}


gchar* exogenesis_fwelcome_GetSelectedLanguage (ExogenesisFWelcome* self) {
	gchar* result = NULL;
	GtkTreeSelection* ts = NULL;
	GtkTreeIter iter = {0};
	GtkTreeModel* tm = NULL;
	gchar* val = NULL;
	GtkTreeSelection* _tmp0_ = NULL;
	GtkTreeSelection* _tmp1_;
	GtkTreeModel* _tmp2_ = NULL;
	GtkTreeIter _tmp3_ = {0};
	GtkTreeModel* _tmp4_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gtk_tree_view_get_selection (self->priv->tvwLanguages);
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (ts);
	ts = _tmp1_;
	gtk_tree_selection_get_selected (ts, &_tmp2_, &_tmp3_);
	_g_object_unref0 (tm);
	_tmp4_ = _g_object_ref0 (_tmp2_);
	tm = _tmp4_;
	iter = _tmp3_;
	gtk_tree_model_get (tm, &iter, 1, &val, -1);
	result = val;
	_g_object_unref0 (tm);
	_g_object_unref0 (ts);
	return result;
}


static gpointer _exogenesis_language_ref0 (gpointer self) {
	return self ? exogenesis_language_ref (self) : NULL;
}


static void _exogenesis_language_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (exogenesis_language_unref (var), NULL));
}


static void _g_list_free__exogenesis_language_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _exogenesis_language_unref0_, NULL);
	g_list_free (self);
}


static void exogenesis_fwelcome_GetLanguages (ExogenesisFWelcome* self) {
	GList* _tmp0_ = NULL;
	GList* languages;
	GtkTreeIter iter = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = exogenesis_language_manager_AvailableLanguages (exogenesis_gLanguageManager);
	languages = _tmp0_;
	{
		GList* lang_collection;
		GList* lang_it;
		lang_collection = languages;
		for (lang_it = lang_collection; lang_it != NULL; lang_it = lang_it->next) {
			ExogenesisLanguage* _tmp1_;
			ExogenesisLanguage* lang;
			_tmp1_ = _exogenesis_language_ref0 ((ExogenesisLanguage*) lang_it->data);
			lang = _tmp1_;
			{
				const gchar* _tmp2_ = NULL;
				const gchar* _tmp3_ = NULL;
				gchar* _tmp4_ = NULL;
				gchar* displaytxt;
				GtkTreeIter _tmp5_ = {0};
				const gchar* _tmp6_ = NULL;
				_tmp2_ = exogenesis_language_get_Country (lang);
				_tmp3_ = exogenesis_language_get_CountryNative (lang);
				_tmp4_ = g_strdup_printf ("%s %s", _tmp2_, _tmp3_);
				displaytxt = _tmp4_;
				gtk_list_store_append (self->priv->_lstLanguages, &_tmp5_);
				iter = _tmp5_;
				_tmp6_ = exogenesis_language_get_Code (lang);
				gtk_list_store_set (self->priv->_lstLanguages, &iter, 0, displaytxt, 1, _tmp6_, -1, -1);
				_g_free0 (displaytxt);
				_exogenesis_language_unref0 (lang);
			}
		}
	}
	__g_list_free__exogenesis_language_unref0_0 (languages);
}


void exogenesis_fwelcome_OnBtnInstall_Click (ExogenesisFWelcome* self, GtkButton* source) {
	GtkWidget* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (source != NULL);
	_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) self);
	exogenesis_main_win_ShowNextWindow (EXOGENESIS_MAIN_WIN (_tmp0_));
}


static void exogenesis_fwelcome_class_init (ExogenesisFWelcomeClass * klass) {
	exogenesis_fwelcome_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ExogenesisFWelcomePrivate));
	G_OBJECT_CLASS (klass)->finalize = exogenesis_fwelcome_finalize;
}


static void exogenesis_fwelcome_instance_init (ExogenesisFWelcome * self) {
	GtkListStore* _tmp0_ = NULL;
	gchar* _tmp1_;
	GtkCssProvider* _tmp2_ = NULL;
	GdkDisplay* _tmp3_ = NULL;
	GdkDisplay* _tmp4_;
	self->priv = EXOGENESIS_FWELCOME_GET_PRIVATE (self);
	_tmp0_ = gtk_list_store_new (2, G_TYPE_STRING, G_TYPE_STRING);
	self->priv->_lstLanguages = _tmp0_;
	_tmp1_ = g_strdup ("welcome");
	self->priv->_fName = _tmp1_;
	_tmp2_ = gtk_css_provider_new ();
	self->priv->_provider = _tmp2_;
	_tmp3_ = gdk_display_get_default ();
	_tmp4_ = _g_object_ref0 (_tmp3_);
	self->priv->_display = _tmp4_;
}


static void exogenesis_fwelcome_finalize (GObject* obj) {
	ExogenesisFWelcome * self;
	self = EXOGENESIS_FWELCOME (obj);
	_g_object_unref0 (self->priv->boxWelcome);
	_g_object_unref0 (self->priv->tvwLanguages);
	_g_object_unref0 (self->priv->lytImage);
	_g_object_unref0 (self->priv->imgNext);
	_g_object_unref0 (self->priv->boxInfo);
	_g_object_unref0 (self->priv->imgWelcome);
	_g_object_unref0 (self->priv->lblWelcomeInfo);
	_g_object_unref0 (self->priv->btnInstall);
	_g_object_unref0 (self->priv->btnLive);
	_g_object_unref0 (self->priv->_lstLanguages);
	_g_free0 (self->priv->_fName);
	_g_object_unref0 (self->priv->_provider);
	_g_object_unref0 (self->priv->_display);
	_g_object_unref0 (self->priv->_screen);
	G_OBJECT_CLASS (exogenesis_fwelcome_parent_class)->finalize (obj);
}


GType exogenesis_fwelcome_get_type (void) {
	static volatile gsize exogenesis_fwelcome_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_fwelcome_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisFWelcomeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_fwelcome_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisFWelcome), 0, (GInstanceInitFunc) exogenesis_fwelcome_instance_init, NULL };
		GType exogenesis_fwelcome_type_id;
		exogenesis_fwelcome_type_id = g_type_register_static (GTK_TYPE_BOX, "ExogenesisFWelcome", &g_define_type_info, 0);
		g_once_init_leave (&exogenesis_fwelcome_type_id__volatile, exogenesis_fwelcome_type_id);
	}
	return exogenesis_fwelcome_type_id__volatile;
}



