/* exoFConfirm.c generated by valac 0.12.1, the Vala compiler
 * generated from exoFConfirm.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define EXOGENESIS_TYPE_FCONFIRM (exogenesis_fconfirm_get_type ())
#define EXOGENESIS_FCONFIRM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_FCONFIRM, ExogenesisFConfirm))
#define EXOGENESIS_FCONFIRM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_FCONFIRM, ExogenesisFConfirmClass))
#define EXOGENESIS_IS_FCONFIRM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_FCONFIRM))
#define EXOGENESIS_IS_FCONFIRM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_FCONFIRM))
#define EXOGENESIS_FCONFIRM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_FCONFIRM, ExogenesisFConfirmClass))

typedef struct _ExogenesisFConfirm ExogenesisFConfirm;
typedef struct _ExogenesisFConfirmClass ExogenesisFConfirmClass;
typedef struct _ExogenesisFConfirmPrivate ExogenesisFConfirmPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define EXOGENESIS_TYPE_INSTALL_DATA (exogenesis_install_data_get_type ())
#define EXOGENESIS_INSTALL_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallData))
#define EXOGENESIS_INSTALL_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallDataClass))
#define EXOGENESIS_IS_INSTALL_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_INSTALL_DATA))
#define EXOGENESIS_IS_INSTALL_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_INSTALL_DATA))
#define EXOGENESIS_INSTALL_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallDataClass))

typedef struct _ExogenesisInstallData ExogenesisInstallData;
typedef struct _ExogenesisInstallDataClass ExogenesisInstallDataClass;

#define EXOGENESIS_TYPE_INSTALL_HARD_DISK (exogenesis_install_hard_disk_get_type ())
#define EXOGENESIS_INSTALL_HARD_DISK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_INSTALL_HARD_DISK, ExogenesisInstallHardDisk))
#define EXOGENESIS_INSTALL_HARD_DISK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_INSTALL_HARD_DISK, ExogenesisInstallHardDiskClass))
#define EXOGENESIS_IS_INSTALL_HARD_DISK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_INSTALL_HARD_DISK))
#define EXOGENESIS_IS_INSTALL_HARD_DISK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_INSTALL_HARD_DISK))
#define EXOGENESIS_INSTALL_HARD_DISK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_INSTALL_HARD_DISK, ExogenesisInstallHardDiskClass))

typedef struct _ExogenesisInstallHardDisk ExogenesisInstallHardDisk;
typedef struct _ExogenesisInstallHardDiskClass ExogenesisInstallHardDiskClass;

#define EXOGENESIS_TYPE_USER_DETAIL (exogenesis_user_detail_get_type ())
#define EXOGENESIS_USER_DETAIL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_USER_DETAIL, ExogenesisUserDetail))
#define EXOGENESIS_USER_DETAIL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_USER_DETAIL, ExogenesisUserDetailClass))
#define EXOGENESIS_IS_USER_DETAIL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_USER_DETAIL))
#define EXOGENESIS_IS_USER_DETAIL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_USER_DETAIL))
#define EXOGENESIS_USER_DETAIL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_USER_DETAIL, ExogenesisUserDetailClass))

typedef struct _ExogenesisUserDetail ExogenesisUserDetail;
typedef struct _ExogenesisUserDetailClass ExogenesisUserDetailClass;

#define EXOGENESIS_TYPE_INSTALL_PARTITION (exogenesis_install_partition_get_type ())
#define EXOGENESIS_INSTALL_PARTITION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_INSTALL_PARTITION, ExogenesisInstallPartition))
#define EXOGENESIS_INSTALL_PARTITION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_INSTALL_PARTITION, ExogenesisInstallPartitionClass))
#define EXOGENESIS_IS_INSTALL_PARTITION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_INSTALL_PARTITION))
#define EXOGENESIS_IS_INSTALL_PARTITION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_INSTALL_PARTITION))
#define EXOGENESIS_INSTALL_PARTITION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_INSTALL_PARTITION, ExogenesisInstallPartitionClass))

typedef struct _ExogenesisInstallPartition ExogenesisInstallPartition;
typedef struct _ExogenesisInstallPartitionClass ExogenesisInstallPartitionClass;
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))

#define EXOGENESIS_TYPE_MAIN_WIN (exogenesis_main_win_get_type ())
#define EXOGENESIS_MAIN_WIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWin))
#define EXOGENESIS_MAIN_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWinClass))
#define EXOGENESIS_IS_MAIN_WIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_MAIN_WIN))
#define EXOGENESIS_IS_MAIN_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_MAIN_WIN))
#define EXOGENESIS_MAIN_WIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWinClass))

typedef struct _ExogenesisMainWin ExogenesisMainWin;
typedef struct _ExogenesisMainWinClass ExogenesisMainWinClass;

struct _ExogenesisFConfirm {
	GtkLayout parent_instance;
	ExogenesisFConfirmPrivate * priv;
};

struct _ExogenesisFConfirmClass {
	GtkLayoutClass parent_class;
};

struct _ExogenesisFConfirmPrivate {
	GtkFixed* fxdLayout;
	GtkButton* btnCancel;
	GtkButton* btnPrevious;
	GtkButton* btnInstall;
	GtkComboBox* cboHDBootTarget;
	GtkLabel* lblConfirmText;
	GtkScrolledWindow* scrConfirm;
	gchar* _Title;
	gchar* _UserDetail;
	gchar* _KeyboardSetting;
	gchar* _KeyboardVariant;
	gchar* _TimeZone;
	gchar* _HDTarget;
	GtkListStore* _lstGrubTarget;
};


static gpointer exogenesis_fconfirm_parent_class = NULL;
extern ExogenesisInstallData* exogenesis_gInstallData;

GType exogenesis_fconfirm_get_type (void) G_GNUC_CONST;
#define EXOGENESIS_FCONFIRM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXOGENESIS_TYPE_FCONFIRM, ExogenesisFConfirmPrivate))
enum  {
	EXOGENESIS_FCONFIRM_DUMMY_PROPERTY
};
ExogenesisFConfirm* exogenesis_fconfirm_new (void);
ExogenesisFConfirm* exogenesis_fconfirm_construct (GType object_type);
static void exogenesis_fconfirm_build (ExogenesisFConfirm* self);
#define EXOGENESIS_UIPath "/home/steve/1-work/anjuta/exogenesis/src/exogenesis.ui"
void exogenesis_fconfirm_OnBtnCancel_Click (ExogenesisFConfirm* self);
static void _exogenesis_fconfirm_OnBtnCancel_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_fconfirm_OnBtnPrevious_Click (ExogenesisFConfirm* self);
static void _exogenesis_fconfirm_OnBtnPrevious_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_fconfirm_OnBtnInstall_Click (ExogenesisFConfirm* self);
static void _exogenesis_fconfirm_OnBtnInstall_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_fconfirm_OnCboHDBootTarget_Changed (ExogenesisFConfirm* self);
static void _exogenesis_fconfirm_OnCboHDBootTarget_Changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self);
void exogenesis_fconfirm_OnRealize (ExogenesisFConfirm* self);
static void _exogenesis_fconfirm_OnRealize_gtk_widget_realize (GtkWidget* _sender, gpointer self);
static void exogenesis_fconfirm_PopulateGrubTarget (ExogenesisFConfirm* self);
GType exogenesis_install_data_get_type (void) G_GNUC_CONST;
GType exogenesis_install_hard_disk_get_type (void) G_GNUC_CONST;
void exogenesis_general_functions_LogIt (const gchar* Message);
const gchar* exogenesis_install_hard_disk_get_DeviceName (ExogenesisInstallHardDisk* self);
static void exogenesis_fconfirm_PopulateDetails (ExogenesisFConfirm* self);
GType exogenesis_user_detail_get_type (void) G_GNUC_CONST;
ExogenesisUserDetail* exogenesis_install_data_GetMainUser (ExogenesisInstallData* self);
const gchar* exogenesis_install_data_get_TimeZone (ExogenesisInstallData* self);
const gchar* exogenesis_install_data_get_KeyboardLayout (ExogenesisInstallData* self);
const gchar* exogenesis_install_data_get_KeyboardVariant (ExogenesisInstallData* self);
const gchar* exogenesis_user_detail_get_Fullname (ExogenesisUserDetail* self);
const gchar* exogenesis_user_detail_get_Username (ExogenesisUserDetail* self);
GType exogenesis_install_partition_get_type (void) G_GNUC_CONST;
const gchar* exogenesis_install_partition_get_Device (ExogenesisInstallPartition* self);
GType exogenesis_main_win_get_type (void) G_GNUC_CONST;
void exogenesis_main_win_Cancel (ExogenesisMainWin* self);
void exogenesis_main_win_ShowPreviousWindow (ExogenesisMainWin* self);
void exogenesis_main_win_ShowNextWindow (ExogenesisMainWin* self);
static void exogenesis_fconfirm_finalize (GObject* obj);


ExogenesisFConfirm* exogenesis_fconfirm_construct (GType object_type) {
	ExogenesisFConfirm * self = NULL;
	self = (ExogenesisFConfirm*) g_object_new (object_type, NULL);
	exogenesis_fconfirm_build (self);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) self->priv->fxdLayout);
	return self;
}


ExogenesisFConfirm* exogenesis_fconfirm_new (void) {
	return exogenesis_fconfirm_construct (EXOGENESIS_TYPE_FCONFIRM);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _exogenesis_fconfirm_OnBtnCancel_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fconfirm_OnBtnCancel_Click (self);
}


static void _exogenesis_fconfirm_OnBtnPrevious_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fconfirm_OnBtnPrevious_Click (self);
}


static void _exogenesis_fconfirm_OnBtnInstall_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fconfirm_OnBtnInstall_Click (self);
}


static void _exogenesis_fconfirm_OnCboHDBootTarget_Changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self) {
	exogenesis_fconfirm_OnCboHDBootTarget_Changed (self);
}


static void _exogenesis_fconfirm_OnRealize_gtk_widget_realize (GtkWidget* _sender, gpointer self) {
	exogenesis_fconfirm_OnRealize (self);
}


static void exogenesis_fconfirm_build (ExogenesisFConfirm* self) {
	GtkBuilder* _tmp0_ = NULL;
	GtkBuilder* builder;
	GObject* _tmp1_ = NULL;
	GtkFixed* _tmp2_;
	GObject* _tmp3_ = NULL;
	GtkButton* _tmp4_;
	GObject* _tmp5_ = NULL;
	GtkButton* _tmp6_;
	GObject* _tmp7_ = NULL;
	GtkButton* _tmp8_;
	GObject* _tmp9_ = NULL;
	GtkComboBox* _tmp10_;
	GObject* _tmp11_ = NULL;
	GtkLabel* _tmp12_;
	GObject* _tmp13_ = NULL;
	GtkScrolledWindow* _tmp14_;
	gint _tmp15_;
	gint _tmp16_;
	GtkCellRendererText* _tmp17_ = NULL;
	GtkCellRendererText* cellHD;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_builder_new ();
	builder = _tmp0_;
	gtk_builder_add_from_file (builder, EXOGENESIS_UIPath, &_inner_error_);
	if (_inner_error_ != NULL) {
		_g_object_unref0 (builder);
		goto __catch2_g_error;
	}
	_tmp1_ = gtk_builder_get_object (builder, "fxdConfirmation");
	_tmp2_ = _g_object_ref0 (GTK_FIXED (_tmp1_));
	_g_object_unref0 (self->priv->fxdLayout);
	self->priv->fxdLayout = _tmp2_;
	_tmp3_ = gtk_builder_get_object (builder, "btnConfirmCancel");
	_tmp4_ = _g_object_ref0 (GTK_BUTTON (_tmp3_));
	_g_object_unref0 (self->priv->btnCancel);
	self->priv->btnCancel = _tmp4_;
	_tmp5_ = gtk_builder_get_object (builder, "btnConfirmPrevious");
	_tmp6_ = _g_object_ref0 (GTK_BUTTON (_tmp5_));
	_g_object_unref0 (self->priv->btnPrevious);
	self->priv->btnPrevious = _tmp6_;
	_tmp7_ = gtk_builder_get_object (builder, "btnConfirmInstall");
	_tmp8_ = _g_object_ref0 (GTK_BUTTON (_tmp7_));
	_g_object_unref0 (self->priv->btnInstall);
	self->priv->btnInstall = _tmp8_;
	_tmp9_ = gtk_builder_get_object (builder, "cboHDBootTarget");
	_tmp10_ = _g_object_ref0 (GTK_COMBO_BOX (_tmp9_));
	_g_object_unref0 (self->priv->cboHDBootTarget);
	self->priv->cboHDBootTarget = _tmp10_;
	_tmp11_ = gtk_builder_get_object (builder, "lblConfirmText");
	_tmp12_ = _g_object_ref0 (GTK_LABEL (_tmp11_));
	_g_object_unref0 (self->priv->lblConfirmText);
	self->priv->lblConfirmText = _tmp12_;
	_tmp13_ = gtk_builder_get_object (builder, "scrConfirm");
	_tmp14_ = _g_object_ref0 (GTK_SCROLLED_WINDOW (_tmp13_));
	_g_object_unref0 (self->priv->scrConfirm);
	self->priv->scrConfirm = _tmp14_;
	g_signal_connect_object (self->priv->btnCancel, "clicked", (GCallback) _exogenesis_fconfirm_OnBtnCancel_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btnPrevious, "clicked", (GCallback) _exogenesis_fconfirm_OnBtnPrevious_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btnInstall, "clicked", (GCallback) _exogenesis_fconfirm_OnBtnInstall_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->cboHDBootTarget, "changed", (GCallback) _exogenesis_fconfirm_OnCboHDBootTarget_Changed_gtk_combo_box_changed, self, 0);
	g_signal_connect_object ((GtkWidget*) self->priv->fxdLayout, "realize", (GCallback) _exogenesis_fconfirm_OnRealize_gtk_widget_realize, self, 0);
	g_object_get ((GtkWidget*) self->priv->fxdLayout, "width-request", &_tmp15_, NULL);
	g_object_set ((GtkWidget*) self, "width-request", _tmp15_, NULL);
	g_object_get ((GtkWidget*) self->priv->fxdLayout, "height-request", &_tmp16_, NULL);
	g_object_set ((GtkWidget*) self, "height-request", _tmp16_, NULL);
	gtk_combo_box_set_model (self->priv->cboHDBootTarget, (GtkTreeModel*) self->priv->_lstGrubTarget);
	_tmp17_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	cellHD = g_object_ref_sink (_tmp17_);
	gtk_cell_layout_pack_start ((GtkCellLayout*) self->priv->cboHDBootTarget, (GtkCellRenderer*) cellHD, TRUE);
	gtk_cell_layout_add_attribute ((GtkCellLayout*) self->priv->cboHDBootTarget, (GtkCellRenderer*) cellHD, "text", 0);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (cellHD);
	_g_object_unref0 (builder);
	goto __finally2;
	__catch2_g_error:
	{
		GError * err;
		gchar* _tmp18_;
		gchar* _tmp19_;
		GtkMessageDialog* _tmp20_ = NULL;
		GtkMessageDialog* _tmp21_;
		GtkMessageDialog* msg;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp18_ = g_strconcat ("Failed to load UI\n", err->message, NULL);
		_tmp19_ = _tmp18_;
		_tmp20_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_ERROR, GTK_BUTTONS_CANCEL, _tmp19_);
		_tmp21_ = g_object_ref_sink (_tmp20_);
		_g_free0 (_tmp19_);
		msg = _tmp21_;
		gtk_dialog_run ((GtkDialog*) msg);
		gtk_main_quit ();
		_g_object_unref0 (msg);
		_g_error_free0 (err);
	}
	__finally2:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void exogenesis_fconfirm_PopulateGrubTarget (ExogenesisFConfirm* self) {
	GtkTreeIter iter = {0};
	g_return_if_fail (self != NULL);
	gtk_list_store_clear (self->priv->_lstGrubTarget);
	{
		GeeIterator* _tmp0_ = NULL;
		GeeIterator* _hd_it;
		_tmp0_ = gee_iterable_iterator ((GeeIterable*) exogenesis_gInstallData);
		_hd_it = _tmp0_;
		while (TRUE) {
			gboolean _tmp1_;
			gpointer _tmp2_ = NULL;
			ExogenesisInstallHardDisk* hd;
			GtkTreeIter _tmp3_ = {0};
			const gchar* _tmp4_ = NULL;
			_tmp1_ = gee_iterator_next (_hd_it);
			if (!_tmp1_) {
				break;
			}
			_tmp2_ = gee_iterator_get (_hd_it);
			hd = (ExogenesisInstallHardDisk*) _tmp2_;
			exogenesis_general_functions_LogIt ("Oooo you have a hard one!\n");
			gtk_list_store_append (self->priv->_lstGrubTarget, &_tmp3_);
			iter = _tmp3_;
			_tmp4_ = exogenesis_install_hard_disk_get_DeviceName (hd);
			gtk_list_store_set (self->priv->_lstGrubTarget, &iter, 0, _tmp4_, -1, -1);
			_g_object_unref0 (hd);
		}
		_g_object_unref0 (_hd_it);
	}
}


static void exogenesis_fconfirm_PopulateDetails (ExogenesisFConfirm* self) {
	ExogenesisUserDetail* _tmp0_ = NULL;
	ExogenesisUserDetail* ud;
	GString* _tmp1_ = NULL;
	GString* options;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	const gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	gboolean _tmp8_ = FALSE;
	const gchar* _tmp9_ = NULL;
	const gchar* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_;
	g_return_if_fail (self != NULL);
	_tmp0_ = exogenesis_install_data_GetMainUser (exogenesis_gInstallData);
	ud = _tmp0_;
	_tmp1_ = g_string_new ("");
	options = _tmp1_;
	_tmp2_ = exogenesis_install_data_get_TimeZone (exogenesis_gInstallData);
	_tmp3_ = g_strdup_printf ("<b>%s</b> %s\n\n", self->priv->_TimeZone, _tmp2_);
	_tmp4_ = _tmp3_;
	g_string_append (options, _tmp4_);
	_g_free0 (_tmp4_);
	_tmp5_ = exogenesis_install_data_get_KeyboardLayout (exogenesis_gInstallData);
	_tmp6_ = g_strdup_printf ("<b>%s</b> %s\n", self->priv->_KeyboardSetting, _tmp5_);
	_tmp7_ = _tmp6_;
	g_string_append (options, _tmp7_);
	_g_free0 (_tmp7_);
	_tmp9_ = exogenesis_install_data_get_KeyboardVariant (exogenesis_gInstallData);
	if (_tmp9_ != NULL) {
		const gchar* _tmp10_ = NULL;
		_tmp10_ = exogenesis_install_data_get_KeyboardVariant (exogenesis_gInstallData);
		_tmp8_ = g_strcmp0 (_tmp10_, "") != 0;
	} else {
		_tmp8_ = FALSE;
	}
	if (_tmp8_) {
		const gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_;
		_tmp11_ = exogenesis_install_data_get_KeyboardVariant (exogenesis_gInstallData);
		_tmp12_ = g_strdup_printf ("<b>%s</b> %s\n", self->priv->_KeyboardVariant, _tmp11_);
		_tmp13_ = _tmp12_;
		g_string_append (options, _tmp13_);
		_g_free0 (_tmp13_);
	}
	_tmp14_ = exogenesis_user_detail_get_Fullname (ud);
	_tmp15_ = exogenesis_user_detail_get_Username (ud);
	_tmp16_ = g_strdup_printf ("\n<b>%s</b> %s - %s\n", self->priv->_UserDetail, _tmp14_, _tmp15_);
	_tmp17_ = _tmp16_;
	g_string_append (options, _tmp17_);
	_g_free0 (_tmp17_);
	_tmp18_ = g_strdup_printf ("\n<b>%s</b>\n", self->priv->_HDTarget);
	_tmp19_ = _tmp18_;
	g_string_append (options, _tmp19_);
	_g_free0 (_tmp19_);
	{
		GeeIterator* _tmp20_ = NULL;
		GeeIterator* _hd_it;
		_tmp20_ = gee_iterable_iterator ((GeeIterable*) exogenesis_gInstallData);
		_hd_it = _tmp20_;
		while (TRUE) {
			gboolean _tmp21_;
			gpointer _tmp22_ = NULL;
			ExogenesisInstallHardDisk* hd;
			const gchar* _tmp23_ = NULL;
			gchar* _tmp24_ = NULL;
			gchar* _tmp25_;
			_tmp21_ = gee_iterator_next (_hd_it);
			if (!_tmp21_) {
				break;
			}
			_tmp22_ = gee_iterator_get (_hd_it);
			hd = (ExogenesisInstallHardDisk*) _tmp22_;
			_tmp23_ = exogenesis_install_hard_disk_get_DeviceName (hd);
			_tmp24_ = g_strdup_printf ("\t%s\n", _tmp23_);
			_tmp25_ = _tmp24_;
			g_string_append (options, _tmp25_);
			_g_free0 (_tmp25_);
			{
				GeeIterator* _tmp26_ = NULL;
				GeeIterator* _ip_it;
				_tmp26_ = gee_iterable_iterator ((GeeIterable*) hd);
				_ip_it = _tmp26_;
				while (TRUE) {
					gboolean _tmp27_;
					gpointer _tmp28_ = NULL;
					ExogenesisInstallPartition* ip;
					const gchar* _tmp29_ = NULL;
					gchar* _tmp30_ = NULL;
					gchar* _tmp31_;
					_tmp27_ = gee_iterator_next (_ip_it);
					if (!_tmp27_) {
						break;
					}
					_tmp28_ = gee_iterator_get (_ip_it);
					ip = (ExogenesisInstallPartition*) _tmp28_;
					_tmp29_ = exogenesis_install_partition_get_Device (ip);
					_tmp30_ = g_strdup_printf ("\t\t%s\n", _tmp29_);
					_tmp31_ = _tmp30_;
					g_string_append (options, _tmp31_);
					_g_free0 (_tmp31_);
					_g_object_unref0 (ip);
				}
				_g_object_unref0 (_ip_it);
			}
			_g_object_unref0 (hd);
		}
		_g_object_unref0 (_hd_it);
	}
	gtk_label_set_label (self->priv->lblConfirmText, options->str);
	_g_string_free0 (options);
	_g_object_unref0 (ud);
}


void exogenesis_fconfirm_OnCboHDBootTarget_Changed (ExogenesisFConfirm* self) {
	g_return_if_fail (self != NULL);
}


void exogenesis_fconfirm_OnRealize (ExogenesisFConfirm* self) {
	g_return_if_fail (self != NULL);
	exogenesis_fconfirm_PopulateDetails (self);
	exogenesis_fconfirm_PopulateGrubTarget (self);
}


void exogenesis_fconfirm_OnBtnCancel_Click (ExogenesisFConfirm* self) {
	GtkContainer* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_widget_get_parent ((GtkWidget*) self);
	exogenesis_main_win_Cancel (EXOGENESIS_MAIN_WIN (_tmp0_));
}


void exogenesis_fconfirm_OnBtnPrevious_Click (ExogenesisFConfirm* self) {
	GtkContainer* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_widget_get_parent ((GtkWidget*) self);
	exogenesis_main_win_ShowPreviousWindow (EXOGENESIS_MAIN_WIN (_tmp0_));
}


void exogenesis_fconfirm_OnBtnInstall_Click (ExogenesisFConfirm* self) {
	GtkContainer* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_widget_get_parent ((GtkWidget*) self);
	exogenesis_main_win_ShowNextWindow (EXOGENESIS_MAIN_WIN (_tmp0_));
}


static void exogenesis_fconfirm_class_init (ExogenesisFConfirmClass * klass) {
	exogenesis_fconfirm_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ExogenesisFConfirmPrivate));
	G_OBJECT_CLASS (klass)->finalize = exogenesis_fconfirm_finalize;
}


static void exogenesis_fconfirm_instance_init (ExogenesisFConfirm * self) {
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GtkListStore* _tmp6_ = NULL;
	self->priv = EXOGENESIS_FCONFIRM_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("Confirmation Options");
	self->priv->_Title = _tmp0_;
	_tmp1_ = g_strdup ("User To Be Added:");
	self->priv->_UserDetail = _tmp1_;
	_tmp2_ = g_strdup ("Keyboard Setting:");
	self->priv->_KeyboardSetting = _tmp2_;
	_tmp3_ = g_strdup ("Keyboard Variant:");
	self->priv->_KeyboardVariant = _tmp3_;
	_tmp4_ = g_strdup ("Timezone:");
	self->priv->_TimeZone = _tmp4_;
	_tmp5_ = g_strdup ("Hard Disk Configuration:");
	self->priv->_HDTarget = _tmp5_;
	_tmp6_ = gtk_list_store_new (1, G_TYPE_STRING);
	self->priv->_lstGrubTarget = _tmp6_;
}


static void exogenesis_fconfirm_finalize (GObject* obj) {
	ExogenesisFConfirm * self;
	self = EXOGENESIS_FCONFIRM (obj);
	_g_object_unref0 (self->priv->fxdLayout);
	_g_object_unref0 (self->priv->btnCancel);
	_g_object_unref0 (self->priv->btnPrevious);
	_g_object_unref0 (self->priv->btnInstall);
	_g_object_unref0 (self->priv->cboHDBootTarget);
	_g_object_unref0 (self->priv->lblConfirmText);
	_g_object_unref0 (self->priv->scrConfirm);
	_g_free0 (self->priv->_Title);
	_g_free0 (self->priv->_UserDetail);
	_g_free0 (self->priv->_KeyboardSetting);
	_g_free0 (self->priv->_KeyboardVariant);
	_g_free0 (self->priv->_TimeZone);
	_g_free0 (self->priv->_HDTarget);
	_g_object_unref0 (self->priv->_lstGrubTarget);
	G_OBJECT_CLASS (exogenesis_fconfirm_parent_class)->finalize (obj);
}


GType exogenesis_fconfirm_get_type (void) {
	static volatile gsize exogenesis_fconfirm_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_fconfirm_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisFConfirmClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_fconfirm_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisFConfirm), 0, (GInstanceInitFunc) exogenesis_fconfirm_instance_init, NULL };
		GType exogenesis_fconfirm_type_id;
		exogenesis_fconfirm_type_id = g_type_register_static (GTK_TYPE_LAYOUT, "ExogenesisFConfirm", &g_define_type_info, 0);
		g_once_init_leave (&exogenesis_fconfirm_type_id__volatile, exogenesis_fconfirm_type_id);
	}
	return exogenesis_fconfirm_type_id__volatile;
}



