/* exoFHDConfig.c generated by valac 0.12.1, the Vala compiler
 * generated from exoFHDConfig.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <stdio.h>
#include <float.h>
#include <math.h>


#define EXOGENESIS_TYPE_FHD_CONFIG (exogenesis_fhd_config_get_type ())
#define EXOGENESIS_FHD_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_FHD_CONFIG, ExogenesisFHDConfig))
#define EXOGENESIS_FHD_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_FHD_CONFIG, ExogenesisFHDConfigClass))
#define EXOGENESIS_IS_FHD_CONFIG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_FHD_CONFIG))
#define EXOGENESIS_IS_FHD_CONFIG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_FHD_CONFIG))
#define EXOGENESIS_FHD_CONFIG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_FHD_CONFIG, ExogenesisFHDConfigClass))

typedef struct _ExogenesisFHDConfig ExogenesisFHDConfig;
typedef struct _ExogenesisFHDConfigClass ExogenesisFHDConfigClass;
typedef struct _ExogenesisFHDConfigPrivate ExogenesisFHDConfigPrivate;

#define TYPE_SEGMENTED_BAR (segmented_bar_get_type ())
#define SEGMENTED_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SEGMENTED_BAR, SegmentedBar))
#define SEGMENTED_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SEGMENTED_BAR, SegmentedBarClass))
#define IS_SEGMENTED_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SEGMENTED_BAR))
#define IS_SEGMENTED_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SEGMENTED_BAR))
#define SEGMENTED_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SEGMENTED_BAR, SegmentedBarClass))

typedef struct _SegmentedBar SegmentedBar;
typedef struct _SegmentedBarClass SegmentedBarClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define EXOGENESIS_TYPE_PREVIOUS_OS (exogenesis_previous_os_get_type ())
#define EXOGENESIS_PREVIOUS_OS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_PREVIOUS_OS, ExogenesisPreviousOS))
#define EXOGENESIS_PREVIOUS_OS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_PREVIOUS_OS, ExogenesisPreviousOSClass))
#define EXOGENESIS_IS_PREVIOUS_OS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_PREVIOUS_OS))
#define EXOGENESIS_IS_PREVIOUS_OS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_PREVIOUS_OS))
#define EXOGENESIS_PREVIOUS_OS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_PREVIOUS_OS, ExogenesisPreviousOSClass))

typedef struct _ExogenesisPreviousOS ExogenesisPreviousOS;
typedef struct _ExogenesisPreviousOSClass ExogenesisPreviousOSClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define EXOGENESIS_TYPE_HD_MANAGER (exogenesis_hd_manager_get_type ())
#define EXOGENESIS_HD_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_HD_MANAGER, ExogenesisHDManager))
#define EXOGENESIS_HD_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_HD_MANAGER, ExogenesisHDManagerClass))
#define EXOGENESIS_IS_HD_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_HD_MANAGER))
#define EXOGENESIS_IS_HD_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_HD_MANAGER))
#define EXOGENESIS_HD_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_HD_MANAGER, ExogenesisHDManagerClass))

typedef struct _ExogenesisHDManager ExogenesisHDManager;
typedef struct _ExogenesisHDManagerClass ExogenesisHDManagerClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ExogenesisHDManagerPrivate ExogenesisHDManagerPrivate;

#define EXOGENESIS_TYPE_HARD_DISK (exogenesis_hard_disk_get_type ())
#define EXOGENESIS_HARD_DISK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_HARD_DISK, ExogenesisHardDisk))
#define EXOGENESIS_HARD_DISK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_HARD_DISK, ExogenesisHardDiskClass))
#define EXOGENESIS_IS_HARD_DISK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_HARD_DISK))
#define EXOGENESIS_IS_HARD_DISK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_HARD_DISK))
#define EXOGENESIS_HARD_DISK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_HARD_DISK, ExogenesisHardDiskClass))

typedef struct _ExogenesisHardDisk ExogenesisHardDisk;
typedef struct _ExogenesisHardDiskClass ExogenesisHardDiskClass;

#define EXOGENESIS_TYPE_PARTITION_INFO (exogenesis_partition_info_get_type ())
#define EXOGENESIS_PARTITION_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_PARTITION_INFO, ExogenesisPartitionInfo))
#define EXOGENESIS_PARTITION_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_PARTITION_INFO, ExogenesisPartitionInfoClass))
#define EXOGENESIS_IS_PARTITION_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_PARTITION_INFO))
#define EXOGENESIS_IS_PARTITION_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_PARTITION_INFO))
#define EXOGENESIS_PARTITION_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_PARTITION_INFO, ExogenesisPartitionInfoClass))

typedef struct _ExogenesisPartitionInfo ExogenesisPartitionInfo;
typedef struct _ExogenesisPartitionInfoClass ExogenesisPartitionInfoClass;

#define EXOGENESIS_TYPE_INSTALL_DATA (exogenesis_install_data_get_type ())
#define EXOGENESIS_INSTALL_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallData))
#define EXOGENESIS_INSTALL_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallDataClass))
#define EXOGENESIS_IS_INSTALL_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_INSTALL_DATA))
#define EXOGENESIS_IS_INSTALL_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_INSTALL_DATA))
#define EXOGENESIS_INSTALL_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallDataClass))

typedef struct _ExogenesisInstallData ExogenesisInstallData;
typedef struct _ExogenesisInstallDataClass ExogenesisInstallDataClass;

#define EXOGENESIS_TYPE_INSTALL_HARD_DISK (exogenesis_install_hard_disk_get_type ())
#define EXOGENESIS_INSTALL_HARD_DISK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_INSTALL_HARD_DISK, ExogenesisInstallHardDisk))
#define EXOGENESIS_INSTALL_HARD_DISK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_INSTALL_HARD_DISK, ExogenesisInstallHardDiskClass))
#define EXOGENESIS_IS_INSTALL_HARD_DISK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_INSTALL_HARD_DISK))
#define EXOGENESIS_IS_INSTALL_HARD_DISK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_INSTALL_HARD_DISK))
#define EXOGENESIS_INSTALL_HARD_DISK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_INSTALL_HARD_DISK, ExogenesisInstallHardDiskClass))

typedef struct _ExogenesisInstallHardDisk ExogenesisInstallHardDisk;
typedef struct _ExogenesisInstallHardDiskClass ExogenesisInstallHardDiskClass;

#define EXOGENESIS_TYPE_INSTALL_PARTITION (exogenesis_install_partition_get_type ())
#define EXOGENESIS_INSTALL_PARTITION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_INSTALL_PARTITION, ExogenesisInstallPartition))
#define EXOGENESIS_INSTALL_PARTITION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_INSTALL_PARTITION, ExogenesisInstallPartitionClass))
#define EXOGENESIS_IS_INSTALL_PARTITION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_INSTALL_PARTITION))
#define EXOGENESIS_IS_INSTALL_PARTITION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_INSTALL_PARTITION))
#define EXOGENESIS_INSTALL_PARTITION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_INSTALL_PARTITION, ExogenesisInstallPartitionClass))

typedef struct _ExogenesisInstallPartition ExogenesisInstallPartition;
typedef struct _ExogenesisInstallPartitionClass ExogenesisInstallPartitionClass;

#define EXOGENESIS_TYPE_MAIN_WIN (exogenesis_main_win_get_type ())
#define EXOGENESIS_MAIN_WIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWin))
#define EXOGENESIS_MAIN_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWinClass))
#define EXOGENESIS_IS_MAIN_WIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_MAIN_WIN))
#define EXOGENESIS_IS_MAIN_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_MAIN_WIN))
#define EXOGENESIS_MAIN_WIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWinClass))

typedef struct _ExogenesisMainWin ExogenesisMainWin;
typedef struct _ExogenesisMainWinClass ExogenesisMainWinClass;

#define EXOGENESIS_TYPE_INSTALLER (exogenesis_installer_get_type ())
#define EXOGENESIS_INSTALLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_INSTALLER, ExogenesisInstaller))
#define EXOGENESIS_INSTALLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_INSTALLER, ExogenesisInstallerClass))
#define EXOGENESIS_IS_INSTALLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_INSTALLER))
#define EXOGENESIS_IS_INSTALLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_INSTALLER))
#define EXOGENESIS_INSTALLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_INSTALLER, ExogenesisInstallerClass))

typedef struct _ExogenesisInstaller ExogenesisInstaller;
typedef struct _ExogenesisInstallerClass ExogenesisInstallerClass;
#define _exogenesis_installer_unref0(var) ((var == NULL) ? NULL : (var = (exogenesis_installer_unref (var), NULL)))

struct _ExogenesisFHDConfig {
	GtkLayout parent_instance;
	ExogenesisFHDConfigPrivate * priv;
};

struct _ExogenesisFHDConfigClass {
	GtkLayoutClass parent_class;
};

struct _ExogenesisFHDConfigPrivate {
	GtkBox* segbox1;
	GtkBox* segbox2;
	GtkButton* btnPrevious;
	GtkButton* btnNext;
	GtkButton* btnCancel;
	GtkRadioButton* rdoAdvanced;
	GtkRadioButton* rdoUseAll;
	GtkCheckButton* chkKeepHome;
	SegmentedBar* segbarHD;
	SegmentedBar* segbarHDA;
	GtkFixed* fxdHDConfig;
	GtkLabel* lblHD;
	GtkComboBox* cboHD;
	GtkLabel* lblPrevious;
	GtkButton* btnCreateTest;
	GtkImage* imgBackground;
	GtkListStore* _disks;
};

struct _ExogenesisHDManager {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ExogenesisHDManagerPrivate * priv;
	gboolean ThreadStop;
	gboolean PartitionerRunning;
	GeeArrayList* HardDisks;
};

struct _ExogenesisHDManagerClass {
	GTypeClass parent_class;
	void (*finalize) (ExogenesisHDManager *self);
};


static gpointer exogenesis_fhd_config_parent_class = NULL;
extern ExogenesisPreviousOS* exogenesis_gPreviousOS;
extern gchar* exogenesis_AppPath;
extern ExogenesisHDManager* exogenesis_gHDManager;
extern ExogenesisInstallData* exogenesis_gInstallData;

GType exogenesis_fhd_config_get_type (void) G_GNUC_CONST;
GType segmented_bar_get_type (void) G_GNUC_CONST;
#define EXOGENESIS_FHD_CONFIG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXOGENESIS_TYPE_FHD_CONFIG, ExogenesisFHDConfigPrivate))
enum  {
	EXOGENESIS_FHD_CONFIG_DUMMY_PROPERTY
};
ExogenesisFHDConfig* exogenesis_fhd_config_new (void);
ExogenesisFHDConfig* exogenesis_fhd_config_construct (GType object_type);
static void exogenesis_fhd_config_build (ExogenesisFHDConfig* self);
static void exogenesis_fhd_config_GetDiskInfo (ExogenesisFHDConfig* self);
gpointer exogenesis_previous_os_ref (gpointer instance);
void exogenesis_previous_os_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_previous_os (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_previous_os (GValue* value, gpointer v_object);
void exogenesis_value_take_previous_os (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_previous_os (const GValue* value);
GType exogenesis_previous_os_get_type (void) G_GNUC_CONST;
void exogenesis_previous_os_GetFSTabMountPoints (ExogenesisPreviousOS* self);
#define EXOGENESIS_UIPath "/home/steve/1-work/anjuta/exogenesis/src/exogenesis.ui"
SegmentedBar* segmented_bar_new (void);
SegmentedBar* segmented_bar_construct (GType object_type);
void exogenesis_fhd_config_OnBtnNext_Click (ExogenesisFHDConfig* self);
static void _exogenesis_fhd_config_OnBtnNext_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_fhd_config_OnBtnPrevious_Click (ExogenesisFHDConfig* self);
static void _exogenesis_fhd_config_OnBtnPrevious_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_fhd_config_OnBtnCancel_Click (ExogenesisFHDConfig* self);
static void _exogenesis_fhd_config_OnBtnCancel_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_fhd_config_OnCboHD_Changed (ExogenesisFHDConfig* self);
static void _exogenesis_fhd_config_OnCboHD_Changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self);
void exogenesis_fhd_config_OnRdoAdvanced_Click (ExogenesisFHDConfig* self);
static void _exogenesis_fhd_config_OnRdoAdvanced_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_fhd_config_OnRdoUseAll_Click (ExogenesisFHDConfig* self);
static void _exogenesis_fhd_config_OnRdoUseAll_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_fhd_config_OnFxdHDConfig_Realize (ExogenesisFHDConfig* self);
static void _exogenesis_fhd_config_OnFxdHDConfig_Realize_gtk_widget_realize (GtkWidget* _sender, gpointer self);
void exogenesis_fhd_config_OnChkKeepHome_Click (ExogenesisFHDConfig* self);
static void _exogenesis_fhd_config_OnChkKeepHome_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
void exogenesis_fhd_config_OnBtnCreate_Click (ExogenesisFHDConfig* self);
static void _exogenesis_fhd_config_OnBtnCreate_Click_gtk_button_clicked (GtkButton* _sender, gpointer self);
gpointer exogenesis_hd_manager_ref (gpointer instance);
void exogenesis_hd_manager_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_hd_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_hd_manager (GValue* value, gpointer v_object);
void exogenesis_value_take_hd_manager (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_hd_manager (const GValue* value);
GType exogenesis_hd_manager_get_type (void) G_GNUC_CONST;
static void exogenesis_fhd_config_OnDriveMounted (ExogenesisFHDConfig* self, const gchar* mountpoint);
static void _exogenesis_fhd_config_OnDriveMounted_exogenesis_hd_manager_drive_mounted (ExogenesisHDManager* _sender, const gchar* mountpoint, gpointer self);
static void exogenesis_fhd_config_OnDriveUnMount (ExogenesisFHDConfig* self);
static void _exogenesis_fhd_config_OnDriveUnMount_exogenesis_hd_manager_drive_un_mounted (ExogenesisHDManager* _sender, gpointer self);
static void exogenesis_fhd_config_OnDiskManagerError (ExogenesisFHDConfig* self, GError* _error_);
static void _exogenesis_fhd_config_OnDiskManagerError_exogenesis_hd_manager_disk_manager_error (ExogenesisHDManager* _sender, GError* err, gpointer self);
static void exogenesis_fhd_config_OnDevicesRefreshed (ExogenesisFHDConfig* self);
static void _exogenesis_fhd_config_OnDevicesRefreshed_exogenesis_hd_manager_devices_refreshed (ExogenesisHDManager* _sender, gpointer self);
void segmented_bar_set_BarHeight (SegmentedBar* self, gint value);
gint segmented_bar_get_BarHeight (SegmentedBar* self);
void segmented_bar_set_HorizontalPadding (SegmentedBar* self, gint value);
void segmented_bar_set_ShowReflection (SegmentedBar* self, gboolean value);
static void exogenesis_fhd_config_SetLabels (ExogenesisFHDConfig* self);
GType exogenesis_hard_disk_get_type (void) G_GNUC_CONST;
gboolean exogenesis_hard_disk_get_IsOptical (ExogenesisHardDisk* self);
const gchar* exogenesis_hard_disk_get_SerialNumber (ExogenesisHardDisk* self);
const gchar* exogenesis_hard_disk_get_Model (ExogenesisHardDisk* self);
const gchar* exogenesis_hard_disk_get_CapacityDescription (ExogenesisHardDisk* self);
static void exogenesis_fhd_config_DisplayPartitionInfo (ExogenesisFHDConfig* self, const gchar* hdserial, SegmentedBar* segbar);
void segmented_bar_RemoveAllSegments (SegmentedBar* self);
void exogenesis_hard_disk_SortPartitions (ExogenesisHardDisk* self);
GType exogenesis_partition_info_get_type (void) G_GNUC_CONST;
const gchar* exogenesis_partition_info_get_OSType (ExogenesisPartitionInfo* self);
const gchar* exogenesis_partition_info_get_PartitionType (ExogenesisPartitionInfo* self);
const gchar* exogenesis_partition_info_get_CapacityDescription (ExogenesisPartitionInfo* self);
const gchar* exogenesis_partition_info_get_FSTabMountPoint (ExogenesisPartitionInfo* self);
static void exogenesis_fhd_config_AddToDisk (ExogenesisFHDConfig* self, SegmentedBar* bar, guint64 HDSize, guint64 PartitionSize, const gchar* title, gint count);
guint64 exogenesis_hard_disk_get_Capacity (ExogenesisHardDisk* self);
guint64 exogenesis_partition_info_get_Capacity (ExogenesisPartitionInfo* self);
const gchar* exogenesis_hard_disk_get_PreviousOS (ExogenesisHardDisk* self);
static gchar* exogenesis_fhd_config_GetSelectedHD (ExogenesisFHDConfig* self);
static void exogenesis_fhd_config_DisplaySuggested (ExogenesisFHDConfig* self, const gchar* hdserial);
ExogenesisHardDisk* exogenesis_hd_manager_GetHDBySerial (ExogenesisHDManager* self, const gchar* serialNumber);
static guint64 exogenesis_fhd_config_RootSize (ExogenesisFHDConfig* self, guint64 totalsize);
gchar* exogenesis_general_functions_FormatHDSize (guint64 size);
static guint64 exogenesis_fhd_config_HomeSize (ExogenesisFHDConfig* self, guint64 totalsize);
static guint64 exogenesis_fhd_config_VarSize (ExogenesisFHDConfig* self, guint64 totalsize);
static guint64 exogenesis_fhd_config_SwapSize (ExogenesisFHDConfig* self, guint64 totalsize);
static void exogenesis_fhd_config_DisplayInstallHDInfo (ExogenesisFHDConfig* self, const gchar* serial);
GType exogenesis_install_data_get_type (void) G_GNUC_CONST;
gint exogenesis_install_data_get_HardDiskCount (ExogenesisInstallData* self);
GType exogenesis_install_hard_disk_get_type (void) G_GNUC_CONST;
const gchar* exogenesis_install_hard_disk_get_SerialNumber (ExogenesisInstallHardDisk* self);
GType exogenesis_install_partition_get_type (void) G_GNUC_CONST;
gboolean exogenesis_install_partition_get_Format (ExogenesisInstallPartition* self);
gboolean exogenesis_install_partition_get_NewPartition (ExogenesisInstallPartition* self);
guint64 exogenesis_install_partition_get_ByteSize (ExogenesisInstallPartition* self);
const gchar* exogenesis_install_partition_get_MountPoint (ExogenesisInstallPartition* self);
const gchar* exogenesis_install_partition_get_Type (ExogenesisInstallPartition* self);
gint segmented_bar_get_Remainder (SegmentedBar* self);
static void exogenesis_fhd_config_PopulateInstallInfo (ExogenesisFHDConfig* self);
ExogenesisInstallHardDisk* exogenesis_install_hard_disk_new (void);
ExogenesisInstallHardDisk* exogenesis_install_hard_disk_construct (GType object_type);
const gchar* exogenesis_hard_disk_get_Device (ExogenesisHardDisk* self);
void exogenesis_install_hard_disk_set_DeviceName (ExogenesisInstallHardDisk* self, const gchar* value);
void exogenesis_install_hard_disk_set_SerialNumber (ExogenesisInstallHardDisk* self, const gchar* value);
ExogenesisInstallPartition* exogenesis_install_partition_new (void);
ExogenesisInstallPartition* exogenesis_install_partition_construct (GType object_type);
void exogenesis_install_partition_set_ByteSize (ExogenesisInstallPartition* self, guint64 value);
void exogenesis_install_partition_set_DisplaySize (ExogenesisInstallPartition* self, const gchar* value);
const gchar* exogenesis_partition_info_get_MountPoint (ExogenesisPartitionInfo* self);
void exogenesis_install_partition_set_Format (ExogenesisInstallPartition* self, gboolean value);
void exogenesis_install_partition_set_MountPoint (ExogenesisInstallPartition* self, const gchar* value);
void exogenesis_install_partition_set_Type (ExogenesisInstallPartition* self, const gchar* value);
const gchar* exogenesis_partition_info_get_PartitionLabel (ExogenesisPartitionInfo* self);
void exogenesis_install_partition_set_Label (ExogenesisInstallPartition* self, const gchar* value);
const gchar* exogenesis_partition_info_get_Device (ExogenesisPartitionInfo* self);
void exogenesis_install_partition_set_Device (ExogenesisInstallPartition* self, const gchar* value);
void exogenesis_install_hard_disk_AddPartition (ExogenesisInstallHardDisk* self, ExogenesisInstallPartition* partition);
void exogenesis_install_data_AddInstallDisk (ExogenesisInstallData* self, ExogenesisInstallHardDisk* hd);
void exogenesis_general_functions_LogIt (const gchar* Message);
gboolean exogenesis_hard_disk_get_HasHomePartition (ExogenesisHardDisk* self);
GType exogenesis_main_win_get_type (void) G_GNUC_CONST;
void exogenesis_main_win_ShowNextWindow (ExogenesisMainWin* self);
ExogenesisInstaller* exogenesis_installer_new (void);
ExogenesisInstaller* exogenesis_installer_construct (GType object_type);
gpointer exogenesis_installer_ref (gpointer instance);
void exogenesis_installer_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_installer (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_installer (GValue* value, gpointer v_object);
void exogenesis_value_take_installer (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_installer (const GValue* value);
GType exogenesis_installer_get_type (void) G_GNUC_CONST;
void exogenesis_installer_CreatePartitionsStart (ExogenesisInstaller* self, ExogenesisInstallHardDisk* iHD);
ExogenesisInstallHardDisk* exogenesis_install_data_GetTargetHD (ExogenesisInstallData* self, gint index);
void exogenesis_main_win_ShowPreviousWindow (ExogenesisMainWin* self);
void exogenesis_main_win_Cancel (ExogenesisMainWin* self);
void segmented_bar_set_SegmentLabelSpacing (SegmentedBar* self, gint value);
void segmented_bar_AddSegmentRgb (SegmentedBar* self, const gchar* title, gint percent, guint rgbColor);
guint exogenesis_general_functions_BarColour (gint idx);
void exogenesis_fhd_config_OnDeviceConnected (ExogenesisFHDConfig* self);
static void exogenesis_fhd_config_finalize (GObject* obj);


ExogenesisFHDConfig* exogenesis_fhd_config_construct (GType object_type) {
	ExogenesisFHDConfig * self = NULL;
	self = (ExogenesisFHDConfig*) g_object_new (object_type, NULL);
	exogenesis_fhd_config_build (self);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) self->priv->fxdHDConfig);
	exogenesis_fhd_config_GetDiskInfo (self);
	exogenesis_previous_os_GetFSTabMountPoints (exogenesis_gPreviousOS);
	return self;
}


ExogenesisFHDConfig* exogenesis_fhd_config_new (void) {
	return exogenesis_fhd_config_construct (EXOGENESIS_TYPE_FHD_CONFIG);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _exogenesis_fhd_config_OnBtnNext_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fhd_config_OnBtnNext_Click (self);
}


static void _exogenesis_fhd_config_OnBtnPrevious_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fhd_config_OnBtnPrevious_Click (self);
}


static void _exogenesis_fhd_config_OnBtnCancel_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fhd_config_OnBtnCancel_Click (self);
}


static void _exogenesis_fhd_config_OnCboHD_Changed_gtk_combo_box_changed (GtkComboBox* _sender, gpointer self) {
	exogenesis_fhd_config_OnCboHD_Changed (self);
}


static void _exogenesis_fhd_config_OnRdoAdvanced_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fhd_config_OnRdoAdvanced_Click (self);
}


static void _exogenesis_fhd_config_OnRdoUseAll_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fhd_config_OnRdoUseAll_Click (self);
}


static void _exogenesis_fhd_config_OnFxdHDConfig_Realize_gtk_widget_realize (GtkWidget* _sender, gpointer self) {
	exogenesis_fhd_config_OnFxdHDConfig_Realize (self);
}


static void _exogenesis_fhd_config_OnChkKeepHome_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fhd_config_OnChkKeepHome_Click (self);
}


static void _exogenesis_fhd_config_OnBtnCreate_Click_gtk_button_clicked (GtkButton* _sender, gpointer self) {
	exogenesis_fhd_config_OnBtnCreate_Click (self);
}


static void _exogenesis_fhd_config_OnDriveMounted_exogenesis_hd_manager_drive_mounted (ExogenesisHDManager* _sender, const gchar* mountpoint, gpointer self) {
	exogenesis_fhd_config_OnDriveMounted (self, mountpoint);
}


static void _exogenesis_fhd_config_OnDriveUnMount_exogenesis_hd_manager_drive_un_mounted (ExogenesisHDManager* _sender, gpointer self) {
	exogenesis_fhd_config_OnDriveUnMount (self);
}


static void _exogenesis_fhd_config_OnDiskManagerError_exogenesis_hd_manager_disk_manager_error (ExogenesisHDManager* _sender, GError* err, gpointer self) {
	exogenesis_fhd_config_OnDiskManagerError (self, err);
}


static void _exogenesis_fhd_config_OnDevicesRefreshed_exogenesis_hd_manager_devices_refreshed (ExogenesisHDManager* _sender, gpointer self) {
	exogenesis_fhd_config_OnDevicesRefreshed (self);
}


static void exogenesis_fhd_config_build (ExogenesisFHDConfig* self) {
	GtkBuilder* _tmp0_ = NULL;
	GtkBuilder* builder;
	GObject* _tmp1_ = NULL;
	GtkFixed* _tmp2_;
	GObject* _tmp3_ = NULL;
	GtkImage* _tmp4_;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_;
	GObject* _tmp7_ = NULL;
	GtkBox* _tmp8_;
	GObject* _tmp9_ = NULL;
	GtkBox* _tmp10_;
	GObject* _tmp11_ = NULL;
	GtkButton* _tmp12_;
	GObject* _tmp13_ = NULL;
	GtkButton* _tmp14_;
	GObject* _tmp15_ = NULL;
	GtkButton* _tmp16_;
	GObject* _tmp17_ = NULL;
	GtkLabel* _tmp18_;
	GObject* _tmp19_ = NULL;
	GtkComboBox* _tmp20_;
	GObject* _tmp21_ = NULL;
	GtkRadioButton* _tmp22_;
	GObject* _tmp23_ = NULL;
	GtkRadioButton* _tmp24_;
	GObject* _tmp25_ = NULL;
	GtkCheckButton* _tmp26_;
	GObject* _tmp27_ = NULL;
	GtkLabel* _tmp28_;
	GObject* _tmp29_ = NULL;
	GtkButton* _tmp30_;
	SegmentedBar* _tmp31_ = NULL;
	SegmentedBar* _tmp32_ = NULL;
	gint _tmp33_;
	gint _tmp34_;
	gint _tmp35_;
	gint _tmp36_;
	GtkCellRendererText* _tmp37_ = NULL;
	GtkCellRendererText* cellHD;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_builder_new ();
	builder = _tmp0_;
	gtk_builder_add_from_file (builder, EXOGENESIS_UIPath, &_inner_error_);
	if (_inner_error_ != NULL) {
		_g_object_unref0 (builder);
		goto __catch5_g_error;
	}
	_tmp1_ = gtk_builder_get_object (builder, "fxdHDConfig");
	_tmp2_ = _g_object_ref0 (GTK_FIXED (_tmp1_));
	_g_object_unref0 (self->priv->fxdHDConfig);
	self->priv->fxdHDConfig = _tmp2_;
	_tmp3_ = gtk_builder_get_object (builder, "imgBackground");
	_tmp4_ = _g_object_ref0 (GTK_IMAGE (_tmp3_));
	_g_object_unref0 (self->priv->imgBackground);
	self->priv->imgBackground = _tmp4_;
	_tmp5_ = g_strdup_printf ("%s/images/default_bkground.png", exogenesis_AppPath);
	_tmp6_ = _tmp5_;
	gtk_image_set_from_file (self->priv->imgBackground, _tmp6_);
	_g_free0 (_tmp6_);
	_tmp7_ = gtk_builder_get_object (builder, "boxHD1");
	_tmp8_ = _g_object_ref0 (GTK_BOX (_tmp7_));
	_g_object_unref0 (self->priv->segbox1);
	self->priv->segbox1 = _tmp8_;
	_tmp9_ = gtk_builder_get_object (builder, "boxHD2");
	_tmp10_ = _g_object_ref0 (GTK_BOX (_tmp9_));
	_g_object_unref0 (self->priv->segbox2);
	self->priv->segbox2 = _tmp10_;
	_tmp11_ = gtk_builder_get_object (builder, "btnHDPrevious");
	_tmp12_ = _g_object_ref0 (GTK_BUTTON (_tmp11_));
	_g_object_unref0 (self->priv->btnPrevious);
	self->priv->btnPrevious = _tmp12_;
	_tmp13_ = gtk_builder_get_object (builder, "btnHDNext");
	_tmp14_ = _g_object_ref0 (GTK_BUTTON (_tmp13_));
	_g_object_unref0 (self->priv->btnNext);
	self->priv->btnNext = _tmp14_;
	_tmp15_ = gtk_builder_get_object (builder, "btnHDCancel");
	_tmp16_ = _g_object_ref0 (GTK_BUTTON (_tmp15_));
	_g_object_unref0 (self->priv->btnCancel);
	self->priv->btnCancel = _tmp16_;
	_tmp17_ = gtk_builder_get_object (builder, "lblHD");
	_tmp18_ = _g_object_ref0 (GTK_LABEL (_tmp17_));
	_g_object_unref0 (self->priv->lblHD);
	self->priv->lblHD = _tmp18_;
	_tmp19_ = gtk_builder_get_object (builder, "cboHD");
	_tmp20_ = _g_object_ref0 (GTK_COMBO_BOX (_tmp19_));
	_g_object_unref0 (self->priv->cboHD);
	self->priv->cboHD = _tmp20_;
	_tmp21_ = gtk_builder_get_object (builder, "rdoHDAdvanced");
	_tmp22_ = _g_object_ref0 (GTK_RADIO_BUTTON (_tmp21_));
	_g_object_unref0 (self->priv->rdoAdvanced);
	self->priv->rdoAdvanced = _tmp22_;
	_tmp23_ = gtk_builder_get_object (builder, "rdoHDCUseAll");
	_tmp24_ = _g_object_ref0 (GTK_RADIO_BUTTON (_tmp23_));
	_g_object_unref0 (self->priv->rdoUseAll);
	self->priv->rdoUseAll = _tmp24_;
	_tmp25_ = gtk_builder_get_object (builder, "chkHDKeepHome");
	_tmp26_ = _g_object_ref0 (GTK_CHECK_BUTTON (_tmp25_));
	_g_object_unref0 (self->priv->chkKeepHome);
	self->priv->chkKeepHome = _tmp26_;
	_tmp27_ = gtk_builder_get_object (builder, "lblPrevious");
	_tmp28_ = _g_object_ref0 (GTK_LABEL (_tmp27_));
	_g_object_unref0 (self->priv->lblPrevious);
	self->priv->lblPrevious = _tmp28_;
	_tmp29_ = gtk_builder_get_object (builder, "btnCreateTest");
	_tmp30_ = _g_object_ref0 (GTK_BUTTON (_tmp29_));
	_g_object_unref0 (self->priv->btnCreateTest);
	self->priv->btnCreateTest = _tmp30_;
	_tmp31_ = segmented_bar_new ();
	_g_object_unref0 (self->priv->segbarHD);
	self->priv->segbarHD = g_object_ref_sink (_tmp31_);
	_tmp32_ = segmented_bar_new ();
	_g_object_unref0 (self->priv->segbarHDA);
	self->priv->segbarHDA = g_object_ref_sink (_tmp32_);
	g_signal_connect_object (self->priv->btnNext, "clicked", (GCallback) _exogenesis_fhd_config_OnBtnNext_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btnPrevious, "clicked", (GCallback) _exogenesis_fhd_config_OnBtnPrevious_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btnCancel, "clicked", (GCallback) _exogenesis_fhd_config_OnBtnCancel_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->cboHD, "changed", (GCallback) _exogenesis_fhd_config_OnCboHD_Changed_gtk_combo_box_changed, self, 0);
	g_signal_connect_object ((GtkButton*) self->priv->rdoAdvanced, "clicked", (GCallback) _exogenesis_fhd_config_OnRdoAdvanced_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object ((GtkButton*) self->priv->rdoUseAll, "clicked", (GCallback) _exogenesis_fhd_config_OnRdoUseAll_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object ((GtkWidget*) self->priv->fxdHDConfig, "realize", (GCallback) _exogenesis_fhd_config_OnFxdHDConfig_Realize_gtk_widget_realize, self, 0);
	g_signal_connect_object ((GtkButton*) self->priv->chkKeepHome, "clicked", (GCallback) _exogenesis_fhd_config_OnChkKeepHome_Click_gtk_button_clicked, self, 0);
	g_signal_connect_object (self->priv->btnCreateTest, "clicked", (GCallback) _exogenesis_fhd_config_OnBtnCreate_Click_gtk_button_clicked, self, 0);
	g_object_get ((GtkWidget*) self->priv->fxdHDConfig, "width-request", &_tmp33_, NULL);
	g_object_set ((GtkWidget*) self, "width-request", _tmp33_, NULL);
	g_object_get ((GtkWidget*) self->priv->fxdHDConfig, "height-request", &_tmp34_, NULL);
	g_object_set ((GtkWidget*) self, "height-request", _tmp34_, NULL);
	g_signal_connect_object (exogenesis_gHDManager, "drive-mounted", (GCallback) _exogenesis_fhd_config_OnDriveMounted_exogenesis_hd_manager_drive_mounted, self, 0);
	g_signal_connect_object (exogenesis_gHDManager, "drive-un-mounted", (GCallback) _exogenesis_fhd_config_OnDriveUnMount_exogenesis_hd_manager_drive_un_mounted, self, 0);
	g_signal_connect_object (exogenesis_gHDManager, "disk-manager-error", (GCallback) _exogenesis_fhd_config_OnDiskManagerError_exogenesis_hd_manager_disk_manager_error, self, 0);
	g_signal_connect_object (exogenesis_gHDManager, "devices-refreshed", (GCallback) _exogenesis_fhd_config_OnDevicesRefreshed_exogenesis_hd_manager_devices_refreshed, self, 0);
	segmented_bar_set_BarHeight (self->priv->segbarHD, 20);
	_tmp35_ = segmented_bar_get_BarHeight (self->priv->segbarHD);
	segmented_bar_set_HorizontalPadding (self->priv->segbarHD, _tmp35_ / 2);
	segmented_bar_set_ShowReflection (self->priv->segbarHD, TRUE);
	gtk_box_pack_start (self->priv->segbox1, (GtkWidget*) self->priv->segbarHD, FALSE, FALSE, (guint) 0);
	gtk_widget_show_all ((GtkWidget*) self->priv->segbox1);
	segmented_bar_set_BarHeight (self->priv->segbarHDA, 20);
	_tmp36_ = segmented_bar_get_BarHeight (self->priv->segbarHDA);
	segmented_bar_set_HorizontalPadding (self->priv->segbarHDA, _tmp36_ / 2);
	segmented_bar_set_ShowReflection (self->priv->segbarHDA, TRUE);
	gtk_box_pack_start (self->priv->segbox2, (GtkWidget*) self->priv->segbarHDA, FALSE, FALSE, (guint) 0);
	gtk_widget_show_all ((GtkWidget*) self->priv->segbox2);
	exogenesis_fhd_config_SetLabels (self);
	gtk_combo_box_set_model (self->priv->cboHD, (GtkTreeModel*) self->priv->_disks);
	_tmp37_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	cellHD = g_object_ref_sink (_tmp37_);
	gtk_cell_layout_pack_start ((GtkCellLayout*) self->priv->cboHD, (GtkCellRenderer*) cellHD, TRUE);
	gtk_cell_layout_add_attribute ((GtkCellLayout*) self->priv->cboHD, (GtkCellRenderer*) cellHD, "text", 0);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (cellHD);
	_g_object_unref0 (builder);
	goto __finally5;
	__catch5_g_error:
	{
		GError * err;
		gchar* _tmp38_;
		gchar* _tmp39_;
		GtkMessageDialog* _tmp40_ = NULL;
		GtkMessageDialog* _tmp41_;
		GtkMessageDialog* msg;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp38_ = g_strconcat ("Failed to load UI\n", err->message, NULL);
		_tmp39_ = _tmp38_;
		_tmp40_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_ERROR, GTK_BUTTONS_CANCEL, _tmp39_);
		_tmp41_ = g_object_ref_sink (_tmp40_);
		_g_free0 (_tmp39_);
		msg = _tmp41_;
		gtk_dialog_run ((GtkDialog*) msg);
		gtk_main_quit ();
		_g_object_unref0 (msg);
		_g_error_free0 (err);
	}
	__finally5:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void exogenesis_fhd_config_SetLabels (ExogenesisFHDConfig* self) {
	g_return_if_fail (self != NULL);
}


static void exogenesis_fhd_config_GetDiskInfo (ExogenesisFHDConfig* self) {
	GtkTreeIter iter = {0};
	g_return_if_fail (self != NULL);
	gtk_list_store_clear (self->priv->_disks);
	{
		GeeArrayList* _tmp0_;
		GeeArrayList* _d_list;
		gint _tmp1_;
		gint _d_size;
		gint _d_index;
		_tmp0_ = _g_object_ref0 (exogenesis_gHDManager->HardDisks);
		_d_list = _tmp0_;
		_tmp1_ = gee_collection_get_size ((GeeCollection*) _d_list);
		_d_size = _tmp1_;
		_d_index = -1;
		while (TRUE) {
			gpointer _tmp2_ = NULL;
			ExogenesisHardDisk* d;
			gboolean _tmp3_ = FALSE;
			gboolean _tmp4_;
			_d_index = _d_index + 1;
			if (!(_d_index < _d_size)) {
				break;
			}
			_tmp2_ = gee_abstract_list_get ((GeeAbstractList*) _d_list, _d_index);
			d = (ExogenesisHardDisk*) _tmp2_;
			_tmp4_ = exogenesis_hard_disk_get_IsOptical (d);
			if (!_tmp4_) {
				const gchar* _tmp5_ = NULL;
				_tmp5_ = exogenesis_hard_disk_get_SerialNumber (d);
				_tmp3_ = _tmp5_ != NULL;
			} else {
				_tmp3_ = FALSE;
			}
			if (_tmp3_) {
				GtkTreeIter _tmp6_ = {0};
				const gchar* _tmp7_ = NULL;
				const gchar* _tmp8_ = NULL;
				gchar* _tmp9_ = NULL;
				gchar* displaytxt;
				const gchar* _tmp10_ = NULL;
				gtk_list_store_append (self->priv->_disks, &_tmp6_);
				iter = _tmp6_;
				_tmp7_ = exogenesis_hard_disk_get_Model (d);
				_tmp8_ = exogenesis_hard_disk_get_CapacityDescription (d);
				_tmp9_ = g_strdup_printf ("%s - %s", _tmp7_, _tmp8_);
				displaytxt = _tmp9_;
				_tmp10_ = exogenesis_hard_disk_get_SerialNumber (d);
				gtk_list_store_set (self->priv->_disks, &iter, 0, displaytxt, 1, _tmp10_, -1, -1);
				_g_free0 (displaytxt);
			}
			_g_object_unref0 (d);
		}
		_g_object_unref0 (_d_list);
	}
	gtk_combo_box_set_active (self->priv->cboHD, 0);
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
	result = _tmp0_ != NULL;
	return result;
}


static void exogenesis_fhd_config_DisplayPartitionInfo (ExogenesisFHDConfig* self, const gchar* hdserial, SegmentedBar* segbar) {
	gint partcount;
	gchar* _tmp0_;
	gchar* label;
	g_return_if_fail (self != NULL);
	g_return_if_fail (hdserial != NULL);
	g_return_if_fail (segbar != NULL);
	partcount = 0;
	_tmp0_ = g_strdup ("");
	label = _tmp0_;
	segmented_bar_RemoveAllSegments (segbar);
	if (hdserial != NULL) {
		{
			GeeArrayList* _tmp1_;
			GeeArrayList* _hd_list;
			gint _tmp2_;
			gint _hd_size;
			gint _hd_index;
			_tmp1_ = _g_object_ref0 (exogenesis_gHDManager->HardDisks);
			_hd_list = _tmp1_;
			_tmp2_ = gee_collection_get_size ((GeeCollection*) _hd_list);
			_hd_size = _tmp2_;
			_hd_index = -1;
			while (TRUE) {
				gpointer _tmp3_ = NULL;
				ExogenesisHardDisk* hd;
				gboolean _tmp4_ = FALSE;
				gboolean _tmp5_ = FALSE;
				const gchar* _tmp6_ = NULL;
				_hd_index = _hd_index + 1;
				if (!(_hd_index < _hd_size)) {
					break;
				}
				_tmp3_ = gee_abstract_list_get ((GeeAbstractList*) _hd_list, _hd_index);
				hd = (ExogenesisHardDisk*) _tmp3_;
				_tmp6_ = exogenesis_hard_disk_get_SerialNumber (hd);
				if (_tmp6_ != NULL) {
					const gchar* _tmp7_ = NULL;
					_tmp7_ = exogenesis_hard_disk_get_SerialNumber (hd);
					_tmp5_ = g_strcmp0 (_tmp7_, hdserial) == 0;
				} else {
					_tmp5_ = FALSE;
				}
				if (_tmp5_) {
					gboolean _tmp8_;
					_tmp8_ = exogenesis_hard_disk_get_IsOptical (hd);
					_tmp4_ = !_tmp8_;
				} else {
					_tmp4_ = FALSE;
				}
				if (_tmp4_) {
					gboolean _tmp37_ = FALSE;
					const gchar* _tmp38_ = NULL;
					exogenesis_hard_disk_SortPartitions (hd);
					{
						GeeIterator* _tmp9_ = NULL;
						GeeIterator* _p_it;
						_tmp9_ = gee_iterable_iterator ((GeeIterable*) hd);
						_p_it = _tmp9_;
						while (TRUE) {
							gboolean _tmp10_;
							gpointer _tmp11_ = NULL;
							ExogenesisPartitionInfo* p;
							gboolean _tmp12_ = FALSE;
							const gchar* _tmp13_ = NULL;
							_tmp10_ = gee_iterator_next (_p_it);
							if (!_tmp10_) {
								break;
							}
							_tmp11_ = gee_iterator_get (_p_it);
							p = (ExogenesisPartitionInfo*) _tmp11_;
							_tmp13_ = exogenesis_partition_info_get_OSType (p);
							if (g_strcmp0 (_tmp13_, "") != 0) {
								const gchar* _tmp14_ = NULL;
								gchar* _tmp15_ = NULL;
								gchar* _tmp16_;
								gboolean _tmp17_;
								_tmp14_ = exogenesis_partition_info_get_PartitionType (p);
								_tmp15_ = g_utf8_strdown (_tmp14_, (gssize) (-1));
								_tmp16_ = _tmp15_;
								_tmp17_ = string_contains (_tmp16_, "extended");
								_tmp12_ = !_tmp17_;
								_g_free0 (_tmp16_);
							} else {
								_tmp12_ = FALSE;
							}
							if (_tmp12_) {
								const gchar* _tmp18_ = NULL;
								const gchar* _tmp19_ = NULL;
								const gchar* _tmp20_ = NULL;
								gchar* _tmp21_ = NULL;
								guint64 _tmp22_;
								guint64 _tmp23_;
								_tmp18_ = exogenesis_partition_info_get_OSType (p);
								_tmp19_ = exogenesis_partition_info_get_CapacityDescription (p);
								_tmp20_ = exogenesis_partition_info_get_FSTabMountPoint (p);
								_tmp21_ = g_strdup_printf ("%s\n%s %s", _tmp18_, _tmp19_, _tmp20_);
								_g_free0 (label);
								label = _tmp21_;
								_tmp22_ = exogenesis_hard_disk_get_Capacity (hd);
								_tmp23_ = exogenesis_partition_info_get_Capacity (p);
								exogenesis_fhd_config_AddToDisk (self, segbar, _tmp22_, _tmp23_, label, partcount);
							} else {
								const gchar* _tmp24_ = NULL;
								gchar* _tmp25_ = NULL;
								gchar* _tmp26_;
								gboolean _tmp27_;
								gboolean _tmp28_;
								_tmp24_ = exogenesis_partition_info_get_PartitionType (p);
								_tmp25_ = g_utf8_strdown (_tmp24_, (gssize) (-1));
								_tmp26_ = _tmp25_;
								_tmp27_ = string_contains (_tmp26_, "extended");
								_tmp28_ = _tmp27_;
								_g_free0 (_tmp26_);
								if (_tmp28_) {
									{
										GeeIterator* _tmp29_ = NULL;
										GeeIterator* _pi_it;
										_tmp29_ = gee_iterable_iterator ((GeeIterable*) p);
										_pi_it = _tmp29_;
										while (TRUE) {
											gboolean _tmp30_;
											gpointer _tmp31_ = NULL;
											ExogenesisPartitionInfo* pi;
											const gchar* _tmp32_ = NULL;
											const gchar* _tmp33_ = NULL;
											gchar* _tmp34_ = NULL;
											guint64 _tmp35_;
											guint64 _tmp36_;
											_tmp30_ = gee_iterator_next (_pi_it);
											if (!_tmp30_) {
												break;
											}
											_tmp31_ = gee_iterator_get (_pi_it);
											pi = (ExogenesisPartitionInfo*) _tmp31_;
											_tmp32_ = exogenesis_partition_info_get_OSType (pi);
											_tmp33_ = exogenesis_partition_info_get_CapacityDescription (pi);
											_tmp34_ = g_strdup_printf ("%s\n%s", _tmp32_, _tmp33_);
											_g_free0 (label);
											label = _tmp34_;
											_tmp35_ = exogenesis_hard_disk_get_Capacity (hd);
											_tmp36_ = exogenesis_partition_info_get_Capacity (pi);
											exogenesis_fhd_config_AddToDisk (self, segbar, _tmp35_, _tmp36_, label, partcount);
											partcount++;
											_g_object_unref0 (pi);
										}
										_g_object_unref0 (_pi_it);
									}
								}
							}
							partcount++;
							_g_object_unref0 (p);
						}
						_g_object_unref0 (_p_it);
					}
					_tmp38_ = exogenesis_hard_disk_get_PreviousOS (hd);
					if (_tmp38_ != NULL) {
						const gchar* _tmp39_ = NULL;
						_tmp39_ = exogenesis_hard_disk_get_PreviousOS (hd);
						_tmp37_ = g_strcmp0 (_tmp39_, "") != 0;
					} else {
						_tmp37_ = FALSE;
					}
					if (_tmp37_) {
						const gchar* _tmp40_ = NULL;
						gchar* _tmp41_ = NULL;
						gchar* _tmp42_;
						_tmp40_ = exogenesis_hard_disk_get_PreviousOS (hd);
						_tmp41_ = g_strdup_printf ("This disk contains a version of %s", _tmp40_);
						_tmp42_ = _tmp41_;
						gtk_label_set_label (self->priv->lblPrevious, _tmp42_);
						_g_free0 (_tmp42_);
					} else {
						gtk_label_set_label (self->priv->lblPrevious, "");
					}
				}
				_g_object_unref0 (hd);
			}
			_g_object_unref0 (_hd_list);
		}
	}
	_g_free0 (label);
}


static gchar* exogenesis_fhd_config_GetSelectedHD (ExogenesisFHDConfig* self) {
	gchar* result = NULL;
	GtkTreeIter iter = {0};
	gchar* di = NULL;
	GValue val = {0};
	GtkTreeIter _tmp0_ = {0};
	GValue _tmp1_ = {0};
	gchar* _tmp2_;
	g_return_val_if_fail (self != NULL, NULL);
	gtk_combo_box_get_active_iter (self->priv->cboHD, &_tmp0_);
	iter = _tmp0_;
	gtk_tree_model_get_value ((GtkTreeModel*) self->priv->_disks, &iter, 1, &_tmp1_);
	G_IS_VALUE (&val) ? (g_value_unset (&val), NULL) : NULL;
	val = _tmp1_;
	_tmp2_ = g_strdup (g_value_get_string (&val));
	_g_free0 (di);
	di = _tmp2_;
	result = di;
	G_IS_VALUE (&val) ? (g_value_unset (&val), NULL) : NULL;
	return result;
}


static void exogenesis_fhd_config_DisplaySuggested (ExogenesisFHDConfig* self, const gchar* hdserial) {
	gchar* title = NULL;
	gchar* displaysize = NULL;
	guint64 partsize = 0ULL;
	ExogenesisHardDisk* _tmp0_ = NULL;
	ExogenesisHardDisk* hd;
	g_return_if_fail (self != NULL);
	g_return_if_fail (hdserial != NULL);
	_tmp0_ = exogenesis_hd_manager_GetHDBySerial (exogenesis_gHDManager, hdserial);
	hd = _tmp0_;
	if (hd != NULL) {
		guint64 _tmp1_;
		guint64 _tmp2_;
		gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		guint64 _tmp5_;
		guint64 _tmp6_;
		guint64 _tmp7_;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		guint64 _tmp10_;
		guint64 _tmp11_;
		guint64 _tmp12_;
		gchar* _tmp13_ = NULL;
		gchar* _tmp14_ = NULL;
		guint64 _tmp15_;
		guint64 _tmp16_;
		guint64 _tmp17_;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
		guint64 _tmp20_;
		segmented_bar_RemoveAllSegments (self->priv->segbarHDA);
		_tmp1_ = exogenesis_hard_disk_get_Capacity (hd);
		_tmp2_ = exogenesis_fhd_config_RootSize (self, _tmp1_);
		partsize = _tmp2_;
		_tmp3_ = exogenesis_general_functions_FormatHDSize (partsize);
		_g_free0 (displaysize);
		displaysize = _tmp3_;
		_tmp4_ = g_strdup_printf ("%s - %s\n%s - %s", "/root", displaysize, "Ext4", "Formatted");
		_g_free0 (title);
		title = _tmp4_;
		_tmp5_ = exogenesis_hard_disk_get_Capacity (hd);
		exogenesis_fhd_config_AddToDisk (self, self->priv->segbarHDA, _tmp5_, partsize, title, 1);
		_tmp6_ = exogenesis_hard_disk_get_Capacity (hd);
		_tmp7_ = exogenesis_fhd_config_HomeSize (self, _tmp6_);
		partsize = _tmp7_;
		_tmp8_ = exogenesis_general_functions_FormatHDSize (partsize);
		_g_free0 (displaysize);
		displaysize = _tmp8_;
		_tmp9_ = g_strdup_printf ("%s - %s\n%s - %s", "/home", displaysize, "Ext4", "Keep Existing");
		_g_free0 (title);
		title = _tmp9_;
		_tmp10_ = exogenesis_hard_disk_get_Capacity (hd);
		exogenesis_fhd_config_AddToDisk (self, self->priv->segbarHDA, _tmp10_, partsize, title, 2);
		_tmp11_ = exogenesis_hard_disk_get_Capacity (hd);
		_tmp12_ = exogenesis_fhd_config_VarSize (self, _tmp11_);
		partsize = _tmp12_;
		_tmp13_ = exogenesis_general_functions_FormatHDSize (partsize);
		_g_free0 (displaysize);
		displaysize = _tmp13_;
		_tmp14_ = g_strdup_printf ("%s - %s\n%s - %s", "/var", displaysize, "Ext4", "Formatted");
		_g_free0 (title);
		title = _tmp14_;
		_tmp15_ = exogenesis_hard_disk_get_Capacity (hd);
		exogenesis_fhd_config_AddToDisk (self, self->priv->segbarHDA, _tmp15_, partsize, title, 3);
		_tmp16_ = exogenesis_hard_disk_get_Capacity (hd);
		_tmp17_ = exogenesis_fhd_config_SwapSize (self, _tmp16_);
		partsize = _tmp17_;
		_tmp18_ = exogenesis_general_functions_FormatHDSize (partsize);
		_g_free0 (displaysize);
		displaysize = _tmp18_;
		_tmp19_ = g_strdup_printf ("%s - %s\n%ss", "swap space", displaysize, "Swap");
		_g_free0 (title);
		title = _tmp19_;
		_tmp20_ = exogenesis_hard_disk_get_Capacity (hd);
		exogenesis_fhd_config_AddToDisk (self, self->priv->segbarHDA, _tmp20_, partsize, title, 4);
	}
	_g_object_unref0 (hd);
	_g_free0 (displaysize);
	_g_free0 (title);
}


static void exogenesis_fhd_config_DisplayInstallHDInfo (ExogenesisFHDConfig* self, const gchar* serial) {
	gint _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (serial != NULL);
	segmented_bar_RemoveAllSegments (self->priv->segbarHDA);
	_tmp0_ = exogenesis_install_data_get_HardDiskCount (exogenesis_gInstallData);
	if (_tmp0_ > 0) {
		{
			GeeIterator* _tmp1_ = NULL;
			GeeIterator* _hd_it;
			_tmp1_ = gee_iterable_iterator ((GeeIterable*) exogenesis_gInstallData);
			_hd_it = _tmp1_;
			while (TRUE) {
				gboolean _tmp2_;
				gpointer _tmp3_ = NULL;
				ExogenesisInstallHardDisk* hd;
				const gchar* _tmp4_ = NULL;
				_tmp2_ = gee_iterator_next (_hd_it);
				if (!_tmp2_) {
					break;
				}
				_tmp3_ = gee_iterator_get (_hd_it);
				hd = (ExogenesisInstallHardDisk*) _tmp3_;
				_tmp4_ = exogenesis_install_hard_disk_get_SerialNumber (hd);
				if (g_strcmp0 (_tmp4_, serial) == 0) {
					guint64 totalused;
					gint pCount;
					ExogenesisHardDisk* _tmp21_ = NULL;
					ExogenesisHardDisk* _tmp22_;
					guint64 _tmp23_;
					guint64 _tmp24_;
					guint64 available;
					gint _tmp25_;
					totalused = (guint64) 0;
					pCount = 1;
					{
						GeeIterator* _tmp5_ = NULL;
						GeeIterator* _ip_it;
						_tmp5_ = gee_iterable_iterator ((GeeIterable*) hd);
						_ip_it = _tmp5_;
						while (TRUE) {
							gboolean _tmp6_;
							gpointer _tmp7_ = NULL;
							ExogenesisInstallPartition* ip;
							guint64 partsize = 0ULL;
							gchar* displaysize = NULL;
							gchar* title = NULL;
							gchar* formattext = NULL;
							const gchar* _tmp8_ = NULL;
							gboolean _tmp9_ = FALSE;
							gboolean _tmp10_;
							gchar* _tmp12_;
							guint64 _tmp13_;
							gchar* _tmp14_ = NULL;
							const gchar* _tmp15_ = NULL;
							const gchar* _tmp16_ = NULL;
							gchar* _tmp17_ = NULL;
							ExogenesisHardDisk* _tmp18_ = NULL;
							ExogenesisHardDisk* _tmp19_;
							guint64 _tmp20_;
							_tmp6_ = gee_iterator_next (_ip_it);
							if (!_tmp6_) {
								break;
							}
							_tmp7_ = gee_iterator_get (_ip_it);
							ip = (ExogenesisInstallPartition*) _tmp7_;
							_tmp10_ = exogenesis_install_partition_get_Format (ip);
							if (_tmp10_) {
								_tmp9_ = TRUE;
							} else {
								gboolean _tmp11_;
								_tmp11_ = exogenesis_install_partition_get_NewPartition (ip);
								_tmp9_ = _tmp11_;
							}
							if (_tmp9_) {
								_tmp8_ = "Formatted";
							} else {
								_tmp8_ = "Keep Existing";
							}
							_tmp12_ = g_strdup (_tmp8_);
							_g_free0 (formattext);
							formattext = _tmp12_;
							_tmp13_ = exogenesis_install_partition_get_ByteSize (ip);
							partsize = _tmp13_;
							_tmp14_ = exogenesis_general_functions_FormatHDSize (partsize);
							_g_free0 (displaysize);
							displaysize = _tmp14_;
							_tmp15_ = exogenesis_install_partition_get_MountPoint (ip);
							_tmp16_ = exogenesis_install_partition_get_Type (ip);
							_tmp17_ = g_strdup_printf ("%s - %s\n%s - %s", _tmp15_, displaysize, _tmp16_, formattext);
							_g_free0 (title);
							title = _tmp17_;
							_tmp18_ = exogenesis_hd_manager_GetHDBySerial (exogenesis_gHDManager, serial);
							_tmp19_ = _tmp18_;
							_tmp20_ = exogenesis_hard_disk_get_Capacity (_tmp19_);
							exogenesis_fhd_config_AddToDisk (self, self->priv->segbarHDA, _tmp20_, partsize, title, pCount);
							_g_object_unref0 (_tmp19_);
							totalused = totalused + partsize;
							pCount++;
							_g_free0 (formattext);
							_g_free0 (title);
							_g_free0 (displaysize);
							_g_object_unref0 (ip);
						}
						_g_object_unref0 (_ip_it);
					}
					_tmp21_ = exogenesis_hd_manager_GetHDBySerial (exogenesis_gHDManager, serial);
					_tmp22_ = _tmp21_;
					_tmp23_ = exogenesis_hard_disk_get_Capacity (_tmp22_);
					_tmp24_ = _tmp23_ - totalused;
					_g_object_unref0 (_tmp22_);
					available = _tmp24_;
					_tmp25_ = segmented_bar_get_Remainder (self->priv->segbarHDA);
					if (_tmp25_ > 0) {
						ExogenesisHardDisk* _tmp26_ = NULL;
						ExogenesisHardDisk* _tmp27_;
						guint64 _tmp28_;
						_tmp26_ = exogenesis_hd_manager_GetHDBySerial (exogenesis_gHDManager, serial);
						_tmp27_ = _tmp26_;
						_tmp28_ = exogenesis_hard_disk_get_Capacity (_tmp27_);
						exogenesis_fhd_config_AddToDisk (self, self->priv->segbarHDA, _tmp28_, available, "UNALLOCATED", 7);
						_g_object_unref0 (_tmp27_);
					}
				}
				_g_object_unref0 (hd);
			}
			_g_object_unref0 (_hd_it);
		}
	}
}


static void exogenesis_fhd_config_PopulateInstallInfo (ExogenesisFHDConfig* self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	ExogenesisHardDisk* _tmp2_ = NULL;
	ExogenesisHardDisk* _tmp3_;
	ExogenesisHardDisk* currentHD;
	ExogenesisInstallHardDisk* _tmp4_ = NULL;
	ExogenesisInstallHardDisk* iHD;
	const gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gboolean _tmp7_;
	g_return_if_fail (self != NULL);
	_tmp0_ = exogenesis_fhd_config_GetSelectedHD (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = exogenesis_hd_manager_GetHDBySerial (exogenesis_gHDManager, _tmp1_);
	_tmp3_ = _tmp2_;
	_g_free0 (_tmp1_);
	currentHD = _tmp3_;
	_tmp4_ = exogenesis_install_hard_disk_new ();
	iHD = _tmp4_;
	_tmp5_ = exogenesis_hard_disk_get_Device (currentHD);
	exogenesis_install_hard_disk_set_DeviceName (iHD, _tmp5_);
	_tmp6_ = exogenesis_hard_disk_get_SerialNumber (currentHD);
	exogenesis_install_hard_disk_set_SerialNumber (iHD, _tmp6_);
	_tmp7_ = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->chkKeepHome);
	if (_tmp7_ == TRUE) {
		{
			GeeIterator* _tmp8_ = NULL;
			GeeIterator* _pi_it;
			_tmp8_ = gee_iterable_iterator ((GeeIterable*) currentHD);
			_pi_it = _tmp8_;
			while (TRUE) {
				gboolean _tmp9_;
				gpointer _tmp10_ = NULL;
				ExogenesisPartitionInfo* pi;
				const gchar* _tmp11_ = NULL;
				gchar* _tmp12_ = NULL;
				gchar* _tmp13_;
				gboolean _tmp14_;
				gboolean _tmp15_;
				_tmp9_ = gee_iterator_next (_pi_it);
				if (!_tmp9_) {
					break;
				}
				_tmp10_ = gee_iterator_get (_pi_it);
				pi = (ExogenesisPartitionInfo*) _tmp10_;
				_tmp11_ = exogenesis_partition_info_get_PartitionType (pi);
				_tmp12_ = g_utf8_strdown (_tmp11_, (gssize) (-1));
				_tmp13_ = _tmp12_;
				_tmp14_ = string_contains (_tmp13_, "extended");
				_tmp15_ = !_tmp14_;
				_g_free0 (_tmp13_);
				if (_tmp15_) {
					ExogenesisInstallPartition* _tmp16_ = NULL;
					ExogenesisInstallPartition* ip;
					guint64 _tmp17_;
					guint64 _tmp18_;
					gchar* _tmp19_ = NULL;
					gchar* _tmp20_;
					gboolean _tmp21_ = FALSE;
					const gchar* _tmp22_ = NULL;
					gboolean _tmp23_;
					const gchar* _tmp24_ = NULL;
					const gchar* _tmp25_ = NULL;
					const gchar* _tmp26_ = NULL;
					const gchar* _tmp27_ = NULL;
					_tmp16_ = exogenesis_install_partition_new ();
					ip = _tmp16_;
					_tmp17_ = exogenesis_partition_info_get_Capacity (pi);
					exogenesis_install_partition_set_ByteSize (ip, _tmp17_);
					_tmp18_ = exogenesis_partition_info_get_Capacity (pi);
					_tmp19_ = exogenesis_general_functions_FormatHDSize (_tmp18_);
					_tmp20_ = _tmp19_;
					exogenesis_install_partition_set_DisplaySize (ip, _tmp20_);
					_g_free0 (_tmp20_);
					_tmp22_ = exogenesis_partition_info_get_MountPoint (pi);
					_tmp23_ = string_contains (_tmp22_, "home");
					if (_tmp23_) {
						_tmp21_ = FALSE;
					} else {
						_tmp21_ = TRUE;
					}
					exogenesis_install_partition_set_Format (ip, _tmp21_);
					_tmp24_ = exogenesis_partition_info_get_MountPoint (pi);
					exogenesis_install_partition_set_MountPoint (ip, _tmp24_);
					_tmp25_ = exogenesis_partition_info_get_OSType (pi);
					exogenesis_install_partition_set_Type (ip, _tmp25_);
					_tmp26_ = exogenesis_partition_info_get_PartitionLabel (pi);
					exogenesis_install_partition_set_Label (ip, _tmp26_);
					_tmp27_ = exogenesis_partition_info_get_Device (pi);
					exogenesis_install_partition_set_Device (ip, _tmp27_);
					exogenesis_install_hard_disk_AddPartition (iHD, ip);
					_g_object_unref0 (ip);
					ip = NULL;
					_g_object_unref0 (ip);
				}
				_g_object_unref0 (pi);
			}
			_g_object_unref0 (_pi_it);
		}
	} else {
		ExogenesisInstallPartition* _tmp28_ = NULL;
		ExogenesisInstallPartition* ip;
		guint64 _tmp29_;
		guint64 _tmp30_;
		guint64 _tmp31_;
		guint64 _tmp32_;
		gchar* _tmp33_ = NULL;
		gchar* _tmp34_;
		_tmp28_ = exogenesis_install_partition_new ();
		ip = _tmp28_;
		_tmp29_ = exogenesis_hard_disk_get_Capacity (currentHD);
		_tmp30_ = exogenesis_fhd_config_RootSize (self, _tmp29_);
		exogenesis_install_partition_set_ByteSize (ip, _tmp30_);
		_tmp31_ = exogenesis_hard_disk_get_Capacity (currentHD);
		_tmp32_ = exogenesis_fhd_config_RootSize (self, _tmp31_);
		_tmp33_ = exogenesis_general_functions_FormatHDSize (_tmp32_);
		_tmp34_ = _tmp33_;
		exogenesis_install_partition_set_DisplaySize (ip, _tmp34_);
		_g_free0 (_tmp34_);
		exogenesis_install_partition_set_Format (ip, TRUE);
		exogenesis_install_partition_set_Label (ip, "");
		_g_object_unref0 (ip);
	}
	exogenesis_install_data_AddInstallDisk (exogenesis_gInstallData, iHD);
	_g_object_unref0 (iHD);
	_g_object_unref0 (currentHD);
}


static void exogenesis_fhd_config_OnDevicesRefreshed (ExogenesisFHDConfig* self) {
	g_return_if_fail (self != NULL);
	exogenesis_fhd_config_GetDiskInfo (self);
}


static void exogenesis_fhd_config_OnDiskManagerError (ExogenesisFHDConfig* self, GError* _error_) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup_printf ("event fired for error - HD Manager Error - %s\n", _error_->message);
	_tmp1_ = _tmp0_;
	exogenesis_general_functions_LogIt (_tmp1_);
	_g_free0 (_tmp1_);
}


static void exogenesis_fhd_config_OnDriveMounted (ExogenesisFHDConfig* self, const gchar* mountpoint) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (mountpoint != NULL);
	exogenesis_previous_os_GetFSTabMountPoints (exogenesis_gPreviousOS);
	exogenesis_fhd_config_OnCboHD_Changed (self);
}


static void exogenesis_fhd_config_OnDriveUnMount (ExogenesisFHDConfig* self) {
	g_return_if_fail (self != NULL);
}


void exogenesis_fhd_config_OnRdoAdvanced_Click (ExogenesisFHDConfig* self) {
	g_return_if_fail (self != NULL);
	gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->rdoUseAll, FALSE);
	gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->chkKeepHome, FALSE);
	gtk_widget_set_sensitive ((GtkWidget*) self->priv->chkKeepHome, FALSE);
}


void exogenesis_fhd_config_OnRdoUseAll_Click (ExogenesisFHDConfig* self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	ExogenesisHardDisk* _tmp2_ = NULL;
	ExogenesisHardDisk* _tmp3_;
	ExogenesisHardDisk* hd;
	gboolean _tmp4_;
	g_return_if_fail (self != NULL);
	gtk_widget_set_sensitive ((GtkWidget*) self->priv->chkKeepHome, TRUE);
	_tmp0_ = exogenesis_fhd_config_GetSelectedHD (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = exogenesis_hd_manager_GetHDBySerial (exogenesis_gHDManager, _tmp1_);
	_tmp3_ = _tmp2_;
	_g_free0 (_tmp1_);
	hd = _tmp3_;
	_tmp4_ = exogenesis_hard_disk_get_HasHomePartition (hd);
	if (_tmp4_) {
		gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->chkKeepHome, TRUE);
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_;
		gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->chkKeepHome, FALSE);
		_tmp5_ = exogenesis_fhd_config_GetSelectedHD (self);
		_tmp6_ = _tmp5_;
		exogenesis_fhd_config_DisplaySuggested (self, _tmp6_);
		_g_free0 (_tmp6_);
	}
	_g_object_unref0 (hd);
}


void exogenesis_fhd_config_OnChkKeepHome_Click (ExogenesisFHDConfig* self) {
	gchar* _tmp0_ = NULL;
	gchar* hdserial;
	gboolean _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = exogenesis_fhd_config_GetSelectedHD (self);
	hdserial = _tmp0_;
	_tmp1_ = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->chkKeepHome);
	if (_tmp1_) {
		exogenesis_fhd_config_DisplayPartitionInfo (self, hdserial, self->priv->segbarHDA);
	} else {
		exogenesis_fhd_config_DisplaySuggested (self, hdserial);
	}
	_g_free0 (hdserial);
}


void exogenesis_fhd_config_OnBtnNext_Click (ExogenesisFHDConfig* self) {
	gint _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	GtkContainer* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = exogenesis_install_data_get_HardDiskCount (exogenesis_gInstallData);
	_tmp1_ = g_strdup_printf ("%i", _tmp0_);
	_tmp2_ = _tmp1_;
	fprintf (stdout, "HARDDISKS USED = %s\n", _tmp2_);
	_g_free0 (_tmp2_);
	_tmp3_ = gtk_widget_get_parent ((GtkWidget*) self);
	exogenesis_main_win_ShowNextWindow (EXOGENESIS_MAIN_WIN (_tmp3_));
}


void exogenesis_fhd_config_OnBtnCreate_Click (ExogenesisFHDConfig* self) {
	ExogenesisInstaller* _tmp0_ = NULL;
	ExogenesisInstaller* inst;
	ExogenesisInstallHardDisk* _tmp1_ = NULL;
	ExogenesisInstallHardDisk* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = exogenesis_installer_new ();
	inst = _tmp0_;
	_tmp1_ = exogenesis_install_data_GetTargetHD (exogenesis_gInstallData, 0);
	_tmp2_ = _tmp1_;
	exogenesis_installer_CreatePartitionsStart (inst, _tmp2_);
	_g_object_unref0 (_tmp2_);
	_exogenesis_installer_unref0 (inst);
}


void exogenesis_fhd_config_OnBtnPrevious_Click (ExogenesisFHDConfig* self) {
	GtkContainer* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_widget_get_parent ((GtkWidget*) self);
	exogenesis_main_win_ShowPreviousWindow (EXOGENESIS_MAIN_WIN (_tmp0_));
}


void exogenesis_fhd_config_OnBtnCancel_Click (ExogenesisFHDConfig* self) {
	GtkContainer* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_widget_get_parent ((GtkWidget*) self);
	exogenesis_main_win_Cancel (EXOGENESIS_MAIN_WIN (_tmp0_));
}


static void exogenesis_fhd_config_AddToDisk (ExogenesisFHDConfig* self, SegmentedBar* bar, guint64 HDSize, guint64 PartitionSize, const gchar* title, gint count) {
	gdouble hdtotal;
	gdouble ptnsize;
	gdouble _tmp0_;
	gint percent;
	guint _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (bar != NULL);
	g_return_if_fail (title != NULL);
	hdtotal = (gdouble) ((HDSize / 1024) / 1024);
	ptnsize = (gdouble) ((PartitionSize / 1024) / 1024);
	_tmp0_ = round ((ptnsize / hdtotal) * 100);
	percent = (gint) _tmp0_;
	segmented_bar_set_SegmentLabelSpacing (bar, 20);
	_tmp1_ = exogenesis_general_functions_BarColour (count);
	segmented_bar_AddSegmentRgb (bar, title, percent, _tmp1_);
}


void exogenesis_fhd_config_OnCboHD_Changed (ExogenesisFHDConfig* self) {
	gchar* _tmp0_ = NULL;
	gchar* hdserial;
	g_return_if_fail (self != NULL);
	_tmp0_ = exogenesis_fhd_config_GetSelectedHD (self);
	hdserial = _tmp0_;
	if (hdserial != NULL) {
		ExogenesisHardDisk* _tmp1_ = NULL;
		ExogenesisHardDisk* _tmp2_;
		gboolean _tmp3_;
		gboolean _tmp4_;
		gboolean _tmp5_;
		exogenesis_fhd_config_DisplayPartitionInfo (self, hdserial, self->priv->segbarHD);
		_tmp1_ = exogenesis_hd_manager_GetHDBySerial (exogenesis_gHDManager, hdserial);
		_tmp2_ = _tmp1_;
		_tmp3_ = exogenesis_hard_disk_get_HasHomePartition (_tmp2_);
		gtk_toggle_button_set_active ((GtkToggleButton*) self->priv->chkKeepHome, _tmp3_);
		_g_object_unref0 (_tmp2_);
		_tmp4_ = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->chkKeepHome);
		gtk_widget_set_sensitive ((GtkWidget*) self->priv->chkKeepHome, _tmp4_);
		_tmp5_ = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->rdoUseAll);
		if (_tmp5_ == TRUE) {
			gboolean _tmp6_;
			_tmp6_ = gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->chkKeepHome);
			if (_tmp6_) {
				exogenesis_fhd_config_DisplayPartitionInfo (self, hdserial, self->priv->segbarHDA);
			} else {
				exogenesis_fhd_config_DisplaySuggested (self, hdserial);
			}
		} else {
			gint _tmp7_;
			_tmp7_ = exogenesis_install_data_get_HardDiskCount (exogenesis_gInstallData);
			if (_tmp7_ > 0) {
				exogenesis_fhd_config_DisplayInstallHDInfo (self, hdserial);
			}
		}
	}
	_g_free0 (hdserial);
}


void exogenesis_fhd_config_OnFxdHDConfig_Realize (ExogenesisFHDConfig* self) {
	g_return_if_fail (self != NULL);
	exogenesis_fhd_config_OnCboHD_Changed (self);
}


void exogenesis_fhd_config_OnDeviceConnected (ExogenesisFHDConfig* self) {
	g_return_if_fail (self != NULL);
	exogenesis_fhd_config_GetDiskInfo (self);
}


static guint64 exogenesis_fhd_config_RootSize (ExogenesisFHDConfig* self, guint64 totalsize) {
	guint64 result = 0ULL;
	g_return_val_if_fail (self != NULL, 0ULL);
	result = (totalsize / 100) * 20;
	return result;
}


static guint64 exogenesis_fhd_config_HomeSize (ExogenesisFHDConfig* self, guint64 totalsize) {
	guint64 result = 0ULL;
	g_return_val_if_fail (self != NULL, 0ULL);
	result = (totalsize / 100) * 66;
	return result;
}


static guint64 exogenesis_fhd_config_VarSize (ExogenesisFHDConfig* self, guint64 totalsize) {
	guint64 result = 0ULL;
	g_return_val_if_fail (self != NULL, 0ULL);
	result = (totalsize / 100) * 10;
	return result;
}


static guint64 exogenesis_fhd_config_SwapSize (ExogenesisFHDConfig* self, guint64 totalsize) {
	guint64 result = 0ULL;
	g_return_val_if_fail (self != NULL, 0ULL);
	result = (totalsize / 100) * 4;
	return result;
}


static void exogenesis_fhd_config_class_init (ExogenesisFHDConfigClass * klass) {
	exogenesis_fhd_config_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ExogenesisFHDConfigPrivate));
	G_OBJECT_CLASS (klass)->finalize = exogenesis_fhd_config_finalize;
}


static void exogenesis_fhd_config_instance_init (ExogenesisFHDConfig * self) {
	GtkListStore* _tmp0_ = NULL;
	self->priv = EXOGENESIS_FHD_CONFIG_GET_PRIVATE (self);
	_tmp0_ = gtk_list_store_new (2, G_TYPE_STRING, G_TYPE_STRING);
	self->priv->_disks = _tmp0_;
}


static void exogenesis_fhd_config_finalize (GObject* obj) {
	ExogenesisFHDConfig * self;
	self = EXOGENESIS_FHD_CONFIG (obj);
	_g_object_unref0 (self->priv->segbox1);
	_g_object_unref0 (self->priv->segbox2);
	_g_object_unref0 (self->priv->btnPrevious);
	_g_object_unref0 (self->priv->btnNext);
	_g_object_unref0 (self->priv->btnCancel);
	_g_object_unref0 (self->priv->rdoAdvanced);
	_g_object_unref0 (self->priv->rdoUseAll);
	_g_object_unref0 (self->priv->chkKeepHome);
	_g_object_unref0 (self->priv->segbarHD);
	_g_object_unref0 (self->priv->segbarHDA);
	_g_object_unref0 (self->priv->fxdHDConfig);
	_g_object_unref0 (self->priv->lblHD);
	_g_object_unref0 (self->priv->cboHD);
	_g_object_unref0 (self->priv->lblPrevious);
	_g_object_unref0 (self->priv->btnCreateTest);
	_g_object_unref0 (self->priv->imgBackground);
	_g_object_unref0 (self->priv->_disks);
	G_OBJECT_CLASS (exogenesis_fhd_config_parent_class)->finalize (obj);
}


GType exogenesis_fhd_config_get_type (void) {
	static volatile gsize exogenesis_fhd_config_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_fhd_config_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisFHDConfigClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_fhd_config_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisFHDConfig), 0, (GInstanceInitFunc) exogenesis_fhd_config_instance_init, NULL };
		GType exogenesis_fhd_config_type_id;
		exogenesis_fhd_config_type_id = g_type_register_static (GTK_TYPE_LAYOUT, "ExogenesisFHDConfig", &g_define_type_info, 0);
		g_once_init_leave (&exogenesis_fhd_config_type_id__volatile, exogenesis_fhd_config_type_id);
	}
	return exogenesis_fhd_config_type_id__volatile;
}



