/* exoLanguageMgr.c generated by valac 0.12.1, the Vala compiler
 * generated from exoLanguageMgr.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <libxml/tree.h>
#include <libxml/parser.h>
#include <gconf/gconf-client.h>
#include <gconf/gconf.h>
#include <libxml/xpath.h>
#include <gee.h>
#include <gobject/gvaluecollector.h>


#define EXOGENESIS_TYPE_LANGUAGE_MANAGER (exogenesis_language_manager_get_type ())
#define EXOGENESIS_LANGUAGE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_LANGUAGE_MANAGER, ExogenesisLanguageManager))
#define EXOGENESIS_LANGUAGE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_LANGUAGE_MANAGER, ExogenesisLanguageManagerClass))
#define EXOGENESIS_IS_LANGUAGE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_LANGUAGE_MANAGER))
#define EXOGENESIS_IS_LANGUAGE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_LANGUAGE_MANAGER))
#define EXOGENESIS_LANGUAGE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_LANGUAGE_MANAGER, ExogenesisLanguageManagerClass))

typedef struct _ExogenesisLanguageManager ExogenesisLanguageManager;
typedef struct _ExogenesisLanguageManagerClass ExogenesisLanguageManagerClass;
typedef struct _ExogenesisLanguageManagerPrivate ExogenesisLanguageManagerPrivate;

#define EXOGENESIS_TYPE_KEYBOARD_MODELS (exogenesis_keyboard_models_get_type ())
#define EXOGENESIS_KEYBOARD_MODELS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_KEYBOARD_MODELS, ExogenesisKeyboardModels))
#define EXOGENESIS_KEYBOARD_MODELS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_KEYBOARD_MODELS, ExogenesisKeyboardModelsClass))
#define EXOGENESIS_IS_KEYBOARD_MODELS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_KEYBOARD_MODELS))
#define EXOGENESIS_IS_KEYBOARD_MODELS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_KEYBOARD_MODELS))
#define EXOGENESIS_KEYBOARD_MODELS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_KEYBOARD_MODELS, ExogenesisKeyboardModelsClass))

typedef struct _ExogenesisKeyboardModels ExogenesisKeyboardModels;
typedef struct _ExogenesisKeyboardModelsClass ExogenesisKeyboardModelsClass;

#define EXOGENESIS_TYPE_KB_COUNTRIES (exogenesis_kb_countries_get_type ())
#define EXOGENESIS_KB_COUNTRIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_KB_COUNTRIES, ExogenesisKbCountries))
#define EXOGENESIS_KB_COUNTRIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_KB_COUNTRIES, ExogenesisKbCountriesClass))
#define EXOGENESIS_IS_KB_COUNTRIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_KB_COUNTRIES))
#define EXOGENESIS_IS_KB_COUNTRIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_KB_COUNTRIES))
#define EXOGENESIS_KB_COUNTRIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_KB_COUNTRIES, ExogenesisKbCountriesClass))

typedef struct _ExogenesisKbCountries ExogenesisKbCountries;
typedef struct _ExogenesisKbCountriesClass ExogenesisKbCountriesClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _gconf_engine_unref0(var) ((var == NULL) ? NULL : (var = (gconf_engine_unref (var), NULL)))
#define __g_slist_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_slist_free__g_free0_ (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define EXOGENESIS_TYPE_LANGUAGE (exogenesis_language_get_type ())
#define EXOGENESIS_LANGUAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_LANGUAGE, ExogenesisLanguage))
#define EXOGENESIS_LANGUAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_LANGUAGE, ExogenesisLanguageClass))
#define EXOGENESIS_IS_LANGUAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_LANGUAGE))
#define EXOGENESIS_IS_LANGUAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_LANGUAGE))
#define EXOGENESIS_LANGUAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_LANGUAGE, ExogenesisLanguageClass))

typedef struct _ExogenesisLanguage ExogenesisLanguage;
typedef struct _ExogenesisLanguageClass ExogenesisLanguageClass;

#define EXOGENESIS_TYPE_GENERAL_FUNCTIONS (exogenesis_general_functions_get_type ())
#define EXOGENESIS_GENERAL_FUNCTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_GENERAL_FUNCTIONS, ExogenesisGeneralFunctions))
#define EXOGENESIS_GENERAL_FUNCTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_GENERAL_FUNCTIONS, ExogenesisGeneralFunctionsClass))
#define EXOGENESIS_IS_GENERAL_FUNCTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_GENERAL_FUNCTIONS))
#define EXOGENESIS_IS_GENERAL_FUNCTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_GENERAL_FUNCTIONS))
#define EXOGENESIS_GENERAL_FUNCTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_GENERAL_FUNCTIONS, ExogenesisGeneralFunctionsClass))

typedef struct _ExogenesisGeneralFunctions ExogenesisGeneralFunctions;
typedef struct _ExogenesisGeneralFunctionsClass ExogenesisGeneralFunctionsClass;
#define _exogenesis_language_unref0(var) ((var == NULL) ? NULL : (var = (exogenesis_language_unref (var), NULL)))
#define __g_list_free__exogenesis_language_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__exogenesis_language_unref0_ (var), NULL)))

#define EXOGENESIS_TYPE_KB_MODEL (exogenesis_kb_model_get_type ())
#define EXOGENESIS_KB_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_KB_MODEL, ExogenesisKbModel))
#define EXOGENESIS_KB_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_KB_MODEL, ExogenesisKbModelClass))
#define EXOGENESIS_IS_KB_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_KB_MODEL))
#define EXOGENESIS_IS_KB_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_KB_MODEL))
#define EXOGENESIS_KB_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_KB_MODEL, ExogenesisKbModelClass))

typedef struct _ExogenesisKbModel ExogenesisKbModel;
typedef struct _ExogenesisKbModelClass ExogenesisKbModelClass;
#define _exogenesis_kb_model_unref0(var) ((var == NULL) ? NULL : (var = (exogenesis_kb_model_unref (var), NULL)))

#define EXOGENESIS_TYPE_KB_COUNTRY (exogenesis_kb_country_get_type ())
#define EXOGENESIS_KB_COUNTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_KB_COUNTRY, ExogenesisKbCountry))
#define EXOGENESIS_KB_COUNTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_KB_COUNTRY, ExogenesisKbCountryClass))
#define EXOGENESIS_IS_KB_COUNTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_KB_COUNTRY))
#define EXOGENESIS_IS_KB_COUNTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_KB_COUNTRY))
#define EXOGENESIS_KB_COUNTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_KB_COUNTRY, ExogenesisKbCountryClass))

typedef struct _ExogenesisKbCountry ExogenesisKbCountry;
typedef struct _ExogenesisKbCountryClass ExogenesisKbCountryClass;

#define EXOGENESIS_TYPE_KB_VARIANT (exogenesis_kb_variant_get_type ())
#define EXOGENESIS_KB_VARIANT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_KB_VARIANT, ExogenesisKbVariant))
#define EXOGENESIS_KB_VARIANT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_KB_VARIANT, ExogenesisKbVariantClass))
#define EXOGENESIS_IS_KB_VARIANT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_KB_VARIANT))
#define EXOGENESIS_IS_KB_VARIANT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_KB_VARIANT))
#define EXOGENESIS_KB_VARIANT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_KB_VARIANT, ExogenesisKbVariantClass))

typedef struct _ExogenesisKbVariant ExogenesisKbVariant;
typedef struct _ExogenesisKbVariantClass ExogenesisKbVariantClass;
typedef struct _ExogenesisParamSpecLanguageManager ExogenesisParamSpecLanguageManager;
typedef struct _ExogenesisLanguagePrivate ExogenesisLanguagePrivate;
typedef struct _ExogenesisParamSpecLanguage ExogenesisParamSpecLanguage;
typedef struct _ExogenesisKeyboardModelsPrivate ExogenesisKeyboardModelsPrivate;
typedef struct _ExogenesisKbModelPrivate ExogenesisKbModelPrivate;
typedef struct _ExogenesisParamSpecKbModel ExogenesisParamSpecKbModel;
typedef struct _ExogenesisKbCountriesPrivate ExogenesisKbCountriesPrivate;
typedef struct _ExogenesisKbCountryPrivate ExogenesisKbCountryPrivate;
typedef struct _ExogenesisKbVariantPrivate ExogenesisKbVariantPrivate;

struct _ExogenesisLanguageManager {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ExogenesisLanguageManagerPrivate * priv;
};

struct _ExogenesisLanguageManagerClass {
	GTypeClass parent_class;
	void (*finalize) (ExogenesisLanguageManager *self);
};

struct _ExogenesisLanguageManagerPrivate {
	gchar* _curLocale;
	xmlDoc* _xKbLayoutDoc;
	ExogenesisKeyboardModels* _kbrds;
	ExogenesisKbCountries* _countries;
	GConfClient* _gc;
	GConfEngine* _eng;
	GSList* _CurrentKbConf;
	gchar* _GCKbKey;
};

typedef enum  {
	EXOGENESIS_XML_ERROR_FILE_NOT_FOUND,
	EXOGENESIS_XML_ERROR_XML_DOCUMENT_EMPTY
} ExogenesisXmlError;
#define EXOGENESIS_XML_ERROR exogenesis_xml_error_quark ()
struct _ExogenesisParamSpecLanguageManager {
	GParamSpec parent_instance;
};

struct _ExogenesisLanguage {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ExogenesisLanguagePrivate * priv;
};

struct _ExogenesisLanguageClass {
	GTypeClass parent_class;
	void (*finalize) (ExogenesisLanguage *self);
};

struct _ExogenesisLanguagePrivate {
	gint _Order;
	gchar* _Code;
	gchar* _Country;
	gchar* _CountryNative;
};

struct _ExogenesisParamSpecLanguage {
	GParamSpec parent_instance;
};

struct _ExogenesisKeyboardModels {
	GObject parent_instance;
	ExogenesisKeyboardModelsPrivate * priv;
	GeeArrayList* _kbrds;
};

struct _ExogenesisKeyboardModelsClass {
	GObjectClass parent_class;
};

struct _ExogenesisKeyboardModelsPrivate {
	glong _count;
};

struct _ExogenesisKbModel {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ExogenesisKbModelPrivate * priv;
};

struct _ExogenesisKbModelClass {
	GTypeClass parent_class;
	void (*finalize) (ExogenesisKbModel *self);
};

struct _ExogenesisKbModelPrivate {
	gchar* _Name;
	gchar* _Description;
	gchar* _Vendor;
};

struct _ExogenesisParamSpecKbModel {
	GParamSpec parent_instance;
};

struct _ExogenesisKbCountries {
	GObject parent_instance;
	ExogenesisKbCountriesPrivate * priv;
	GeeArrayList* _countries;
};

struct _ExogenesisKbCountriesClass {
	GObjectClass parent_class;
};

struct _ExogenesisKbCountry {
	GObject parent_instance;
	ExogenesisKbCountryPrivate * priv;
	GeeArrayList* _variant;
	GeeArrayList* _isocode;
};

struct _ExogenesisKbCountryClass {
	GObjectClass parent_class;
};

struct _ExogenesisKbCountryPrivate {
	gchar* _Name;
	gchar* _ShortDescription;
	gchar* _Description;
	gint _variantcount;
};

struct _ExogenesisKbVariant {
	GObject parent_instance;
	ExogenesisKbVariantPrivate * priv;
	GeeArrayList* _languageList;
};

struct _ExogenesisKbVariantClass {
	GObjectClass parent_class;
};

struct _ExogenesisKbVariantPrivate {
	gchar* _Name;
	gchar* _Description;
};


static gpointer exogenesis_language_manager_parent_class = NULL;
extern ExogenesisGeneralFunctions* exogenesis_gGenFunc;
extern gchar* exogenesis_AppPath;
static gpointer exogenesis_language_parent_class = NULL;
static gpointer exogenesis_keyboard_models_parent_class = NULL;
static GeeIterableIface* exogenesis_keyboard_models_gee_iterable_parent_iface = NULL;
static gpointer exogenesis_kb_model_parent_class = NULL;
static gpointer exogenesis_kb_countries_parent_class = NULL;
static GeeIterableIface* exogenesis_kb_countries_gee_iterable_parent_iface = NULL;
static gpointer exogenesis_kb_country_parent_class = NULL;
static GeeComparableIface* exogenesis_kb_country_gee_comparable_parent_iface = NULL;
static GeeIterableIface* exogenesis_kb_country_gee_iterable_parent_iface = NULL;
static gpointer exogenesis_kb_variant_parent_class = NULL;
static GeeIterableIface* exogenesis_kb_variant_gee_iterable_parent_iface = NULL;

gpointer exogenesis_language_manager_ref (gpointer instance);
void exogenesis_language_manager_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_language_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_language_manager (GValue* value, gpointer v_object);
void exogenesis_value_take_language_manager (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_language_manager (const GValue* value);
GType exogenesis_language_manager_get_type (void) G_GNUC_CONST;
GType exogenesis_keyboard_models_get_type (void) G_GNUC_CONST;
GType exogenesis_kb_countries_get_type (void) G_GNUC_CONST;
#define EXOGENESIS_LANGUAGE_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXOGENESIS_TYPE_LANGUAGE_MANAGER, ExogenesisLanguageManagerPrivate))
enum  {
	EXOGENESIS_LANGUAGE_MANAGER_DUMMY_PROPERTY
};
ExogenesisKeyboardModels* exogenesis_keyboard_models_new (void);
ExogenesisKeyboardModels* exogenesis_keyboard_models_construct (GType object_type);
ExogenesisKbCountries* exogenesis_kb_countries_new (void);
ExogenesisKbCountries* exogenesis_kb_countries_construct (GType object_type);
static void _g_free0_ (gpointer var);
static void _g_slist_free__g_free0_ (GSList* self);
ExogenesisLanguageManager* exogenesis_language_manager_new (void);
ExogenesisLanguageManager* exogenesis_language_manager_construct (GType object_type);
void exogenesis_language_manager_GetKbLayouts (ExogenesisLanguageManager* self, const gchar* xorgfile);
static void exogenesis_language_manager_BackupCurrentKbSetting (ExogenesisLanguageManager* self);
static void exogenesis_language_manager_AddGconfListener (ExogenesisLanguageManager* self);
gchar* exogenesis_language_manager_GetCurrentCountry (ExogenesisLanguageManager* self);
static void exogenesis_language_manager_GConfCallBack (ExogenesisLanguageManager* self, GConfClient* gc, guint cxnid, GConfEntry* entry);
static void _exogenesis_language_manager_GConfCallBack_gconf_client_notify_func (GConfClient* client, guint cnxn_id, GConfEntry* entry, gpointer self);
void exogenesis_language_manager_GConfSetLayout (ExogenesisLanguageManager* self, const gchar* layout, const gchar* variant);
void exogenesis_general_functions_LogIt (const gchar* Message);
gpointer exogenesis_language_ref (gpointer instance);
void exogenesis_language_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_language (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_language (GValue* value, gpointer v_object);
void exogenesis_value_take_language (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_language (const GValue* value);
GType exogenesis_language_get_type (void) G_GNUC_CONST;
GList* exogenesis_language_manager_AvailableLanguages (ExogenesisLanguageManager* self);
gpointer exogenesis_general_functions_ref (gpointer instance);
void exogenesis_general_functions_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_general_functions (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_general_functions (GValue* value, gpointer v_object);
void exogenesis_value_take_general_functions (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_general_functions (const GValue* value);
GType exogenesis_general_functions_get_type (void) G_GNUC_CONST;
gchar* exogenesis_general_functions_ReadTextFile (ExogenesisGeneralFunctions* self, const gchar* filename);
ExogenesisLanguage* exogenesis_language_new (void);
ExogenesisLanguage* exogenesis_language_construct (GType object_type);
void exogenesis_language_set_Order (ExogenesisLanguage* self, gint value);
void exogenesis_language_set_Code (ExogenesisLanguage* self, const gchar* value);
void exogenesis_language_set_Country (ExogenesisLanguage* self, const gchar* value);
void exogenesis_language_set_CountryNative (ExogenesisLanguage* self, const gchar* value);
static void _exogenesis_language_unref0_ (gpointer var);
static void _g_list_free__exogenesis_language_unref0_ (GList* self);
static void exogenesis_language_manager_PopulateKbModels (ExogenesisLanguageManager* self);
void exogenesis_language_manager_PopulateCountries (ExogenesisLanguageManager* self);
GQuark exogenesis_xml_error_quark (void);
ExogenesisKbModel* exogenesis_kb_model_new (void);
ExogenesisKbModel* exogenesis_kb_model_construct (GType object_type);
gpointer exogenesis_kb_model_ref (gpointer instance);
void exogenesis_kb_model_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_kb_model (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_kb_model (GValue* value, gpointer v_object);
void exogenesis_value_take_kb_model (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_kb_model (const GValue* value);
GType exogenesis_kb_model_get_type (void) G_GNUC_CONST;
void exogenesis_kb_model_set_Name (ExogenesisKbModel* self, const gchar* value);
void exogenesis_kb_model_set_Description (ExogenesisKbModel* self, const gchar* value);
void exogenesis_kb_model_set_Vendor (ExogenesisKbModel* self, const gchar* value);
void exogenesis_keyboard_models_AddKeyboard (ExogenesisKeyboardModels* self, ExogenesisKbModel* m);
ExogenesisKbCountry* exogenesis_kb_country_new (void);
ExogenesisKbCountry* exogenesis_kb_country_construct (GType object_type);
GType exogenesis_kb_country_get_type (void) G_GNUC_CONST;
static void exogenesis_language_manager_PopulateCountry (ExogenesisLanguageManager* self, xmlNode* nd, ExogenesisKbCountry* country);
static void exogenesis_language_manager_PopulateVariant (ExogenesisLanguageManager* self, xmlNode* nd, ExogenesisKbCountry* country);
void exogenesis_kb_countries_AddCountry (ExogenesisKbCountries* self, ExogenesisKbCountry* country);
void exogenesis_kb_country_set_Name (ExogenesisKbCountry* self, const gchar* value);
void exogenesis_kb_country_set_ShortDescription (ExogenesisKbCountry* self, const gchar* value);
void exogenesis_kb_country_set_Description (ExogenesisKbCountry* self, const gchar* value);
ExogenesisKbVariant* exogenesis_kb_variant_new (void);
ExogenesisKbVariant* exogenesis_kb_variant_construct (GType object_type);
GType exogenesis_kb_variant_get_type (void) G_GNUC_CONST;
void exogenesis_kb_variant_set_Name (ExogenesisKbVariant* self, const gchar* value);
const gchar* exogenesis_kb_country_get_Description (ExogenesisKbCountry* self);
void exogenesis_kb_variant_set_Description (ExogenesisKbVariant* self, const gchar* value);
void exogenesis_kb_country_AddVariant (ExogenesisKbCountry* self, ExogenesisKbVariant* kbvariant);
ExogenesisKbCountries* exogenesis_language_manager_get_Countries (ExogenesisLanguageManager* self);
ExogenesisKeyboardModels* exogenesis_language_manager_get_Keyboards (ExogenesisLanguageManager* self);
const gchar* exogenesis_language_manager_get_CurrentLocale (ExogenesisLanguageManager* self);
void exogenesis_language_manager_set_CurrentLocale (ExogenesisLanguageManager* self, const gchar* value);
static void exogenesis_language_manager_finalize (ExogenesisLanguageManager* obj);
#define EXOGENESIS_LANGUAGE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXOGENESIS_TYPE_LANGUAGE, ExogenesisLanguagePrivate))
enum  {
	EXOGENESIS_LANGUAGE_DUMMY_PROPERTY
};
gint exogenesis_language_get_Order (ExogenesisLanguage* self);
const gchar* exogenesis_language_get_Code (ExogenesisLanguage* self);
const gchar* exogenesis_language_get_Country (ExogenesisLanguage* self);
const gchar* exogenesis_language_get_CountryNative (ExogenesisLanguage* self);
static void exogenesis_language_finalize (ExogenesisLanguage* obj);
#define EXOGENESIS_KEYBOARD_MODELS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXOGENESIS_TYPE_KEYBOARD_MODELS, ExogenesisKeyboardModelsPrivate))
enum  {
	EXOGENESIS_KEYBOARD_MODELS_DUMMY_PROPERTY,
	EXOGENESIS_KEYBOARD_MODELS_ELEMENT_TYPE,
	EXOGENESIS_KEYBOARD_MODELS_COUNT
};
void exogenesis_keyboard_models_KeyboardModels (ExogenesisKeyboardModels* self);
void exogenesis_keyboard_models_Sort (ExogenesisKeyboardModels* self);
static GeeIterator* exogenesis_keyboard_models_real_iterator (GeeIterable* base);
glong exogenesis_keyboard_models_get_Count (ExogenesisKeyboardModels* self);
static void exogenesis_keyboard_models_finalize (GObject* obj);
static void _vala_exogenesis_keyboard_models_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
#define EXOGENESIS_KB_MODEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXOGENESIS_TYPE_KB_MODEL, ExogenesisKbModelPrivate))
enum  {
	EXOGENESIS_KB_MODEL_DUMMY_PROPERTY
};
ExogenesisKbModel* exogenesis_kb_model_new_WithValues (const gchar* name, const gchar* description, const gchar* vendor);
ExogenesisKbModel* exogenesis_kb_model_construct_WithValues (GType object_type, const gchar* name, const gchar* description, const gchar* vendor);
const gchar* exogenesis_kb_model_get_Name (ExogenesisKbModel* self);
const gchar* exogenesis_kb_model_get_Description (ExogenesisKbModel* self);
const gchar* exogenesis_kb_model_get_Vendor (ExogenesisKbModel* self);
static void exogenesis_kb_model_finalize (ExogenesisKbModel* obj);
enum  {
	EXOGENESIS_KB_COUNTRIES_DUMMY_PROPERTY,
	EXOGENESIS_KB_COUNTRIES_ELEMENT_TYPE
};
void exogenesis_kb_countries_KbCountries (ExogenesisKbCountries* self);
void exogenesis_kb_countries_Sort (ExogenesisKbCountries* self);
static GeeIterator* exogenesis_kb_countries_real_iterator (GeeIterable* base);
static void exogenesis_kb_countries_finalize (GObject* obj);
static void _vala_exogenesis_kb_countries_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
#define EXOGENESIS_KB_COUNTRY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXOGENESIS_TYPE_KB_COUNTRY, ExogenesisKbCountryPrivate))
enum  {
	EXOGENESIS_KB_COUNTRY_DUMMY_PROPERTY,
	EXOGENESIS_KB_COUNTRY_NAME,
	EXOGENESIS_KB_COUNTRY_SHORT_DESCRIPTION,
	EXOGENESIS_KB_COUNTRY_DESCRIPTION,
	EXOGENESIS_KB_COUNTRY_VARIANT_COUNT,
	EXOGENESIS_KB_COUNTRY_ELEMENT_TYPE
};
void exogenesis_kb_country_KbCountry (ExogenesisKbCountry* self);
void exogenesis_kb_country_AddLanguageISO (ExogenesisKbCountry* self, const gchar* iso);
static GeeIterator* exogenesis_kb_country_real_iterator (GeeIterable* base);
static gint exogenesis_kb_country_real_compare_to (GeeComparable* base, ExogenesisKbCountry* comp);
const gchar* exogenesis_kb_country_get_Name (ExogenesisKbCountry* self);
const gchar* exogenesis_kb_country_get_ShortDescription (ExogenesisKbCountry* self);
gint exogenesis_kb_country_get_VariantCount (ExogenesisKbCountry* self);
static void exogenesis_kb_country_finalize (GObject* obj);
static void _vala_exogenesis_kb_country_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_exogenesis_kb_country_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
#define EXOGENESIS_KB_VARIANT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EXOGENESIS_TYPE_KB_VARIANT, ExogenesisKbVariantPrivate))
enum  {
	EXOGENESIS_KB_VARIANT_DUMMY_PROPERTY,
	EXOGENESIS_KB_VARIANT_NAME,
	EXOGENESIS_KB_VARIANT_DESCRIPTION,
	EXOGENESIS_KB_VARIANT_ELEMENT_TYPE
};
void exogenesis_kb_variant_KbVariant (ExogenesisKbVariant* self);
void exogenesis_kb_variant_AddLanguage (ExogenesisKbVariant* self, const gchar* lang);
static GeeIterator* exogenesis_kb_variant_real_iterator (GeeIterable* base);
const gchar* exogenesis_kb_variant_get_Name (ExogenesisKbVariant* self);
const gchar* exogenesis_kb_variant_get_Description (ExogenesisKbVariant* self);
static void exogenesis_kb_variant_finalize (GObject* obj);
static void _vala_exogenesis_kb_variant_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_exogenesis_kb_variant_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static void _g_slist_free__g_free0_ (GSList* self) {
	g_slist_foreach (self, (GFunc) _g_free0_, NULL);
	g_slist_free (self);
}


ExogenesisLanguageManager* exogenesis_language_manager_construct (GType object_type) {
	ExogenesisLanguageManager* self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	self = (ExogenesisLanguageManager*) g_type_create_instance (object_type);
	_tmp0_ = g_getenv ("LANG");
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_curLocale);
	self->priv->_curLocale = _tmp1_;
	exogenesis_language_manager_GetKbLayouts (self, "/usr/share/X11/xkb/rules/xorg.xml");
	exogenesis_language_manager_BackupCurrentKbSetting (self);
	exogenesis_language_manager_AddGconfListener (self);
	return self;
}


ExogenesisLanguageManager* exogenesis_language_manager_new (void) {
	return exogenesis_language_manager_construct (EXOGENESIS_TYPE_LANGUAGE_MANAGER);
}


gchar* exogenesis_language_manager_GetCurrentCountry (ExogenesisLanguageManager* self) {
	gchar* result = NULL;
	gchar* _tmp0_;
	gchar* ret;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup ("");
	ret = _tmp0_;
	{
		GSList* s_collection;
		GSList* s_it;
		s_collection = self->priv->_CurrentKbConf;
		for (s_it = s_collection; s_it != NULL; s_it = s_it->next) {
			gchar* _tmp1_;
			gchar* s;
			_tmp1_ = g_strdup ((const gchar*) s_it->data);
			s = _tmp1_;
			{
				gchar* _tmp2_;
				_tmp2_ = g_strdup (s);
				_g_free0 (ret);
				ret = _tmp2_;
				_g_free0 (s);
				break;
			}
		}
	}
	result = ret;
	return result;
}


static void _exogenesis_language_manager_GConfCallBack_gconf_client_notify_func (GConfClient* client, guint cnxn_id, GConfEntry* entry, gpointer self) {
	exogenesis_language_manager_GConfCallBack (self, client, cnxn_id, entry);
}


static void exogenesis_language_manager_AddGconfListener (ExogenesisLanguageManager* self) {
	gchar* _tmp0_;
	gchar* listening_dir;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("/desktop/gnome/peripherals/keyboard/kbd");
	listening_dir = _tmp0_;
	gconf_client_add_dir (self->priv->_gc, listening_dir, GCONF_CLIENT_PRELOAD_ONELEVEL, &_inner_error_);
	if (_inner_error_ != NULL) {
		_g_free0 (listening_dir);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	gconf_client_notify_add (self->priv->_gc, self->priv->_GCKbKey, _exogenesis_language_manager_GConfCallBack_gconf_client_notify_func, exogenesis_language_manager_ref (self), exogenesis_language_manager_unref, &_inner_error_);
	if (_inner_error_ != NULL) {
		_g_free0 (listening_dir);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_g_free0 (listening_dir);
}


static void exogenesis_language_manager_GConfCallBack (ExogenesisLanguageManager* self, GConfClient* gc, guint cxnid, GConfEntry* entry) {
	GSList* _tmp0_ = NULL;
	GSList* newList;
	gchar* _tmp1_;
	gchar* s;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (gc != NULL);
	g_return_if_fail (entry != NULL);
	_tmp0_ = gconf_client_get_list (self->priv->_gc, entry->key, GCONF_VALUE_STRING, &_inner_error_);
	newList = _tmp0_;
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp1_ = g_strdup ("");
	s = _tmp1_;
	{
		GSList* st_collection;
		GSList* st_it;
		st_collection = newList;
		for (st_it = st_collection; st_it != NULL; st_it = st_it->next) {
			gchar* _tmp2_;
			gchar* st;
			_tmp2_ = g_strdup ((const gchar*) st_it->data);
			st = _tmp2_;
			{
				gchar* _tmp3_;
				_tmp3_ = g_strconcat (s, st, NULL);
				_g_free0 (s);
				s = _tmp3_;
				_g_free0 (st);
			}
		}
	}
	_g_free0 (s);
	__g_slist_free__g_free0_0 (newList);
}


void exogenesis_language_manager_GConfSetLayout (ExogenesisLanguageManager* self, const gchar* layout, const gchar* variant) {
	gchar* entry = NULL;
	GSList* nu;
	gboolean _tmp0_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (layout != NULL);
	g_return_if_fail (variant != NULL);
	nu = NULL;
	if (layout != NULL) {
		_tmp0_ = g_strcmp0 (layout, "") != 0;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		gchar* _tmp3_;
		if (g_strcmp0 (variant, "") != 0) {
			gchar* _tmp1_ = NULL;
			_tmp1_ = g_strdup_printf ("%s\t%s", layout, variant);
			_g_free0 (entry);
			entry = _tmp1_;
		} else {
			gchar* _tmp2_;
			_tmp2_ = g_strdup (layout);
			_g_free0 (entry);
			entry = _tmp2_;
		}
		_tmp3_ = g_strdup (entry);
		nu = g_slist_prepend (nu, _tmp3_);
		gconf_client_set_list (self->priv->_gc, self->priv->_GCKbKey, GCONF_VALUE_STRING, nu, &_inner_error_);
		if (_inner_error_ != NULL) {
			__g_slist_free__g_free0_0 (nu);
			_g_free0 (entry);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		__g_slist_free__g_free0_0 (nu);
		nu = NULL;
		g_signal_emit_by_name (self, "on-gconf-layout-changed");
	}
	__g_slist_free__g_free0_0 (nu);
	_g_free0 (entry);
}


static void exogenesis_language_manager_BackupCurrentKbSetting (ExogenesisLanguageManager* self) {
	GSList* _tmp0_ = NULL;
	GSList* _tmp1_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = gconf_client_get_list (self->priv->_gc, self->priv->_GCKbKey, GCONF_VALUE_STRING, &_inner_error_);
	_tmp1_ = _tmp0_;
	if (_inner_error_ != NULL) {
		goto __catch18_g_error;
	}
	__g_slist_free__g_free0_0 (self->priv->_CurrentKbConf);
	self->priv->_CurrentKbConf = _tmp1_;
	goto __finally18;
	__catch18_g_error:
	{
		GError * err;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = g_strdup_printf ("Can't get current keyboard configs! - %s\n", err->message);
		_tmp3_ = _tmp2_;
		exogenesis_general_functions_LogIt (_tmp3_);
		_g_free0 (_tmp3_);
		_g_error_free0 (err);
	}
	__finally18:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static gpointer _exogenesis_language_ref0 (gpointer self) {
	return self ? exogenesis_language_ref (self) : NULL;
}


static void _exogenesis_language_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (exogenesis_language_unref (var), NULL));
}


static void _g_list_free__exogenesis_language_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _exogenesis_language_unref0_, NULL);
	g_list_free (self);
}


GList* exogenesis_language_manager_AvailableLanguages (ExogenesisLanguageManager* self) {
	GList* result = NULL;
	GList* langs;
	gchar* filedata = NULL;
	gchar* ot = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar** _tmp3_;
	gchar** _tmp4_ = NULL;
	gchar** lines;
	gint lines_length1;
	gint _lines_size_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	langs = NULL;
	_tmp0_ = g_strdup_printf ("%s/locale/languagelist.data", exogenesis_AppPath);
	_tmp1_ = _tmp0_;
	_tmp2_ = exogenesis_general_functions_ReadTextFile (exogenesis_gGenFunc, _tmp1_);
	_g_free0 (filedata);
	filedata = _tmp2_;
	_g_free0 (_tmp1_);
	_tmp4_ = _tmp3_ = g_strsplit (filedata, "\n", 0);
	lines = _tmp4_;
	lines_length1 = _vala_array_length (_tmp3_);
	_lines_size_ = _vala_array_length (_tmp3_);
	{
		gchar** line_collection;
		int line_collection_length1;
		int line_it;
		line_collection = lines;
		line_collection_length1 = lines_length1;
		for (line_it = 0; line_it < lines_length1; line_it = line_it + 1) {
			gchar* _tmp5_;
			gchar* line;
			_tmp5_ = g_strdup (line_collection[line_it]);
			line = _tmp5_;
			{
				gchar** _tmp6_;
				gchar** _tmp7_ = NULL;
				gchar** lang;
				gint lang_length1;
				gint _lang_size_;
				_tmp7_ = _tmp6_ = g_strsplit (line, ":", 0);
				lang = _tmp7_;
				lang_length1 = _vala_array_length (_tmp6_);
				_lang_size_ = _vala_array_length (_tmp6_);
				if (lang_length1 == 4) {
					ExogenesisLanguage* _tmp8_ = NULL;
					ExogenesisLanguage* language;
					gint _tmp9_;
					ExogenesisLanguage* _tmp10_;
					_tmp8_ = exogenesis_language_new ();
					language = _tmp8_;
					_tmp9_ = atoi (lang[0]);
					exogenesis_language_set_Order (language, _tmp9_);
					exogenesis_language_set_Code (language, (const gchar*) lang[1]);
					exogenesis_language_set_Country (language, (const gchar*) lang[2]);
					exogenesis_language_set_CountryNative (language, (const gchar*) lang[3]);
					_tmp10_ = _exogenesis_language_ref0 (language);
					langs = g_list_append (langs, _tmp10_);
					_exogenesis_language_unref0 (language);
				}
				lang = (_vala_array_free (lang, lang_length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (line);
			}
		}
	}
	result = langs;
	lines = (_vala_array_free (lines, lines_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (ot);
	_g_free0 (filedata);
	return result;
	lines = (_vala_array_free (lines, lines_length1, (GDestroyNotify) g_free), NULL);
	goto __finally19;
	__catch19_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		exogenesis_general_functions_LogIt (e->message);
		_g_error_free0 (e);
	}
	__finally19:
	_g_free0 (ot);
	_g_free0 (filedata);
	__g_list_free__exogenesis_language_unref0_0 (langs);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return NULL;
	result = NULL;
	_g_free0 (ot);
	_g_free0 (filedata);
	__g_list_free__exogenesis_language_unref0_0 (langs);
	return result;
}


void exogenesis_language_manager_GetKbLayouts (ExogenesisLanguageManager* self, const gchar* xorgfile) {
	xmlDoc* _tmp0_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (xorgfile != NULL);
	_tmp0_ = xmlParseFile (xorgfile);
	self->priv->_xKbLayoutDoc = _tmp0_;
	exogenesis_language_manager_PopulateKbModels (self);
	exogenesis_language_manager_PopulateCountries (self);
	if (self->priv->_xKbLayoutDoc == NULL) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new (EXOGENESIS_XML_ERROR, EXOGENESIS_XML_ERROR_FILE_NOT_FOUND, "file %s not found or permissions missing", xorgfile);
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	xmlFreeDoc (self->priv->_xKbLayoutDoc);
}


static void exogenesis_language_manager_PopulateKbModels (ExogenesisLanguageManager* self) {
	g_return_if_fail (self != NULL);
	if (self->priv->_xKbLayoutDoc != NULL) {
		xmlXPathContext* _tmp0_ = NULL;
		xmlXPathContext* xpath;
		xmlXPathObject* _tmp1_ = NULL;
		xmlXPathObject* _result_;
		_tmp0_ = xmlXPathNewContext (self->priv->_xKbLayoutDoc);
		xpath = _tmp0_;
		_tmp1_ = xmlXPathEvalExpression ("//model/configItem", xpath);
		_result_ = _tmp1_;
		if (_result_ != NULL) {
			ExogenesisKeyboardModels* _tmp2_ = NULL;
			_tmp2_ = exogenesis_keyboard_models_new ();
			_g_object_unref0 (self->priv->_kbrds);
			self->priv->_kbrds = _tmp2_;
			{
				gint i;
				i = 0;
				{
					gboolean _tmp3_;
					_tmp3_ = TRUE;
					while (TRUE) {
						gint _tmp4_;
						xmlNode* _tmp5_ = NULL;
						xmlNode* nd;
						if (!_tmp3_) {
							i++;
						}
						_tmp3_ = FALSE;
						_tmp4_ = xmlXPathNodeSetGetLength (_result_->nodesetval);
						if (!(i < _tmp4_)) {
							break;
						}
						_tmp5_ = xmlXPathNodeSetItem (_result_->nodesetval, i);
						nd = _tmp5_->children;
						if (nd->type == XML_TEXT_NODE) {
							ExogenesisKbModel* _tmp6_ = NULL;
							ExogenesisKbModel* model;
							_tmp6_ = exogenesis_kb_model_new ();
							model = _tmp6_;
							{
								xmlNode* curNode;
								curNode = nd;
								{
									gboolean _tmp7_;
									_tmp7_ = TRUE;
									while (TRUE) {
										if (!_tmp7_) {
											curNode = curNode->next;
										}
										_tmp7_ = FALSE;
										if (!(curNode != NULL)) {
											break;
										}
										if (curNode->type == XML_ELEMENT_NODE) {
											const gchar* _tmp8_;
											GQuark _tmp9_;
											static GQuark _tmp9__label0 = 0;
											static GQuark _tmp9__label1 = 0;
											static GQuark _tmp9__label2 = 0;
											_tmp8_ = curNode->name;
											_tmp9_ = (NULL == _tmp8_) ? 0 : g_quark_from_string (_tmp8_);
											if (_tmp9_ == ((0 != _tmp9__label0) ? _tmp9__label0 : (_tmp9__label0 = g_quark_from_static_string ("name")))) {
												switch (0) {
													default:
													{
														gchar* _tmp10_ = NULL;
														gchar* _tmp11_;
														_tmp10_ = xmlNodeGetContent (curNode);
														_tmp11_ = _tmp10_;
														exogenesis_kb_model_set_Name (model, _tmp11_);
														_g_free0 (_tmp11_);
														break;
													}
												}
											} else if (_tmp9_ == ((0 != _tmp9__label1) ? _tmp9__label1 : (_tmp9__label1 = g_quark_from_static_string ("description")))) {
												switch (0) {
													default:
													{
														gchar* _tmp12_ = NULL;
														gchar* _tmp13_;
														_tmp12_ = xmlNodeGetContent (curNode);
														_tmp13_ = _tmp12_;
														exogenesis_kb_model_set_Description (model, _tmp13_);
														_g_free0 (_tmp13_);
														break;
													}
												}
											} else if (_tmp9_ == ((0 != _tmp9__label2) ? _tmp9__label2 : (_tmp9__label2 = g_quark_from_static_string ("vendor")))) {
												switch (0) {
													default:
													{
														gchar* _tmp14_ = NULL;
														gchar* _tmp15_;
														_tmp14_ = xmlNodeGetContent (curNode);
														_tmp15_ = _tmp14_;
														exogenesis_kb_model_set_Vendor (model, _tmp15_);
														_g_free0 (_tmp15_);
														break;
													}
												}
											} else {
												switch (0) {
													default:
													{
														break;
													}
												}
											}
										}
									}
								}
							}
							exogenesis_keyboard_models_AddKeyboard (self->priv->_kbrds, model);
							_exogenesis_kb_model_unref0 (model);
							model = NULL;
							_exogenesis_kb_model_unref0 (model);
						}
					}
				}
			}
		}
	}
}


void exogenesis_language_manager_PopulateCountries (ExogenesisLanguageManager* self) {
	g_return_if_fail (self != NULL);
	if (self->priv->_xKbLayoutDoc != NULL) {
		xmlXPathContext* _tmp0_ = NULL;
		xmlXPathContext* xpath;
		xmlXPathObject* _tmp1_ = NULL;
		xmlXPathObject* _result_;
		_tmp0_ = xmlXPathNewContext (self->priv->_xKbLayoutDoc);
		xpath = _tmp0_;
		_tmp1_ = xmlXPathEvalExpression ("//layout", xpath);
		_result_ = _tmp1_;
		if (_result_ != NULL) {
			{
				gint i;
				i = 0;
				{
					gboolean _tmp2_;
					_tmp2_ = TRUE;
					while (TRUE) {
						gint _tmp3_;
						xmlNode* _tmp4_ = NULL;
						xmlNode* nd;
						ExogenesisKbCountry* _tmp5_ = NULL;
						ExogenesisKbCountry* country;
						if (!_tmp2_) {
							i++;
						}
						_tmp2_ = FALSE;
						_tmp3_ = xmlXPathNodeSetGetLength (_result_->nodesetval);
						if (!(i < _tmp3_)) {
							break;
						}
						_tmp4_ = xmlXPathNodeSetItem (_result_->nodesetval, i);
						nd = _tmp4_->children;
						_tmp5_ = exogenesis_kb_country_new ();
						country = _tmp5_;
						{
							xmlNode* curNode;
							curNode = nd;
							{
								gboolean _tmp6_;
								_tmp6_ = TRUE;
								while (TRUE) {
									const gchar* _tmp7_;
									GQuark _tmp8_;
									static GQuark _tmp8__label0 = 0;
									static GQuark _tmp8__label1 = 0;
									if (!_tmp6_) {
										curNode = curNode->next;
									}
									_tmp6_ = FALSE;
									if (!(curNode != NULL)) {
										break;
									}
									_tmp7_ = curNode->name;
									_tmp8_ = (NULL == _tmp7_) ? 0 : g_quark_from_string (_tmp7_);
									if (_tmp8_ == ((0 != _tmp8__label0) ? _tmp8__label0 : (_tmp8__label0 = g_quark_from_static_string ("configItem")))) {
										switch (0) {
											default:
											{
												exogenesis_language_manager_PopulateCountry (self, curNode->children, country);
												break;
											}
										}
									} else if (_tmp8_ == ((0 != _tmp8__label1) ? _tmp8__label1 : (_tmp8__label1 = g_quark_from_static_string ("variantList")))) {
										switch (0) {
											default:
											{
												exogenesis_language_manager_PopulateVariant (self, curNode->children, country);
												break;
											}
										}
									}
								}
							}
						}
						exogenesis_kb_countries_AddCountry (self->priv->_countries, country);
						_g_object_unref0 (country);
						country = NULL;
						_g_object_unref0 (country);
					}
				}
			}
		}
	}
}


static void exogenesis_language_manager_PopulateCountry (ExogenesisLanguageManager* self, xmlNode* nd, ExogenesisKbCountry* country) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (country != NULL);
	{
		xmlNode* n;
		n = nd;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				const gchar* _tmp1_;
				GQuark _tmp2_;
				static GQuark _tmp2__label0 = 0;
				static GQuark _tmp2__label1 = 0;
				static GQuark _tmp2__label2 = 0;
				static GQuark _tmp2__label3 = 0;
				if (!_tmp0_) {
					n = n->next;
				}
				_tmp0_ = FALSE;
				if (!(n != NULL)) {
					break;
				}
				_tmp1_ = n->name;
				_tmp2_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
				if (_tmp2_ == ((0 != _tmp2__label0) ? _tmp2__label0 : (_tmp2__label0 = g_quark_from_static_string ("name")))) {
					switch (0) {
						default:
						{
							gchar* _tmp3_ = NULL;
							gchar* _tmp4_;
							_tmp3_ = xmlNodeGetContent (n);
							_tmp4_ = _tmp3_;
							exogenesis_kb_country_set_Name (country, _tmp4_);
							_g_free0 (_tmp4_);
							break;
						}
					}
				} else if (_tmp2_ == ((0 != _tmp2__label1) ? _tmp2__label1 : (_tmp2__label1 = g_quark_from_static_string ("shortDescription")))) {
					switch (0) {
						default:
						{
							gchar* _tmp5_ = NULL;
							gchar* _tmp6_;
							_tmp5_ = xmlNodeGetContent (n);
							_tmp6_ = _tmp5_;
							exogenesis_kb_country_set_ShortDescription (country, _tmp6_);
							_g_free0 (_tmp6_);
							break;
						}
					}
				} else if (_tmp2_ == ((0 != _tmp2__label2) ? _tmp2__label2 : (_tmp2__label2 = g_quark_from_static_string ("description")))) {
					switch (0) {
						default:
						{
							gchar* _tmp7_ = NULL;
							gchar* _tmp8_;
							_tmp7_ = xmlNodeGetContent (n);
							_tmp8_ = _tmp7_;
							exogenesis_kb_country_set_Description (country, _tmp8_);
							_g_free0 (_tmp8_);
							break;
						}
					}
				} else if (_tmp2_ == ((0 != _tmp2__label3) ? _tmp2__label3 : (_tmp2__label3 = g_quark_from_static_string ("languageList")))) {
					switch (0) {
						default:
						{
							break;
						}
					}
				}
			}
		}
	}
}


static void exogenesis_language_manager_PopulateVariant (ExogenesisLanguageManager* self, xmlNode* nd, ExogenesisKbCountry* country) {
	ExogenesisKbVariant* _tmp0_ = NULL;
	ExogenesisKbVariant* kv;
	const gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (country != NULL);
	_tmp0_ = exogenesis_kb_variant_new ();
	kv = _tmp0_;
	exogenesis_kb_variant_set_Name (kv, "");
	_tmp1_ = exogenesis_kb_country_get_Description (country);
	exogenesis_kb_variant_set_Description (kv, _tmp1_);
	exogenesis_kb_country_AddVariant (country, kv);
	_g_object_unref0 (kv);
	kv = NULL;
	{
		xmlNode* n;
		n = nd;
		{
			gboolean _tmp2_;
			_tmp2_ = TRUE;
			while (TRUE) {
				if (!_tmp2_) {
					n = n->next;
				}
				_tmp2_ = FALSE;
				if (!(n != NULL)) {
					break;
				}
				if (g_strcmp0 (n->name, "variant") == 0) {
					{
						xmlNode* m;
						m = n->children;
						{
							gboolean _tmp3_;
							_tmp3_ = TRUE;
							while (TRUE) {
								if (!_tmp3_) {
									m = m->next;
								}
								_tmp3_ = FALSE;
								if (!(m != NULL)) {
									break;
								}
								if (g_strcmp0 (m->name, "configItem") == 0) {
									ExogenesisKbVariant* _tmp4_ = NULL;
									ExogenesisKbVariant* kbv;
									_tmp4_ = exogenesis_kb_variant_new ();
									kbv = _tmp4_;
									{
										xmlNode* o;
										o = m->children;
										{
											gboolean _tmp5_;
											_tmp5_ = TRUE;
											while (TRUE) {
												const gchar* _tmp6_;
												GQuark _tmp7_;
												static GQuark _tmp7__label0 = 0;
												static GQuark _tmp7__label1 = 0;
												static GQuark _tmp7__label2 = 0;
												if (!_tmp5_) {
													o = o->next;
												}
												_tmp5_ = FALSE;
												if (!(o != NULL)) {
													break;
												}
												_tmp6_ = o->name;
												_tmp7_ = (NULL == _tmp6_) ? 0 : g_quark_from_string (_tmp6_);
												if (_tmp7_ == ((0 != _tmp7__label0) ? _tmp7__label0 : (_tmp7__label0 = g_quark_from_static_string ("name")))) {
													switch (0) {
														default:
														{
															gchar* _tmp8_ = NULL;
															gchar* _tmp9_;
															_tmp8_ = xmlNodeGetContent (o);
															_tmp9_ = _tmp8_;
															exogenesis_kb_variant_set_Name (kbv, _tmp9_);
															_g_free0 (_tmp9_);
															break;
														}
													}
												} else if (_tmp7_ == ((0 != _tmp7__label1) ? _tmp7__label1 : (_tmp7__label1 = g_quark_from_static_string ("description")))) {
													switch (0) {
														default:
														{
															gchar* _tmp10_ = NULL;
															gchar* _tmp11_;
															_tmp10_ = xmlNodeGetContent (o);
															_tmp11_ = _tmp10_;
															exogenesis_kb_variant_set_Description (kbv, _tmp11_);
															_g_free0 (_tmp11_);
															break;
														}
													}
												} else if (_tmp7_ == ((0 != _tmp7__label2) ? _tmp7__label2 : (_tmp7__label2 = g_quark_from_static_string ("languageList")))) {
													switch (0) {
														default:
														{
															break;
														}
													}
												}
											}
										}
									}
									exogenesis_kb_country_AddVariant (country, kbv);
									_g_object_unref0 (kbv);
									kbv = NULL;
									_g_object_unref0 (kbv);
								}
							}
						}
					}
				}
			}
		}
	}
	_g_object_unref0 (kv);
}


ExogenesisKbCountries* exogenesis_language_manager_get_Countries (ExogenesisLanguageManager* self) {
	ExogenesisKbCountries* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_countries;
	return result;
}


ExogenesisKeyboardModels* exogenesis_language_manager_get_Keyboards (ExogenesisLanguageManager* self) {
	ExogenesisKeyboardModels* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_kbrds;
	return result;
}


const gchar* exogenesis_language_manager_get_CurrentLocale (ExogenesisLanguageManager* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_curLocale;
	return result;
}


void exogenesis_language_manager_set_CurrentLocale (ExogenesisLanguageManager* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_curLocale);
	self->priv->_curLocale = _tmp0_;
}


static void exogenesis_value_language_manager_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void exogenesis_value_language_manager_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		exogenesis_language_manager_unref (value->data[0].v_pointer);
	}
}


static void exogenesis_value_language_manager_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = exogenesis_language_manager_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer exogenesis_value_language_manager_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* exogenesis_value_language_manager_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ExogenesisLanguageManager* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = exogenesis_language_manager_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* exogenesis_value_language_manager_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ExogenesisLanguageManager** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = exogenesis_language_manager_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* exogenesis_param_spec_language_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ExogenesisParamSpecLanguageManager* spec;
	g_return_val_if_fail (g_type_is_a (object_type, EXOGENESIS_TYPE_LANGUAGE_MANAGER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer exogenesis_value_get_language_manager (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_LANGUAGE_MANAGER), NULL);
	return value->data[0].v_pointer;
}


void exogenesis_value_set_language_manager (GValue* value, gpointer v_object) {
	ExogenesisLanguageManager* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_LANGUAGE_MANAGER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, EXOGENESIS_TYPE_LANGUAGE_MANAGER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		exogenesis_language_manager_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		exogenesis_language_manager_unref (old);
	}
}


void exogenesis_value_take_language_manager (GValue* value, gpointer v_object) {
	ExogenesisLanguageManager* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_LANGUAGE_MANAGER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, EXOGENESIS_TYPE_LANGUAGE_MANAGER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		exogenesis_language_manager_unref (old);
	}
}


static void exogenesis_language_manager_class_init (ExogenesisLanguageManagerClass * klass) {
	exogenesis_language_manager_parent_class = g_type_class_peek_parent (klass);
	EXOGENESIS_LANGUAGE_MANAGER_CLASS (klass)->finalize = exogenesis_language_manager_finalize;
	g_type_class_add_private (klass, sizeof (ExogenesisLanguageManagerPrivate));
	g_signal_new ("on_gconf_layout_changed", EXOGENESIS_TYPE_LANGUAGE_MANAGER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void exogenesis_language_manager_instance_init (ExogenesisLanguageManager * self) {
	ExogenesisKeyboardModels* _tmp0_ = NULL;
	ExogenesisKbCountries* _tmp1_ = NULL;
	GConfClient* _tmp2_ = NULL;
	GConfClient* _tmp3_;
	GConfEngine* _tmp4_ = NULL;
	GConfEngine* _tmp5_;
	GConfEngine* _tmp6_;
	gchar* _tmp7_;
	self->priv = EXOGENESIS_LANGUAGE_MANAGER_GET_PRIVATE (self);
	_tmp0_ = exogenesis_keyboard_models_new ();
	self->priv->_kbrds = _tmp0_;
	_tmp1_ = exogenesis_kb_countries_new ();
	self->priv->_countries = _tmp1_;
	_tmp2_ = gconf_client_get_default ();
	_tmp3_ = _g_object_ref0 (_tmp2_);
	self->priv->_gc = _tmp3_;
	_tmp4_ = gconf_engine_get_default ();
	_tmp5_ = (_tmp6_ = _tmp4_, (_tmp6_ == NULL) ? NULL : gconf_engine_ref (_tmp6_), _tmp6_);
	self->priv->_eng = _tmp5_;
	_tmp7_ = g_strdup ("/desktop/gnome/peripherals/keyboard/kbd/layouts");
	self->priv->_GCKbKey = _tmp7_;
	self->ref_count = 1;
}


static void exogenesis_language_manager_finalize (ExogenesisLanguageManager* obj) {
	ExogenesisLanguageManager * self;
	self = EXOGENESIS_LANGUAGE_MANAGER (obj);
	_g_free0 (self->priv->_curLocale);
	_g_object_unref0 (self->priv->_kbrds);
	_g_object_unref0 (self->priv->_countries);
	_g_object_unref0 (self->priv->_gc);
	_gconf_engine_unref0 (self->priv->_eng);
	__g_slist_free__g_free0_0 (self->priv->_CurrentKbConf);
	_g_free0 (self->priv->_GCKbKey);
}


GType exogenesis_language_manager_get_type (void) {
	static volatile gsize exogenesis_language_manager_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_language_manager_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { exogenesis_value_language_manager_init, exogenesis_value_language_manager_free_value, exogenesis_value_language_manager_copy_value, exogenesis_value_language_manager_peek_pointer, "p", exogenesis_value_language_manager_collect_value, "p", exogenesis_value_language_manager_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisLanguageManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_language_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisLanguageManager), 0, (GInstanceInitFunc) exogenesis_language_manager_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType exogenesis_language_manager_type_id;
		exogenesis_language_manager_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ExogenesisLanguageManager", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&exogenesis_language_manager_type_id__volatile, exogenesis_language_manager_type_id);
	}
	return exogenesis_language_manager_type_id__volatile;
}


gpointer exogenesis_language_manager_ref (gpointer instance) {
	ExogenesisLanguageManager* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void exogenesis_language_manager_unref (gpointer instance) {
	ExogenesisLanguageManager* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		EXOGENESIS_LANGUAGE_MANAGER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


ExogenesisLanguage* exogenesis_language_construct (GType object_type) {
	ExogenesisLanguage* self = NULL;
	self = (ExogenesisLanguage*) g_type_create_instance (object_type);
	return self;
}


ExogenesisLanguage* exogenesis_language_new (void) {
	return exogenesis_language_construct (EXOGENESIS_TYPE_LANGUAGE);
}


gint exogenesis_language_get_Order (ExogenesisLanguage* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_Order;
	return result;
}


void exogenesis_language_set_Order (ExogenesisLanguage* self, gint value) {
	g_return_if_fail (self != NULL);
	self->priv->_Order = value;
}


const gchar* exogenesis_language_get_Code (ExogenesisLanguage* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Code;
	return result;
}


void exogenesis_language_set_Code (ExogenesisLanguage* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_Code);
	self->priv->_Code = _tmp0_;
}


const gchar* exogenesis_language_get_Country (ExogenesisLanguage* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Country;
	return result;
}


void exogenesis_language_set_Country (ExogenesisLanguage* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_Country);
	self->priv->_Country = _tmp0_;
}


const gchar* exogenesis_language_get_CountryNative (ExogenesisLanguage* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_CountryNative;
	return result;
}


void exogenesis_language_set_CountryNative (ExogenesisLanguage* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_CountryNative);
	self->priv->_CountryNative = _tmp0_;
}


static void exogenesis_value_language_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void exogenesis_value_language_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		exogenesis_language_unref (value->data[0].v_pointer);
	}
}


static void exogenesis_value_language_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = exogenesis_language_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer exogenesis_value_language_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* exogenesis_value_language_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ExogenesisLanguage* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = exogenesis_language_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* exogenesis_value_language_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ExogenesisLanguage** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = exogenesis_language_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* exogenesis_param_spec_language (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ExogenesisParamSpecLanguage* spec;
	g_return_val_if_fail (g_type_is_a (object_type, EXOGENESIS_TYPE_LANGUAGE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer exogenesis_value_get_language (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_LANGUAGE), NULL);
	return value->data[0].v_pointer;
}


void exogenesis_value_set_language (GValue* value, gpointer v_object) {
	ExogenesisLanguage* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_LANGUAGE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, EXOGENESIS_TYPE_LANGUAGE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		exogenesis_language_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		exogenesis_language_unref (old);
	}
}


void exogenesis_value_take_language (GValue* value, gpointer v_object) {
	ExogenesisLanguage* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_LANGUAGE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, EXOGENESIS_TYPE_LANGUAGE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		exogenesis_language_unref (old);
	}
}


static void exogenesis_language_class_init (ExogenesisLanguageClass * klass) {
	exogenesis_language_parent_class = g_type_class_peek_parent (klass);
	EXOGENESIS_LANGUAGE_CLASS (klass)->finalize = exogenesis_language_finalize;
	g_type_class_add_private (klass, sizeof (ExogenesisLanguagePrivate));
}


static void exogenesis_language_instance_init (ExogenesisLanguage * self) {
	self->priv = EXOGENESIS_LANGUAGE_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void exogenesis_language_finalize (ExogenesisLanguage* obj) {
	ExogenesisLanguage * self;
	self = EXOGENESIS_LANGUAGE (obj);
	_g_free0 (self->priv->_Code);
	_g_free0 (self->priv->_Country);
	_g_free0 (self->priv->_CountryNative);
}


GType exogenesis_language_get_type (void) {
	static volatile gsize exogenesis_language_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_language_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { exogenesis_value_language_init, exogenesis_value_language_free_value, exogenesis_value_language_copy_value, exogenesis_value_language_peek_pointer, "p", exogenesis_value_language_collect_value, "p", exogenesis_value_language_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisLanguageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_language_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisLanguage), 0, (GInstanceInitFunc) exogenesis_language_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType exogenesis_language_type_id;
		exogenesis_language_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ExogenesisLanguage", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&exogenesis_language_type_id__volatile, exogenesis_language_type_id);
	}
	return exogenesis_language_type_id__volatile;
}


gpointer exogenesis_language_ref (gpointer instance) {
	ExogenesisLanguage* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void exogenesis_language_unref (gpointer instance) {
	ExogenesisLanguage* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		EXOGENESIS_LANGUAGE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


void exogenesis_keyboard_models_KeyboardModels (ExogenesisKeyboardModels* self) {
	g_return_if_fail (self != NULL);
}


void exogenesis_keyboard_models_AddKeyboard (ExogenesisKeyboardModels* self, ExogenesisKbModel* m) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (m != NULL);
	self->priv->_count++;
	gee_abstract_collection_add ((GeeAbstractCollection*) self->_kbrds, m);
}


void exogenesis_keyboard_models_Sort (ExogenesisKeyboardModels* self) {
	g_return_if_fail (self != NULL);
	gee_list_sort ((GeeList*) self->_kbrds, NULL);
}


static GeeIterator* exogenesis_keyboard_models_real_iterator (GeeIterable* base) {
	ExogenesisKeyboardModels * self;
	GeeIterator* result = NULL;
	GeeIterator* _tmp0_ = NULL;
	self = (ExogenesisKeyboardModels*) base;
	_tmp0_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) self->_kbrds);
	result = _tmp0_;
	return result;
}


ExogenesisKeyboardModels* exogenesis_keyboard_models_construct (GType object_type) {
	ExogenesisKeyboardModels * self = NULL;
	self = (ExogenesisKeyboardModels*) g_object_new (object_type, NULL);
	return self;
}


ExogenesisKeyboardModels* exogenesis_keyboard_models_new (void) {
	return exogenesis_keyboard_models_construct (EXOGENESIS_TYPE_KEYBOARD_MODELS);
}


static GType exogenesis_keyboard_models_real_get_element_type (GeeIterable* base) {
	GType result;
	ExogenesisKeyboardModels* self;
	self = (ExogenesisKeyboardModels*) base;
	result = EXOGENESIS_TYPE_KB_MODEL;
	return result;
}


glong exogenesis_keyboard_models_get_Count (ExogenesisKeyboardModels* self) {
	glong result;
	g_return_val_if_fail (self != NULL, 0L);
	result = self->priv->_count;
	return result;
}


static void exogenesis_keyboard_models_class_init (ExogenesisKeyboardModelsClass * klass) {
	exogenesis_keyboard_models_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ExogenesisKeyboardModelsPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_exogenesis_keyboard_models_get_property;
	G_OBJECT_CLASS (klass)->finalize = exogenesis_keyboard_models_finalize;
	g_object_class_override_property (G_OBJECT_CLASS (klass), EXOGENESIS_KEYBOARD_MODELS_ELEMENT_TYPE, "element-type");
	g_object_class_install_property (G_OBJECT_CLASS (klass), EXOGENESIS_KEYBOARD_MODELS_COUNT, g_param_spec_long ("Count", "Count", "Count", G_MINLONG, G_MAXLONG, 0L, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void exogenesis_keyboard_models_gee_iterable_interface_init (GeeIterableIface * iface) {
	exogenesis_keyboard_models_gee_iterable_parent_iface = g_type_interface_peek_parent (iface);
	iface->iterator = (GeeIterator* (*)(GeeIterable*)) exogenesis_keyboard_models_real_iterator;
	iface->get_element_type = exogenesis_keyboard_models_real_get_element_type;
}


static void exogenesis_keyboard_models_instance_init (ExogenesisKeyboardModels * self) {
	GeeArrayList* _tmp0_ = NULL;
	self->priv = EXOGENESIS_KEYBOARD_MODELS_GET_PRIVATE (self);
	_tmp0_ = gee_array_list_new (EXOGENESIS_TYPE_KB_MODEL, (GBoxedCopyFunc) exogenesis_kb_model_ref, exogenesis_kb_model_unref, NULL);
	self->_kbrds = _tmp0_;
	self->priv->_count = (glong) 0;
}


static void exogenesis_keyboard_models_finalize (GObject* obj) {
	ExogenesisKeyboardModels * self;
	self = EXOGENESIS_KEYBOARD_MODELS (obj);
	_g_object_unref0 (self->_kbrds);
	G_OBJECT_CLASS (exogenesis_keyboard_models_parent_class)->finalize (obj);
}


GType exogenesis_keyboard_models_get_type (void) {
	static volatile gsize exogenesis_keyboard_models_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_keyboard_models_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisKeyboardModelsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_keyboard_models_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisKeyboardModels), 0, (GInstanceInitFunc) exogenesis_keyboard_models_instance_init, NULL };
		static const GInterfaceInfo gee_iterable_info = { (GInterfaceInitFunc) exogenesis_keyboard_models_gee_iterable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType exogenesis_keyboard_models_type_id;
		exogenesis_keyboard_models_type_id = g_type_register_static (G_TYPE_OBJECT, "ExogenesisKeyboardModels", &g_define_type_info, 0);
		g_type_add_interface_static (exogenesis_keyboard_models_type_id, GEE_TYPE_ITERABLE, &gee_iterable_info);
		g_once_init_leave (&exogenesis_keyboard_models_type_id__volatile, exogenesis_keyboard_models_type_id);
	}
	return exogenesis_keyboard_models_type_id__volatile;
}


static void _vala_exogenesis_keyboard_models_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ExogenesisKeyboardModels * self;
	self = EXOGENESIS_KEYBOARD_MODELS (object);
	switch (property_id) {
		case EXOGENESIS_KEYBOARD_MODELS_ELEMENT_TYPE:
		g_value_set_gtype (value, gee_iterable_get_element_type ((GeeIterable*) self));
		break;
		case EXOGENESIS_KEYBOARD_MODELS_COUNT:
		g_value_set_long (value, exogenesis_keyboard_models_get_Count (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


ExogenesisKbModel* exogenesis_kb_model_construct (GType object_type) {
	ExogenesisKbModel* self = NULL;
	self = (ExogenesisKbModel*) g_type_create_instance (object_type);
	return self;
}


ExogenesisKbModel* exogenesis_kb_model_new (void) {
	return exogenesis_kb_model_construct (EXOGENESIS_TYPE_KB_MODEL);
}


ExogenesisKbModel* exogenesis_kb_model_construct_WithValues (GType object_type, const gchar* name, const gchar* description, const gchar* vendor) {
	ExogenesisKbModel* self = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (description != NULL, NULL);
	g_return_val_if_fail (vendor != NULL, NULL);
	self = (ExogenesisKbModel*) g_type_create_instance (object_type);
	exogenesis_kb_model_set_Name (self, name);
	exogenesis_kb_model_set_Description (self, description);
	exogenesis_kb_model_set_Vendor (self, vendor);
	return self;
}


ExogenesisKbModel* exogenesis_kb_model_new_WithValues (const gchar* name, const gchar* description, const gchar* vendor) {
	return exogenesis_kb_model_construct_WithValues (EXOGENESIS_TYPE_KB_MODEL, name, description, vendor);
}


const gchar* exogenesis_kb_model_get_Name (ExogenesisKbModel* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Name;
	return result;
}


void exogenesis_kb_model_set_Name (ExogenesisKbModel* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_Name);
	self->priv->_Name = _tmp0_;
}


const gchar* exogenesis_kb_model_get_Description (ExogenesisKbModel* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Description;
	return result;
}


void exogenesis_kb_model_set_Description (ExogenesisKbModel* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_Description);
	self->priv->_Description = _tmp0_;
}


const gchar* exogenesis_kb_model_get_Vendor (ExogenesisKbModel* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Vendor;
	return result;
}


void exogenesis_kb_model_set_Vendor (ExogenesisKbModel* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_Vendor);
	self->priv->_Vendor = _tmp0_;
}


static void exogenesis_value_kb_model_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void exogenesis_value_kb_model_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		exogenesis_kb_model_unref (value->data[0].v_pointer);
	}
}


static void exogenesis_value_kb_model_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = exogenesis_kb_model_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer exogenesis_value_kb_model_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* exogenesis_value_kb_model_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ExogenesisKbModel* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = exogenesis_kb_model_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* exogenesis_value_kb_model_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ExogenesisKbModel** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = exogenesis_kb_model_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* exogenesis_param_spec_kb_model (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ExogenesisParamSpecKbModel* spec;
	g_return_val_if_fail (g_type_is_a (object_type, EXOGENESIS_TYPE_KB_MODEL), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer exogenesis_value_get_kb_model (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_KB_MODEL), NULL);
	return value->data[0].v_pointer;
}


void exogenesis_value_set_kb_model (GValue* value, gpointer v_object) {
	ExogenesisKbModel* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_KB_MODEL));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, EXOGENESIS_TYPE_KB_MODEL));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		exogenesis_kb_model_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		exogenesis_kb_model_unref (old);
	}
}


void exogenesis_value_take_kb_model (GValue* value, gpointer v_object) {
	ExogenesisKbModel* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_KB_MODEL));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, EXOGENESIS_TYPE_KB_MODEL));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		exogenesis_kb_model_unref (old);
	}
}


static void exogenesis_kb_model_class_init (ExogenesisKbModelClass * klass) {
	exogenesis_kb_model_parent_class = g_type_class_peek_parent (klass);
	EXOGENESIS_KB_MODEL_CLASS (klass)->finalize = exogenesis_kb_model_finalize;
	g_type_class_add_private (klass, sizeof (ExogenesisKbModelPrivate));
}


static void exogenesis_kb_model_instance_init (ExogenesisKbModel * self) {
	self->priv = EXOGENESIS_KB_MODEL_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void exogenesis_kb_model_finalize (ExogenesisKbModel* obj) {
	ExogenesisKbModel * self;
	self = EXOGENESIS_KB_MODEL (obj);
	_g_free0 (self->priv->_Name);
	_g_free0 (self->priv->_Description);
	_g_free0 (self->priv->_Vendor);
}


GType exogenesis_kb_model_get_type (void) {
	static volatile gsize exogenesis_kb_model_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_kb_model_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { exogenesis_value_kb_model_init, exogenesis_value_kb_model_free_value, exogenesis_value_kb_model_copy_value, exogenesis_value_kb_model_peek_pointer, "p", exogenesis_value_kb_model_collect_value, "p", exogenesis_value_kb_model_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisKbModelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_kb_model_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisKbModel), 0, (GInstanceInitFunc) exogenesis_kb_model_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType exogenesis_kb_model_type_id;
		exogenesis_kb_model_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ExogenesisKbModel", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&exogenesis_kb_model_type_id__volatile, exogenesis_kb_model_type_id);
	}
	return exogenesis_kb_model_type_id__volatile;
}


gpointer exogenesis_kb_model_ref (gpointer instance) {
	ExogenesisKbModel* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void exogenesis_kb_model_unref (gpointer instance) {
	ExogenesisKbModel* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		EXOGENESIS_KB_MODEL_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


void exogenesis_kb_countries_KbCountries (ExogenesisKbCountries* self) {
	g_return_if_fail (self != NULL);
}


void exogenesis_kb_countries_AddCountry (ExogenesisKbCountries* self, ExogenesisKbCountry* country) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (country != NULL);
	gee_abstract_collection_add ((GeeAbstractCollection*) self->_countries, country);
}


void exogenesis_kb_countries_Sort (ExogenesisKbCountries* self) {
	g_return_if_fail (self != NULL);
	gee_list_sort ((GeeList*) self->_countries, NULL);
}


static GeeIterator* exogenesis_kb_countries_real_iterator (GeeIterable* base) {
	ExogenesisKbCountries * self;
	GeeIterator* result = NULL;
	GeeIterator* _tmp0_ = NULL;
	self = (ExogenesisKbCountries*) base;
	_tmp0_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) self->_countries);
	result = _tmp0_;
	return result;
}


ExogenesisKbCountries* exogenesis_kb_countries_construct (GType object_type) {
	ExogenesisKbCountries * self = NULL;
	self = (ExogenesisKbCountries*) g_object_new (object_type, NULL);
	return self;
}


ExogenesisKbCountries* exogenesis_kb_countries_new (void) {
	return exogenesis_kb_countries_construct (EXOGENESIS_TYPE_KB_COUNTRIES);
}


static GType exogenesis_kb_countries_real_get_element_type (GeeIterable* base) {
	GType result;
	ExogenesisKbCountries* self;
	self = (ExogenesisKbCountries*) base;
	result = EXOGENESIS_TYPE_KB_COUNTRY;
	return result;
}


static void exogenesis_kb_countries_class_init (ExogenesisKbCountriesClass * klass) {
	exogenesis_kb_countries_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->get_property = _vala_exogenesis_kb_countries_get_property;
	G_OBJECT_CLASS (klass)->finalize = exogenesis_kb_countries_finalize;
	g_object_class_override_property (G_OBJECT_CLASS (klass), EXOGENESIS_KB_COUNTRIES_ELEMENT_TYPE, "element-type");
}


static void exogenesis_kb_countries_gee_iterable_interface_init (GeeIterableIface * iface) {
	exogenesis_kb_countries_gee_iterable_parent_iface = g_type_interface_peek_parent (iface);
	iface->iterator = (GeeIterator* (*)(GeeIterable*)) exogenesis_kb_countries_real_iterator;
	iface->get_element_type = exogenesis_kb_countries_real_get_element_type;
}


static void exogenesis_kb_countries_instance_init (ExogenesisKbCountries * self) {
	GeeArrayList* _tmp0_ = NULL;
	_tmp0_ = gee_array_list_new (EXOGENESIS_TYPE_KB_COUNTRY, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
	self->_countries = _tmp0_;
}


static void exogenesis_kb_countries_finalize (GObject* obj) {
	ExogenesisKbCountries * self;
	self = EXOGENESIS_KB_COUNTRIES (obj);
	_g_object_unref0 (self->_countries);
	G_OBJECT_CLASS (exogenesis_kb_countries_parent_class)->finalize (obj);
}


GType exogenesis_kb_countries_get_type (void) {
	static volatile gsize exogenesis_kb_countries_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_kb_countries_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisKbCountriesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_kb_countries_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisKbCountries), 0, (GInstanceInitFunc) exogenesis_kb_countries_instance_init, NULL };
		static const GInterfaceInfo gee_iterable_info = { (GInterfaceInitFunc) exogenesis_kb_countries_gee_iterable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType exogenesis_kb_countries_type_id;
		exogenesis_kb_countries_type_id = g_type_register_static (G_TYPE_OBJECT, "ExogenesisKbCountries", &g_define_type_info, 0);
		g_type_add_interface_static (exogenesis_kb_countries_type_id, GEE_TYPE_ITERABLE, &gee_iterable_info);
		g_once_init_leave (&exogenesis_kb_countries_type_id__volatile, exogenesis_kb_countries_type_id);
	}
	return exogenesis_kb_countries_type_id__volatile;
}


static void _vala_exogenesis_kb_countries_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ExogenesisKbCountries * self;
	self = EXOGENESIS_KB_COUNTRIES (object);
	switch (property_id) {
		case EXOGENESIS_KB_COUNTRIES_ELEMENT_TYPE:
		g_value_set_gtype (value, gee_iterable_get_element_type ((GeeIterable*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


void exogenesis_kb_country_KbCountry (ExogenesisKbCountry* self) {
	g_return_if_fail (self != NULL);
}


void exogenesis_kb_country_AddLanguageISO (ExogenesisKbCountry* self, const gchar* iso) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (iso != NULL);
	gee_abstract_collection_add ((GeeAbstractCollection*) self->_isocode, iso);
}


void exogenesis_kb_country_AddVariant (ExogenesisKbCountry* self, ExogenesisKbVariant* kbvariant) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (kbvariant != NULL);
	self->priv->_variantcount++;
	gee_abstract_collection_add ((GeeAbstractCollection*) self->_variant, kbvariant);
}


static GeeIterator* exogenesis_kb_country_real_iterator (GeeIterable* base) {
	ExogenesisKbCountry * self;
	GeeIterator* result = NULL;
	GeeIterator* _tmp0_ = NULL;
	self = (ExogenesisKbCountry*) base;
	_tmp0_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) self->_variant);
	result = _tmp0_;
	return result;
}


static gint exogenesis_kb_country_real_compare_to (GeeComparable* base, ExogenesisKbCountry* comp) {
	ExogenesisKbCountry * self;
	gint result = 0;
	self = (ExogenesisKbCountry*) base;
	g_return_val_if_fail (comp != NULL, 0);
	if (g_strcmp0 (self->priv->_Description, comp->priv->_Description) < 0) {
		result = -1;
		return result;
	}
	if (g_strcmp0 (self->priv->_Description, comp->priv->_Description) > 0) {
		result = 1;
		return result;
	}
	result = 0;
	return result;
}


ExogenesisKbCountry* exogenesis_kb_country_construct (GType object_type) {
	ExogenesisKbCountry * self = NULL;
	self = (ExogenesisKbCountry*) g_object_new (object_type, NULL);
	return self;
}


ExogenesisKbCountry* exogenesis_kb_country_new (void) {
	return exogenesis_kb_country_construct (EXOGENESIS_TYPE_KB_COUNTRY);
}


const gchar* exogenesis_kb_country_get_Name (ExogenesisKbCountry* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Name;
	return result;
}


void exogenesis_kb_country_set_Name (ExogenesisKbCountry* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_Name);
	self->priv->_Name = _tmp0_;
	g_object_notify ((GObject *) self, "Name");
}


const gchar* exogenesis_kb_country_get_ShortDescription (ExogenesisKbCountry* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_ShortDescription;
	return result;
}


void exogenesis_kb_country_set_ShortDescription (ExogenesisKbCountry* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_ShortDescription);
	self->priv->_ShortDescription = _tmp0_;
	g_object_notify ((GObject *) self, "ShortDescription");
}


const gchar* exogenesis_kb_country_get_Description (ExogenesisKbCountry* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Description;
	return result;
}


void exogenesis_kb_country_set_Description (ExogenesisKbCountry* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_Description);
	self->priv->_Description = _tmp0_;
	g_object_notify ((GObject *) self, "Description");
}


gint exogenesis_kb_country_get_VariantCount (ExogenesisKbCountry* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = self->priv->_variantcount;
	return result;
}


static GType exogenesis_kb_country_real_get_element_type (GeeIterable* base) {
	GType result;
	ExogenesisKbCountry* self;
	self = (ExogenesisKbCountry*) base;
	result = EXOGENESIS_TYPE_KB_VARIANT;
	return result;
}


static void exogenesis_kb_country_class_init (ExogenesisKbCountryClass * klass) {
	exogenesis_kb_country_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ExogenesisKbCountryPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_exogenesis_kb_country_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_exogenesis_kb_country_set_property;
	G_OBJECT_CLASS (klass)->finalize = exogenesis_kb_country_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), EXOGENESIS_KB_COUNTRY_NAME, g_param_spec_string ("Name", "Name", "Name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), EXOGENESIS_KB_COUNTRY_SHORT_DESCRIPTION, g_param_spec_string ("ShortDescription", "ShortDescription", "ShortDescription", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), EXOGENESIS_KB_COUNTRY_DESCRIPTION, g_param_spec_string ("Description", "Description", "Description", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), EXOGENESIS_KB_COUNTRY_VARIANT_COUNT, g_param_spec_int ("VariantCount", "VariantCount", "VariantCount", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_override_property (G_OBJECT_CLASS (klass), EXOGENESIS_KB_COUNTRY_ELEMENT_TYPE, "element-type");
}


static void exogenesis_kb_country_gee_comparable_interface_init (GeeComparableIface * iface) {
	exogenesis_kb_country_gee_comparable_parent_iface = g_type_interface_peek_parent (iface);
	iface->compare_to = (gint (*)(GeeComparable* ,gconstpointer)) exogenesis_kb_country_real_compare_to;
}


static void exogenesis_kb_country_gee_iterable_interface_init (GeeIterableIface * iface) {
	exogenesis_kb_country_gee_iterable_parent_iface = g_type_interface_peek_parent (iface);
	iface->iterator = (GeeIterator* (*)(GeeIterable*)) exogenesis_kb_country_real_iterator;
	iface->get_element_type = exogenesis_kb_country_real_get_element_type;
}


static void exogenesis_kb_country_instance_init (ExogenesisKbCountry * self) {
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	self->priv = EXOGENESIS_KB_COUNTRY_GET_PRIVATE (self);
	_tmp0_ = gee_array_list_new (EXOGENESIS_TYPE_KB_VARIANT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
	self->_variant = _tmp0_;
	_tmp1_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL);
	self->_isocode = _tmp1_;
	self->priv->_variantcount = 0;
}


static void exogenesis_kb_country_finalize (GObject* obj) {
	ExogenesisKbCountry * self;
	self = EXOGENESIS_KB_COUNTRY (obj);
	_g_free0 (self->priv->_Name);
	_g_free0 (self->priv->_ShortDescription);
	_g_free0 (self->priv->_Description);
	_g_object_unref0 (self->_variant);
	_g_object_unref0 (self->_isocode);
	G_OBJECT_CLASS (exogenesis_kb_country_parent_class)->finalize (obj);
}


GType exogenesis_kb_country_get_type (void) {
	static volatile gsize exogenesis_kb_country_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_kb_country_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisKbCountryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_kb_country_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisKbCountry), 0, (GInstanceInitFunc) exogenesis_kb_country_instance_init, NULL };
		static const GInterfaceInfo gee_comparable_info = { (GInterfaceInitFunc) exogenesis_kb_country_gee_comparable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo gee_iterable_info = { (GInterfaceInitFunc) exogenesis_kb_country_gee_iterable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType exogenesis_kb_country_type_id;
		exogenesis_kb_country_type_id = g_type_register_static (G_TYPE_OBJECT, "ExogenesisKbCountry", &g_define_type_info, 0);
		g_type_add_interface_static (exogenesis_kb_country_type_id, GEE_TYPE_COMPARABLE, &gee_comparable_info);
		g_type_add_interface_static (exogenesis_kb_country_type_id, GEE_TYPE_ITERABLE, &gee_iterable_info);
		g_once_init_leave (&exogenesis_kb_country_type_id__volatile, exogenesis_kb_country_type_id);
	}
	return exogenesis_kb_country_type_id__volatile;
}


static void _vala_exogenesis_kb_country_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ExogenesisKbCountry * self;
	self = EXOGENESIS_KB_COUNTRY (object);
	switch (property_id) {
		case EXOGENESIS_KB_COUNTRY_NAME:
		g_value_set_string (value, exogenesis_kb_country_get_Name (self));
		break;
		case EXOGENESIS_KB_COUNTRY_SHORT_DESCRIPTION:
		g_value_set_string (value, exogenesis_kb_country_get_ShortDescription (self));
		break;
		case EXOGENESIS_KB_COUNTRY_DESCRIPTION:
		g_value_set_string (value, exogenesis_kb_country_get_Description (self));
		break;
		case EXOGENESIS_KB_COUNTRY_VARIANT_COUNT:
		g_value_set_int (value, exogenesis_kb_country_get_VariantCount (self));
		break;
		case EXOGENESIS_KB_COUNTRY_ELEMENT_TYPE:
		g_value_set_gtype (value, gee_iterable_get_element_type ((GeeIterable*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_exogenesis_kb_country_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ExogenesisKbCountry * self;
	self = EXOGENESIS_KB_COUNTRY (object);
	switch (property_id) {
		case EXOGENESIS_KB_COUNTRY_NAME:
		exogenesis_kb_country_set_Name (self, g_value_get_string (value));
		break;
		case EXOGENESIS_KB_COUNTRY_SHORT_DESCRIPTION:
		exogenesis_kb_country_set_ShortDescription (self, g_value_get_string (value));
		break;
		case EXOGENESIS_KB_COUNTRY_DESCRIPTION:
		exogenesis_kb_country_set_Description (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


void exogenesis_kb_variant_KbVariant (ExogenesisKbVariant* self) {
	g_return_if_fail (self != NULL);
}


void exogenesis_kb_variant_AddLanguage (ExogenesisKbVariant* self, const gchar* lang) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (lang != NULL);
	gee_abstract_collection_add ((GeeAbstractCollection*) self->_languageList, lang);
}


static GeeIterator* exogenesis_kb_variant_real_iterator (GeeIterable* base) {
	ExogenesisKbVariant * self;
	GeeIterator* result = NULL;
	GeeIterator* _tmp0_ = NULL;
	self = (ExogenesisKbVariant*) base;
	_tmp0_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) self->_languageList);
	result = _tmp0_;
	return result;
}


ExogenesisKbVariant* exogenesis_kb_variant_construct (GType object_type) {
	ExogenesisKbVariant * self = NULL;
	self = (ExogenesisKbVariant*) g_object_new (object_type, NULL);
	return self;
}


ExogenesisKbVariant* exogenesis_kb_variant_new (void) {
	return exogenesis_kb_variant_construct (EXOGENESIS_TYPE_KB_VARIANT);
}


const gchar* exogenesis_kb_variant_get_Name (ExogenesisKbVariant* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Name;
	return result;
}


void exogenesis_kb_variant_set_Name (ExogenesisKbVariant* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_Name);
	self->priv->_Name = _tmp0_;
	g_object_notify ((GObject *) self, "Name");
}


const gchar* exogenesis_kb_variant_get_Description (ExogenesisKbVariant* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_Description;
	return result;
}


void exogenesis_kb_variant_set_Description (ExogenesisKbVariant* self, const gchar* value) {
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_Description);
	self->priv->_Description = _tmp0_;
	g_object_notify ((GObject *) self, "Description");
}


static GType exogenesis_kb_variant_real_get_element_type (GeeIterable* base) {
	GType result;
	ExogenesisKbVariant* self;
	self = (ExogenesisKbVariant*) base;
	result = G_TYPE_STRING;
	return result;
}


static void exogenesis_kb_variant_class_init (ExogenesisKbVariantClass * klass) {
	exogenesis_kb_variant_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ExogenesisKbVariantPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_exogenesis_kb_variant_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_exogenesis_kb_variant_set_property;
	G_OBJECT_CLASS (klass)->finalize = exogenesis_kb_variant_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), EXOGENESIS_KB_VARIANT_NAME, g_param_spec_string ("Name", "Name", "Name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), EXOGENESIS_KB_VARIANT_DESCRIPTION, g_param_spec_string ("Description", "Description", "Description", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_override_property (G_OBJECT_CLASS (klass), EXOGENESIS_KB_VARIANT_ELEMENT_TYPE, "element-type");
}


static void exogenesis_kb_variant_gee_iterable_interface_init (GeeIterableIface * iface) {
	exogenesis_kb_variant_gee_iterable_parent_iface = g_type_interface_peek_parent (iface);
	iface->iterator = (GeeIterator* (*)(GeeIterable*)) exogenesis_kb_variant_real_iterator;
	iface->get_element_type = exogenesis_kb_variant_real_get_element_type;
}


static void exogenesis_kb_variant_instance_init (ExogenesisKbVariant * self) {
	GeeArrayList* _tmp0_ = NULL;
	self->priv = EXOGENESIS_KB_VARIANT_GET_PRIVATE (self);
	_tmp0_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL);
	self->_languageList = _tmp0_;
}


static void exogenesis_kb_variant_finalize (GObject* obj) {
	ExogenesisKbVariant * self;
	self = EXOGENESIS_KB_VARIANT (obj);
	_g_free0 (self->priv->_Name);
	_g_free0 (self->priv->_Description);
	_g_object_unref0 (self->_languageList);
	G_OBJECT_CLASS (exogenesis_kb_variant_parent_class)->finalize (obj);
}


GType exogenesis_kb_variant_get_type (void) {
	static volatile gsize exogenesis_kb_variant_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_kb_variant_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisKbVariantClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_kb_variant_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisKbVariant), 0, (GInstanceInitFunc) exogenesis_kb_variant_instance_init, NULL };
		static const GInterfaceInfo gee_iterable_info = { (GInterfaceInitFunc) exogenesis_kb_variant_gee_iterable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType exogenesis_kb_variant_type_id;
		exogenesis_kb_variant_type_id = g_type_register_static (G_TYPE_OBJECT, "ExogenesisKbVariant", &g_define_type_info, 0);
		g_type_add_interface_static (exogenesis_kb_variant_type_id, GEE_TYPE_ITERABLE, &gee_iterable_info);
		g_once_init_leave (&exogenesis_kb_variant_type_id__volatile, exogenesis_kb_variant_type_id);
	}
	return exogenesis_kb_variant_type_id__volatile;
}


static void _vala_exogenesis_kb_variant_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ExogenesisKbVariant * self;
	self = EXOGENESIS_KB_VARIANT (object);
	switch (property_id) {
		case EXOGENESIS_KB_VARIANT_NAME:
		g_value_set_string (value, exogenesis_kb_variant_get_Name (self));
		break;
		case EXOGENESIS_KB_VARIANT_DESCRIPTION:
		g_value_set_string (value, exogenesis_kb_variant_get_Description (self));
		break;
		case EXOGENESIS_KB_VARIANT_ELEMENT_TYPE:
		g_value_set_gtype (value, gee_iterable_get_element_type ((GeeIterable*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_exogenesis_kb_variant_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ExogenesisKbVariant * self;
	self = EXOGENESIS_KB_VARIANT (object);
	switch (property_id) {
		case EXOGENESIS_KB_VARIANT_NAME:
		exogenesis_kb_variant_set_Name (self, g_value_get_string (value));
		break;
		case EXOGENESIS_KB_VARIANT_DESCRIPTION:
		exogenesis_kb_variant_set_Description (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



