/* main.c generated by valac 0.12.1, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gst/gst.h>
#include <gdk/gdk.h>
#include <gobject/gvaluecollector.h>


#define EXOGENESIS_TYPE_MAIN_WIN (exogenesis_main_win_get_type ())
#define EXOGENESIS_MAIN_WIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWin))
#define EXOGENESIS_MAIN_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWinClass))
#define EXOGENESIS_IS_MAIN_WIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_MAIN_WIN))
#define EXOGENESIS_IS_MAIN_WIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_MAIN_WIN))
#define EXOGENESIS_MAIN_WIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_MAIN_WIN, ExogenesisMainWinClass))

typedef struct _ExogenesisMainWin ExogenesisMainWin;
typedef struct _ExogenesisMainWinClass ExogenesisMainWinClass;

#define EXOGENESIS_TYPE_HD_MANAGER (exogenesis_hd_manager_get_type ())
#define EXOGENESIS_HD_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_HD_MANAGER, ExogenesisHDManager))
#define EXOGENESIS_HD_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_HD_MANAGER, ExogenesisHDManagerClass))
#define EXOGENESIS_IS_HD_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_HD_MANAGER))
#define EXOGENESIS_IS_HD_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_HD_MANAGER))
#define EXOGENESIS_HD_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_HD_MANAGER, ExogenesisHDManagerClass))

typedef struct _ExogenesisHDManager ExogenesisHDManager;
typedef struct _ExogenesisHDManagerClass ExogenesisHDManagerClass;

#define EXOGENESIS_TYPE_LANGUAGE_MANAGER (exogenesis_language_manager_get_type ())
#define EXOGENESIS_LANGUAGE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_LANGUAGE_MANAGER, ExogenesisLanguageManager))
#define EXOGENESIS_LANGUAGE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_LANGUAGE_MANAGER, ExogenesisLanguageManagerClass))
#define EXOGENESIS_IS_LANGUAGE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_LANGUAGE_MANAGER))
#define EXOGENESIS_IS_LANGUAGE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_LANGUAGE_MANAGER))
#define EXOGENESIS_LANGUAGE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_LANGUAGE_MANAGER, ExogenesisLanguageManagerClass))

typedef struct _ExogenesisLanguageManager ExogenesisLanguageManager;
typedef struct _ExogenesisLanguageManagerClass ExogenesisLanguageManagerClass;

#define EXOGENESIS_TYPE_INSTALL_DATA (exogenesis_install_data_get_type ())
#define EXOGENESIS_INSTALL_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallData))
#define EXOGENESIS_INSTALL_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallDataClass))
#define EXOGENESIS_IS_INSTALL_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_INSTALL_DATA))
#define EXOGENESIS_IS_INSTALL_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_INSTALL_DATA))
#define EXOGENESIS_INSTALL_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_INSTALL_DATA, ExogenesisInstallDataClass))

typedef struct _ExogenesisInstallData ExogenesisInstallData;
typedef struct _ExogenesisInstallDataClass ExogenesisInstallDataClass;

#define EXOGENESIS_TYPE_GENERAL_FUNCTIONS (exogenesis_general_functions_get_type ())
#define EXOGENESIS_GENERAL_FUNCTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_GENERAL_FUNCTIONS, ExogenesisGeneralFunctions))
#define EXOGENESIS_GENERAL_FUNCTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_GENERAL_FUNCTIONS, ExogenesisGeneralFunctionsClass))
#define EXOGENESIS_IS_GENERAL_FUNCTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_GENERAL_FUNCTIONS))
#define EXOGENESIS_IS_GENERAL_FUNCTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_GENERAL_FUNCTIONS))
#define EXOGENESIS_GENERAL_FUNCTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_GENERAL_FUNCTIONS, ExogenesisGeneralFunctionsClass))

typedef struct _ExogenesisGeneralFunctions ExogenesisGeneralFunctions;
typedef struct _ExogenesisGeneralFunctionsClass ExogenesisGeneralFunctionsClass;

#define EXOGENESIS_TYPE_PREVIOUS_OS (exogenesis_previous_os_get_type ())
#define EXOGENESIS_PREVIOUS_OS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_PREVIOUS_OS, ExogenesisPreviousOS))
#define EXOGENESIS_PREVIOUS_OS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_PREVIOUS_OS, ExogenesisPreviousOSClass))
#define EXOGENESIS_IS_PREVIOUS_OS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_PREVIOUS_OS))
#define EXOGENESIS_IS_PREVIOUS_OS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_PREVIOUS_OS))
#define EXOGENESIS_PREVIOUS_OS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_PREVIOUS_OS, ExogenesisPreviousOSClass))

typedef struct _ExogenesisPreviousOS ExogenesisPreviousOS;
typedef struct _ExogenesisPreviousOSClass ExogenesisPreviousOSClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _exogenesis_hd_manager_unref0(var) ((var == NULL) ? NULL : (var = (exogenesis_hd_manager_unref (var), NULL)))
#define _exogenesis_language_manager_unref0(var) ((var == NULL) ? NULL : (var = (exogenesis_language_manager_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _exogenesis_general_functions_unref0(var) ((var == NULL) ? NULL : (var = (exogenesis_general_functions_unref (var), NULL)))
#define _exogenesis_previous_os_unref0(var) ((var == NULL) ? NULL : (var = (exogenesis_previous_os_unref (var), NULL)))

#define EXOGENESIS_TYPE_MAIN (exogenesis_main_get_type ())
#define EXOGENESIS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EXOGENESIS_TYPE_MAIN, ExogenesisMain))
#define EXOGENESIS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EXOGENESIS_TYPE_MAIN, ExogenesisMainClass))
#define EXOGENESIS_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EXOGENESIS_TYPE_MAIN))
#define EXOGENESIS_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EXOGENESIS_TYPE_MAIN))
#define EXOGENESIS_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EXOGENESIS_TYPE_MAIN, ExogenesisMainClass))

typedef struct _ExogenesisMain ExogenesisMain;
typedef struct _ExogenesisMainClass ExogenesisMainClass;
typedef struct _ExogenesisMainPrivate ExogenesisMainPrivate;
typedef struct _ExogenesisParamSpecMain ExogenesisParamSpecMain;

typedef enum  {
	EXOGENESIS_XML_ERROR_FILE_NOT_FOUND,
	EXOGENESIS_XML_ERROR_XML_DOCUMENT_EMPTY
} ExogenesisXmlError;
#define EXOGENESIS_XML_ERROR exogenesis_xml_error_quark ()
struct _ExogenesisMain {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ExogenesisMainPrivate * priv;
};

struct _ExogenesisMainClass {
	GTypeClass parent_class;
	void (*finalize) (ExogenesisMain *self);
};

struct _ExogenesisParamSpecMain {
	GParamSpec parent_instance;
};


extern ExogenesisMainWin* exogenesis_exoMainWin;
ExogenesisMainWin* exogenesis_exoMainWin = NULL;
extern GtkWindow* exogenesis_winbkgrd;
GtkWindow* exogenesis_winbkgrd = NULL;
extern ExogenesisHDManager* exogenesis_gHDManager;
ExogenesisHDManager* exogenesis_gHDManager = NULL;
extern ExogenesisLanguageManager* exogenesis_gLanguageManager;
ExogenesisLanguageManager* exogenesis_gLanguageManager = NULL;
extern ExogenesisInstallData* exogenesis_gInstallData;
ExogenesisInstallData* exogenesis_gInstallData = NULL;
extern ExogenesisGeneralFunctions* exogenesis_gGenFunc;
ExogenesisGeneralFunctions* exogenesis_gGenFunc = NULL;
extern ExogenesisPreviousOS* exogenesis_gPreviousOS;
ExogenesisPreviousOS* exogenesis_gPreviousOS = NULL;
extern gchar* exogenesis_AppPath;
gchar* exogenesis_AppPath = NULL;
extern gboolean exogenesis_DebugMode;
gboolean exogenesis_DebugMode = FALSE;
static gpointer exogenesis_main_parent_class = NULL;

GType exogenesis_main_win_get_type (void) G_GNUC_CONST;
gpointer exogenesis_hd_manager_ref (gpointer instance);
void exogenesis_hd_manager_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_hd_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_hd_manager (GValue* value, gpointer v_object);
void exogenesis_value_take_hd_manager (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_hd_manager (const GValue* value);
GType exogenesis_hd_manager_get_type (void) G_GNUC_CONST;
gpointer exogenesis_language_manager_ref (gpointer instance);
void exogenesis_language_manager_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_language_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_language_manager (GValue* value, gpointer v_object);
void exogenesis_value_take_language_manager (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_language_manager (const GValue* value);
GType exogenesis_language_manager_get_type (void) G_GNUC_CONST;
GType exogenesis_install_data_get_type (void) G_GNUC_CONST;
gpointer exogenesis_general_functions_ref (gpointer instance);
void exogenesis_general_functions_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_general_functions (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_general_functions (GValue* value, gpointer v_object);
void exogenesis_value_take_general_functions (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_general_functions (const GValue* value);
GType exogenesis_general_functions_get_type (void) G_GNUC_CONST;
gpointer exogenesis_previous_os_ref (gpointer instance);
void exogenesis_previous_os_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_previous_os (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_previous_os (GValue* value, gpointer v_object);
void exogenesis_value_take_previous_os (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_previous_os (const GValue* value);
GType exogenesis_previous_os_get_type (void) G_GNUC_CONST;
#define EXOGENESIS_UIPath "/home/steve/1-work/anjuta/exogenesis/src/exogenesis.ui"
gint exogenesis_main (gchar** args, int args_length1);
ExogenesisHDManager* exogenesis_hd_manager_new (void);
ExogenesisHDManager* exogenesis_hd_manager_construct (GType object_type);
ExogenesisLanguageManager* exogenesis_language_manager_new (void);
ExogenesisLanguageManager* exogenesis_language_manager_construct (GType object_type);
ExogenesisInstallData* exogenesis_install_data_new (void);
ExogenesisInstallData* exogenesis_install_data_construct (GType object_type);
ExogenesisGeneralFunctions* exogenesis_general_functions_new (void);
ExogenesisGeneralFunctions* exogenesis_general_functions_construct (GType object_type);
ExogenesisPreviousOS* exogenesis_previous_os_new (void);
ExogenesisPreviousOS* exogenesis_previous_os_construct (GType object_type);
void exogenesis_FadeDesktop (void);
ExogenesisMainWin* exogenesis_main_win_new (void);
ExogenesisMainWin* exogenesis_main_win_construct (GType object_type);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
gboolean exogenesis_w_ExposeEvent (GtkWidget* w, GdkEventExpose* evnt);
GQuark exogenesis_xml_error_quark (void);
gpointer exogenesis_main_ref (gpointer instance);
void exogenesis_main_unref (gpointer instance);
GParamSpec* exogenesis_param_spec_main (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void exogenesis_value_set_main (GValue* value, gpointer v_object);
void exogenesis_value_take_main (GValue* value, gpointer v_object);
gpointer exogenesis_value_get_main (const GValue* value);
GType exogenesis_main_get_type (void) G_GNUC_CONST;
enum  {
	EXOGENESIS_MAIN_DUMMY_PROPERTY
};
ExogenesisMain* exogenesis_main_new (void);
ExogenesisMain* exogenesis_main_construct (GType object_type);
static void exogenesis_main_finalize (ExogenesisMain* obj);


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


gint exogenesis_main (gchar** args, int args_length1) {
	gint result = 0;
	gchar* _tmp0_ = NULL;
	ExogenesisHDManager* _tmp1_ = NULL;
	ExogenesisLanguageManager* _tmp2_ = NULL;
	ExogenesisInstallData* _tmp3_ = NULL;
	ExogenesisGeneralFunctions* _tmp4_ = NULL;
	ExogenesisPreviousOS* _tmp5_ = NULL;
	ExogenesisMainWin* _tmp6_ = NULL;
	gtk_init (&args_length1, &args);
	gst_init (&args_length1, &args);
	if (args_length1 > 1) {
		if (g_strcmp0 (args[1], "DEBUG") == 0) {
			exogenesis_DebugMode = TRUE;
		}
	}
	_tmp0_ = g_get_current_dir ();
	_g_free0 (exogenesis_AppPath);
	exogenesis_AppPath = _tmp0_;
	_tmp1_ = exogenesis_hd_manager_new ();
	_exogenesis_hd_manager_unref0 (exogenesis_gHDManager);
	exogenesis_gHDManager = _tmp1_;
	_tmp2_ = exogenesis_language_manager_new ();
	_exogenesis_language_manager_unref0 (exogenesis_gLanguageManager);
	exogenesis_gLanguageManager = _tmp2_;
	_tmp3_ = exogenesis_install_data_new ();
	_g_object_unref0 (exogenesis_gInstallData);
	exogenesis_gInstallData = _tmp3_;
	_tmp4_ = exogenesis_general_functions_new ();
	_exogenesis_general_functions_unref0 (exogenesis_gGenFunc);
	exogenesis_gGenFunc = _tmp4_;
	_tmp5_ = exogenesis_previous_os_new ();
	_exogenesis_previous_os_unref0 (exogenesis_gPreviousOS);
	exogenesis_gPreviousOS = _tmp5_;
	if (!exogenesis_DebugMode) {
		exogenesis_FadeDesktop ();
	}
	_tmp6_ = exogenesis_main_win_new ();
	_g_object_unref0 (exogenesis_exoMainWin);
	exogenesis_exoMainWin = g_object_ref_sink (_tmp6_);
	gtk_window_set_title ((GtkWindow*) exogenesis_exoMainWin, "Exogenesis");
	gtk_window_set_transient_for ((GtkWindow*) exogenesis_exoMainWin, exogenesis_winbkgrd);
	g_signal_connect ((GtkWidget*) exogenesis_exoMainWin, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_main ();
	result = 0;
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return exogenesis_main (argv, argc);
}


void exogenesis_FadeDesktop (void) {
}


gboolean exogenesis_w_ExposeEvent (GtkWidget* w, GdkEventExpose* evnt) {
	gboolean result = FALSE;
	g_return_val_if_fail (w != NULL, FALSE);
	result = FALSE;
	return result;
}


GQuark exogenesis_xml_error_quark (void) {
	return g_quark_from_static_string ("exogenesis_xml_error-quark");
}


ExogenesisMain* exogenesis_main_construct (GType object_type) {
	ExogenesisMain* self = NULL;
	self = (ExogenesisMain*) g_type_create_instance (object_type);
	return self;
}


ExogenesisMain* exogenesis_main_new (void) {
	return exogenesis_main_construct (EXOGENESIS_TYPE_MAIN);
}


static void exogenesis_value_main_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void exogenesis_value_main_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		exogenesis_main_unref (value->data[0].v_pointer);
	}
}


static void exogenesis_value_main_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = exogenesis_main_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer exogenesis_value_main_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* exogenesis_value_main_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ExogenesisMain* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = exogenesis_main_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* exogenesis_value_main_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ExogenesisMain** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = exogenesis_main_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* exogenesis_param_spec_main (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ExogenesisParamSpecMain* spec;
	g_return_val_if_fail (g_type_is_a (object_type, EXOGENESIS_TYPE_MAIN), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer exogenesis_value_get_main (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_MAIN), NULL);
	return value->data[0].v_pointer;
}


void exogenesis_value_set_main (GValue* value, gpointer v_object) {
	ExogenesisMain* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, EXOGENESIS_TYPE_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		exogenesis_main_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		exogenesis_main_unref (old);
	}
}


void exogenesis_value_take_main (GValue* value, gpointer v_object) {
	ExogenesisMain* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EXOGENESIS_TYPE_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, EXOGENESIS_TYPE_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		exogenesis_main_unref (old);
	}
}


static void exogenesis_main_class_init (ExogenesisMainClass * klass) {
	exogenesis_main_parent_class = g_type_class_peek_parent (klass);
	EXOGENESIS_MAIN_CLASS (klass)->finalize = exogenesis_main_finalize;
}


static void exogenesis_main_instance_init (ExogenesisMain * self) {
	self->ref_count = 1;
}


static void exogenesis_main_finalize (ExogenesisMain* obj) {
	ExogenesisMain * self;
	self = EXOGENESIS_MAIN (obj);
}


GType exogenesis_main_get_type (void) {
	static volatile gsize exogenesis_main_type_id__volatile = 0;
	if (g_once_init_enter (&exogenesis_main_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { exogenesis_value_main_init, exogenesis_value_main_free_value, exogenesis_value_main_copy_value, exogenesis_value_main_peek_pointer, "p", exogenesis_value_main_collect_value, "p", exogenesis_value_main_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ExogenesisMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) exogenesis_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ExogenesisMain), 0, (GInstanceInitFunc) exogenesis_main_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType exogenesis_main_type_id;
		exogenesis_main_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ExogenesisMain", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&exogenesis_main_type_id__volatile, exogenesis_main_type_id);
	}
	return exogenesis_main_type_id__volatile;
}


gpointer exogenesis_main_ref (gpointer instance) {
	ExogenesisMain* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void exogenesis_main_unref (gpointer instance) {
	ExogenesisMain* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		EXOGENESIS_MAIN_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



